### ISSUE TITLE
Push-based scheduler optimization

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1002]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1002)
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Apr 17, 2019, 09:16

## Background
Original proposal from [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert): https://mail.gnome.org/archives/buildstream-list/2019-March/msg00034.html

> I've been looking at the scheduler and the queues and from what I can see in
> some benchmarks and profiles, they are becoming an important bottleneck,
> especially with a large number of workers.
> 
> A few issues have been raised over time about that:
> - https://gitlab.com/BuildStream/buildstream/issues/824
> - https://gitlab.com/BuildStream/buildstream/issues/943
> 
> Currently, the queues go over every element until they find enough elements to
> fill up all resources. While this works fine with few workers, since the
> probability of finding a job that is ready early in the queue is quite high,
> the performance degrades when more workers are added, as the probability to have
> many jobs ready early decreases.
> 
> The problem becomes even worse when we are using remote execution with many
> workers.
> 
> I therefore think we should be pushing items in the queue as soon as they are
> needed.

## Tasks
* [ ] Add core scheduler support for queues that use push/callback-based ready state change instead of the current approach of calling `Queue.status()` on every element in `harvest_jobs()`.

  This first task is just about the core Scheduler/Queue code, without actually using the new functionality in the individual queues yet.

* [ ] Use push/callback-based approach in

    * PullQueue
    * FetchQueue
    * BuildQueue

   The other queues do not use `QueueStatus.WAIT` and thus should not require significant changes.

   These tasks will require corresponding changes in the `Element` class.

* [ ] Drop the old `Queue.status()`-based ready check / wait queue.

   `Queue.status()` should likely continue to exist (possibly under a different name) to decide whether the element should completely skip the queue. It might also make sense to keep using it to determine whether an element is immediately ready when it's enqueued. However, it should no longer be called as part of `harvest_jobs()`.

* [ ] Maybe: Defer enqueuing (non-track) elements before they are marked as 'required'.

   I don't think this is strictly necessary as this can also be handled by the push/callback-based approach within the pull/fetch/build queues. However, it might be slightly cleaner to do it in `Stream`.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on May 15, 2019, 14:07

mentioned in merge request !1344

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jun 4, 2019, 17:02

assigned to [[Gitlab user @jennis]](https://gitlab.com/jennis)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Jun 7, 2019, 16:05

closed via merge request !1344

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Jun 7, 2019, 16:05

mentioned in commit 16338464b15f8836cd6e84b9e7bc11047494cc66
