### ISSUE TITLE
Run UI in a seperatate process to the scheduler.

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1036]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1036)
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on May 28, 2019, 17:18

## Background

[//]: # (Provide a background or the root/source that justifies this task or action.)
In the last round of profiling data collected by [[Gitlab user @danielsilverstone-ct]](https://gitlab.com/danielsilverstone-ct), we could see that UI rendering is taking up a significant proportion of the CPU time in BuildStream's main process.

Further investigation has shown that the UI rendering is a performance bottleneck. This is particularly obvious when IO is slow and writing to the screen is expensive, with [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) observing on his system (using BuildStream in docker through bash.exe on a Windows machine) that 40% of the time is spent writing to the screen, with the main process running at 100% of a cpu. Having the UI and the scheduler run is separate processes would remove this bottleneck.

One possible approach is to have the UI remain in the main process, with the scheduling process running as a subprocess. The scheduling process will be managed and abstracted by the `Stream`, without being known to the front-end. As part of this work, message handling will be refactored so that all state required by the front-end will be passed explicitly with each `Message` object, where the front-end currently relies on some global state. All signals and user input will be handled by the front-end, which will tell the stream what the appropriate actions are.

The details of how interactive shells will work have not yet been ironed out, though various approaches have been discussed on the list. This will need some experimentation. 

This was discussed in [this ML thread](https://mail.gnome.org/archives/buildstream-list/2019-May/msg00011.html). Whilst there are still details to iron out, we're at a point where it makes sense to put together a proof of concept to verify that the proposed approach will work and that we can actually achieve some performance improvements. 

## Task description

Current task proposal is below. Please note that points 1-4 exist in various states in the branch `phil/ui-split-refactor` - this branch contains the PoC and our plan is to try to merge the below points as small, digestable MRs into master, and re-base our branch as we go.

* [x]  Rework LoadError exception to bring arg ordering inline with the rest of exception classes. The subclassing of exceptions brings issues under pickle especially when a given positional arg is named message, amongst other issues. Instead of hacking around to make this work a single MR should be completed to align the ordering throughout the codebase. Some info around this is [here](https://stackoverflow.com/questions/41808912/cannot-unpickle-exception-subclass/41809333#41809333) and the work is captured in https://gitlab.com/BuildStream/buildstream/merge_requests/1489

* [x]  MR to add the changes for the message/job construction. This MR will include changes to the message class itself and how they are generated. For instance an elementjob will use it's element_full_name as the unique_id to avoid a full Plugin table lookup in the main process just to gather the same string (this isn't just wasteful, it's also not going to work with concurrency of the given state). It should also make the messages more 'correct', in the sense that the data is encoded when the message is generated instead of later in the process. This lives at https://gitlab.com/BuildStream/buildstream/merge_requests/1500

* [x] MR to remove the need for anything in the frontend (App) to require an Element or Queue instance, with it operating on just the name after which the 'backend' will process against the given object. This might require a generic implementation that will then be utilised with the bidirectional notification handler. This lives at https://gitlab.com/BuildStream/buildstream/merge_requests/1546

* [x]  Add basis of 'NotificationHandler' between stream-scheduler. An MR can be created for the initial handler implementation, which abstracts the callbacks from the frontend (job start,complete,interrupt,tick) to the scheduler via stream. This should be a multiprocessing queue used for further frontend-subprocess notifications which need to emit into the main process (exception handling, queue/task group state, task errors etc). This needs to be bi-directional to allow the app to notify the 'backend' on which objects (such as Elements which will exist in different states in each process) to act on. This lives at https://gitlab.com/BuildStream/buildstream/merge_requests/1550

* [x]  PoC/MVP for multiprocessing implementation. This implementation will take the form of a context manager(**Update** it doesn't seem plausible to support pickling of subproccessed methods under a context manager, so this approach will be different) which covers the entry points into stream, which go on to invoke a scheduler. At which exact point the process split happens is not yet final, as having certain things loaded in the frontend may prove useful, for example when handling an interactive build failure shell. Initially this will be applied to build as the most prominent usecase, also ensuring the basis of the architectural changes are benchmarked and the impelentation is reviewed before undertaking it across further methods. This MR will include changes that are needed to support the addition of the concurrency beyond the existing concurrency (the scheduler jobs are already multiprocessed, meaning there's extra complexity for ensuring state is mirrored in the new 'main' process). There might also need to be work around the handling of status rendering for Tasks across State/Messenger, which did not exist at the time of the original implementation. This lives at https://gitlab.com/BuildStream/buildstream/merge_requests/1613

* [x]  Further work on the separation of processes. The queue into the subprocess (specifically the scheduler) needs to be handled in a bi-directional manner, more than likely achieved by have two queues, one for each direction. The frontend app currently initiates the scheduler terminating it's asyncio processes, this should be handleded by the queue into the sub-processed operation. Once the scheduler is fully abstracted into a subprocess, the SIG handling should be moved into the main process as we will be able to run another asyncio loop for this. With this in place the 'frontend/main process' will instruct the scheduler how to behave when such signals are caught, switching the current control flow of the scheduler waiting for the frontend to respond with what it should do.

* [x] Once there's an async event loop on both sides of the notification handler (stream & scheduler) then benchmarks & profiling should be assessed to determine the characteristics between non-interactive bst builds (sig handling not needed), with & without the multiprocess implementation. These should be conducted on both linux & WSL (WSL is where click.echo was showing the most overheads in profiling). At this point it should be decided upon if the added code complexity and maintenance cost (especially if landed in an opt-in/experimental state) is worth any originally perceived benefits of the process seperation

* [ ]  Handling 'on-the-fly' build failures in interactive mode, where the user delegates that they wish to load a build shell into the sandbox. There is still no concrete plan on how to handle this (as seen on the mailing list thread). (This may now come under 3rd bulletpoint, to be included with the notification handling. As it stands the initial implementation may require the selection to be loaded via the element name, as is the case if loading a new build shell)

## Acceptance Criteria

[//]: # (Acceptance criteria should follow the S.M.A.R.T. principle https://en.wikipedia.org/wiki/SMART_criteria )

----
[//]: # (To review information about possible relevant labels for this issue please view the list of labels: https://gitlab.com/BuildStream/buildstream/labels)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on May 28, 2019, 17:58

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on May 31, 2019, 14:27

Just some thought re the in-flight shelling into failed builds. By *default* bst will cache the buildtree of a failed element into the artifact, so this could possibly give the frontend an entry point into constructing the build sandbox. However as I mentioned this is the default bst behaviour, it can be changed via user configuration to never cache buildtrees and as has been discussed previously that running in this mode could affect expect bst operations. (This obviously doesn't apply to 'in-flight' shell debugging afaik)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Jun 3, 2019, 15:33

As the scheduler uses multiprocessing to spawn jobs, the Stream will not be able to spawn it's 'scheduling processes' as [daemon threads](https://docs.python.org/3.7/library/multiprocessing.html?highlight=process#multiprocessing.Process.daemon). However if Stream is the only point of direct communication to the spawned process (as it will mediate all callbacks required to the frontend, the frontend should not be aware of the scheduler) then using `Pipe()` may be beneficial for performance. I'm not currently seeing a situation where one Stream invoked subproccess would need to speak to another.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Jun 3, 2019, 17:41

I've been having a look at this, because it runs into similar problems to !1029.
Specifically, I'm looking at how to get information to the status renderer without inspecting internals that won't be accurate after the UI is separated from the scheduler.

Note that AIUI, the scheduler will fork off from the UI process at `Stream._run()` (i.e. all Elements have been constructed, and all Queues have been added to the Scheduler).

So, far, I've found the following incidents of the UI using internals that won't be accessible/accurate after forking:
* _frontend/status.py:
  - The Status class uses the Stream's elapsed_time property repeatedly. This calls out to the Scheduler, which has Scheduler._starttime, which is modified so that time that elapsed while the Scheduler is suspended doesn't count.
  - It also uses the lengths of Stream.session_elements and Stream.total_elements, (i.e. length of the list of target elements, and length of the whole pipeline). This should be stable after forking because they won't change, but gets in the way of a clean separation of what information gets passed to the frontend.
  - Plus, it iterates over the list of Queues in the Stream, using:
    - The length of the list of Queues
    - The length of the Queue's processed_elements, skipped_elements and failed_elements
    - The Queue's complete_name
* _frontend/widget.py:
  - `ElementName.render()` widget looks up the element by its ID and gets the plugin's full name (breaks separation, will give a consistent result pre/post forking)
  - `CacheKey.render()` does a similar trick and gets the element's cache key. This will give inconsistent results pre/post forking, as cache key calculation may occur in the scheduler process post-fork)
  - `LogLine.show_pipeline()` iterates over the elements given as arguments and reads a lot of information from them (`_get_display_key()`, `_get_consistency()`, `_source_cached()` and `_Element__public` are not going to be consistent post-fork).
    - `show_pipeline()` is called in three places:
      - in _frontend/cli.py::show, which does not require the scheduler to be started iirc.
      - in `LogLine.print_heading()`, which is only called by the `App.session_start_cb()` which is only called by `Stream._run()`, so probably occurs pre-fork.
      - in `LogLine.print_summary()`, which is only called in `App.initialized()` post-yield. This *will* be inconsistent after process separation.
  - `LogLine.print_summary()` also uses an element's name and cache key, and iterates over all the Queues just like Status does.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Jun 3, 2019, 18:24

To propagate this information back to the frontend, we would need:
* A callback to the frontend when `Scheduler._starttime` is changed
* A proper Task interface to replace reading the Queues (big job, I haven't thought this through in detail yet)
* element_update_cache_key, element_update_consistency, element_update_source_cached, and element_update_public callbacks.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Jun 4, 2019, 11:39

[[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) I may be wrong, but I believe each entrypoint will have it's entire function body spawned into a subprocess (via a decorator), meaning this may be separated before the queues are added to the scheduler etc. Is this correct [[Gitlab user @phildawson]](https://gitlab.com/phildawson)?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Jun 4, 2019, 12:21

If you're referring to methods like `Stream.push()`, `Stream.fetch()` and `Stream.build()`, then running the whole function body in a subprocess is an extra complication to my understanding, as that means that loading elements also happens in a subprocess.

I'll have a look at how that would affect things.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Jun 4, 2019, 16:44

If the pipeline's loaded post-fork, we'll need to load some kind of representation for the whole pipeline.
It looks like the information that would have to be sent to the frontend is:
* The list of all elements in the pipeline
* Individual data from each element on:
  - The element's full name
  - Whether an element is workspaced
  - The workspace's directory
  - The yaml of the element's config, variables, environment variables, and its public data
    (public data can change during a scheduler run, too)
  - The element's Scope.ALL, Scope.BUILD and Scope.RUN dependencies.
  - The element's full cache key, abbreviated cache key, and whether the key should be dimmed when rendering
    (this information is all used at once)
  - The element's consistency / cached success / cached failure / whether the source is cached / buildableness
    (It would be easier to replace this with a single piece of information and have the Element determine it)
* The list of all plugins loaded (the classes, not their instances)
* The full list of queues, using:
  - The queue's name (Queue.complete_name)
  - The names of every element in the processed_elements, skipped_elements and failed_elements lists.
    (technically, we only need the names for the failed_elements list, to cross-reference with the error messages received)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Jun 4, 2019, 17:14

Right, that is quite a lot of extra data! I presume some of this is crossover with what is needed for the message object refactor where certain extra state/info needs to be added when the message is initialised. 

I believe the initial implementation approach was going to be 'wrapping' each scheduler _run() within Stream as the subprocess but that later developed into each entry point being a separate process to ensure encapsulation over each bst function and increasing the separation from the main frontend process. 

Having a myriad of callbacks and hefty state objects between the queues/pipes to achieve this through a single Stream entry point for the frontend will be challenging.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Jun 4, 2019, 18:02

It looks like to carry this information, it would make sense to have a "UI State" class, which holds information that the UI needs. (the _frontend/status.py file currently stores some state (current jobs), but is documented as just a widget for rendering so I'm not comfortable having all this state in there).

In this UIState, I'd store:
* TaskGroups (alternative to Queues. Have names and ordering, contain Tasks)
  - Lists of Tasks named "active", "processed", "skipped" and "failed" (would be able to take the processed, skipped and failed lists out of the Queues).
  * Tasks (start time, action name, full name, progress?)
* pipeline, a list of `ElementProxy`s (maybe UIElement is a more helpful name?)
  - full_name
  - workspaced
  - workspace_dir
  - config, variables, env, public_data (yaml)
  - all_depends, build_depends, run_depends (lists of element names)
  - cache key (move abbreviation logic into ElementProxy or the CacheKey widget)
  - dim_key (whether the cache key should be dimmed, usually whether the cache key isn't equal to the strict cache key)
  - "state" (could be "no reference", "failed", "cached", "fetch needed", "buildable" or "waiting"; easier to send this than the element's cachedness, source state and buidlableness)

I'll spend some time thinking about what messages we'd need to pass around to keep this information synchronised next.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Jun 5, 2019, 14:45

We may need to take a look at using dill (and in turn, [multiprocess](https://pypi.org/project/multiprocess/)) if we're creating and carry complex objects between the subprocess that have types not supported by the standard multiprocessing pickle. From what I can tell dill is slower than cPickle but it has a wider range of supported types (it also has configurable .settings for tuning performance where applicable).

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Jun 11, 2019, 13:42

If we're going down the decorator route for adding the entry point into stream, which will then handle starting the desired methods as subprocesses then we may benefit from https://github.com/alex-sherman/deco *can't use on class methods

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Jun 13, 2019, 12:51

mentioned in merge request !1398

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Jun 14, 2019, 17:18

Myself & [[Gitlab user @phildawson]](https://gitlab.com/phildawson) have some early WIP/PoC work which is currently lazily committed to the branch `phil/ui-split-refactor` (note bst won't work here, still niggling out errors)

The branch contains the foundations for 2 of the aspects that we see as needing to be implemented before multiprocessing can be added. These being:

> "Refactoring Message object handling so as much about the state at which
> the object was generated is encoded into it, removing the need for the
> status to reference back into backend/ scheduler process as much as possible."


This is mostly done, however there are still some errors in the tests that need to be rectified.

> "Decoupling/reworking of mechanisms where the scheduler waits for a
> frontend response callbacks for coupled actions. The frontend should
> have as little knowledge of the schedulers actions as possible,
> instructing it, via Stream, when a certain action is triggered."

Here we've taken the approach of handling the 4 callbacks from the scheduler to frontend via a single point of entry via stream. Stream now implements a simple 'notification' handler with the scheduler, using these notifications to trigger the needed frontend callbacks, along with any data that was needed in the previous implementation. When the body of stream processes are ran in subprocesses (this will include the related scheduler process) this message handler will sit in the main process & should hopefully notify the frontend with the needed state data. Once we have subprocessing in place, we can move the async interrupt ctrl^c handling into the main thread so the 'frontend main process' has full control, where currently the scheduler handles it. As the scheduler will live in a subprocess it's job asyncio handling will not be affected and should allow it's custom handling to be unaffected.

We've also highlighted other aspects that can/should be implemented before we apply multiprocessing, all of which should lower the friction cause when hacking into it.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Jun 25, 2019, 12:15

mentioned in merge request !1409

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Jul 17, 2019, 12:00

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Jul 17, 2019, 12:53

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Jul 17, 2019, 16:26

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Jul 17, 2019, 17:01

mentioned in merge request !1489

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Jul 17, 2019, 17:05

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Jul 18, 2019, 15:15

marked the task **Rework LoadError exception to bring arg ordering inline with the rest of exception classes. The subclassing of exceptions brings issues under pickle especially when a given positional arg is named message, amongst other issues. Instead of hacking around to make this work a single MR should be completed to align the ordering throughout the codebase. Some info around this is here https://stackoverflow.com/questions/41808912/cannot-unpickle-exception-subclass/41809333#41809333** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jul 24, 2019, 15:00

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Jul 25, 2019, 16:55

mentioned in merge request !1500

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Aug 1, 2019, 15:51

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Aug 8, 2019, 14:56

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Aug 8, 2019, 16:36

marked the task **MR to add the changes for the message/job construction. This MR will include changes to the message class itself and how they are generated. For instance an elementjob will use it's element_full_name as the unique_id to avoid a full Plugin table lookup in the main process just to gather the same string (this isn't just wasteful, it's also not going to work with concurrency of the given state). It should also make the messages more 'correct', in the sense that the data is encoded when the message is generated instead of later in the process. This lives at https://gitlab.com/BuildStream/buildstream/merge_requests/1500** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Aug 8, 2019, 16:37

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Aug 8, 2019, 16:37

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Aug 12, 2019, 12:37

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Aug 13, 2019, 12:03

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Aug 14, 2019, 16:48

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Aug 16, 2019, 12:59

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Aug 16, 2019, 13:03

mentioned in merge request !1550

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Aug 16, 2019, 13:03

mentioned in merge request !1546

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Aug 20, 2019, 09:00

marked the task **MR to remove the need for anything in the frontend (App) to require an Element or Queue instance, with it operating on just the name after which the 'backend' will process against the given object. This might require a generic implementation that will then be utilised with the bidirectional notification handler. This lives at https://gitlab.com/BuildStream/buildstream/merge_requests/1546** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Sep 10, 2019, 11:33

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Sep 10, 2019, 12:08

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Sep 10, 2019, 13:02

marked the task **Add basis of 'NotificationHandler' between stream-scheduler. An MR can be created for the initial handler implementation, which abstracts the callbacks from the frontend (job start,complete,interrupt,tick) to the scheduler via stream. This should be a multiprocessing queue used for further frontend-subprocess notifications which need to emit into the main process (exception handling, queue/task group state, task errors etc). This needs to be bi-directional to allow the app to notify the 'backend' on which objects (such as Elements which will exist in different states in each process) to act on. This lives at https://gitlab.com/BuildStream/buildstream/merge_requests/1550** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Sep 27, 2019, 18:02

mentioned in merge request !1613

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Oct 2, 2019, 10:21

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Oct 7, 2019, 14:37

marked this issue as related to #1160

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Oct 7, 2019, 15:36

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Oct 7, 2019, 15:47

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Oct 31, 2019, 16:13

marked the task **PoC/MVP for multiprocessing implementation. This implementation will take the form of a context manager(**Update** it doesn't seem plausible to support pickling of subproccessed methods under a context manager, so this approach will be different) which covers the entry points into stream, which go on to invoke a scheduler. At which exact point the process split happens is not yet final, as having certain things loaded in the frontend may prove useful, for example when handling an interactive build failure shell. Initially this will be applied to build as the most prominent usecase, also ensuring the basis of the architectural changes are benchmarked and the impelentation is reviewed before undertaking it across further methods. This MR will include changes that are needed to support the addition of the concurrency beyond the existing concurrency (the scheduler jobs are already multiprocessed, meaning there's extra complexity for ensuring state is mirrored in the new 'main' process). There might also need to be work around the handling of status rendering for Tasks across State/Messenger, which did not exist at the time of the original implementation. This lives at https://gitlab.com/BuildStream/buildstream/merge_requests/1613** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Oct 31, 2019, 16:13

marked the task **Further work on the separation of processes. The queue into the subprocess (specifically the scheduler) needs to be handled in a bi-directional manner, more than likely achieved by have two queues, one for each direction. The frontend app currently initiates the scheduler terminating it's asyncio processes, this should be handleded by the queue into the sub-processed operation. Once the scheduler is fully abstracted into a subprocess, the SIG handling should be moved into the main process as we will be able to run another asyncio loop for this. With this in place the 'frontend/main process' will instruct the scheduler how to behave when such signals are caught, switching the current control flow of the scheduler waiting for the frontend to respond with what it should do.** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Nov 28, 2019, 12:47

marked the task **Once there's an async event loop on both sides of the notification handler (stream & scheduler) then benchmarks & profiling should be assessed to determine the characteristics between non-interactive bst builds (sig handling not needed), with & without the multiprocess implementation. These should be conducted on both linux & WSL (WSL is where click.echo was showing the most overheads in profiling). At this point it should be decided upon if the added code complexity and maintenance cost (especially if landed in an opt-in/experimental state) is worth any originally perceived benefits of the process seperation** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Jun 26, 2020, 09:26

unassigned [[Gitlab user @phildawson]](https://gitlab.com/phildawson)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Jun 26, 2020, 12:41

This should have been closed along with https://gitlab.com/BuildStream/buildstream/-/merge_requests/1613#note_365424938

I'll repeat the comment here as I close this issue:

> Given that the benchmarks of this MR ended up being not better than no split, I will close this MR and we can always re-open or cherry-pick pieces if we want later on.
> Thanks for this experimentation!

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Jun 26, 2020, 12:41

closed
