### ISSUE TITLE
Move source cache to proto based service

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1038]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1038)
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on May 29, 2019, 13:48

## Background

[//]: # (Provide a background or the root/source that justifies this task or action.)
The source cache should move towards using a protocol buffer based format similar to new artifact service architecture (overall plan described in #909). The reference service should be kept for now to allow it to be used with older buildstream clients.

## Task description

[//]: # (Short summary of the action to be executed)

* [x] Design new source protos. This should be similar to artifact protos and may include metadata such as the sources provenance data.
* [x] Implement new `SourceCacheService` that uses this.
* [x] Use new `SourceCacheService` in `SourceCache` for pulling and pushing sources.

## Acceptance Criteria

[//]: # (Acceptance criteria should follow the S.M.A.R.T. principle https://en.wikipedia.org/wiki/SMART_criteria )
All old source cache tests pass using new source protos.

----
[//]: # (To review information about possible relevant labels for this issue please view the list of labels: https://gitlab.com/BuildStream/buildstream/labels)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on May 29, 2019, 13:48

mentioned in merge request !1362

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 19, 2019, 12:11

mentioned in merge request !1410

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 21, 2019, 14:13

assigned to [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 25, 2019, 09:30

mentioned in commit 8bbea0cc9d1c07dbcf7bba563082c31694d92220

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 25, 2019, 09:30

mentioned in commit 35214d0d87c759788a1be22d5e9b77ddecf9806e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 25, 2019, 09:30

mentioned in commit 8e264f093816a63f77e52d58332e8b32d713eb92

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 25, 2019, 09:30

mentioned in commit 55bf188cb681ca0683dda3c82202ee21369cb47d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 25, 2019, 12:16

marked the task **Design new source protos. This should be similar to artifact protos and may include metadata such as the sources provenance data.** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 25, 2019, 12:16

marked the task **Implement new `SourceCacheService` that uses this.** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 26, 2019, 14:08

mentioned in commit c9f8581531a0d583ef3cb21519aefb9e1ba66bd4

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 26, 2019, 14:08

mentioned in commit ef712320ebd39f2259b90ce7cd3f7d9ffdb28a5c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 26, 2019, 14:08

mentioned in commit 544c02367784e2e401760bf171d8b61ae8d3959a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 26, 2019, 14:15

mentioned in commit 8c9df8706969b5346b404c1581299fbcf4e3676e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 26, 2019, 14:15

mentioned in commit 4533989e94d68b80ea1dfd7a59dd7177417f91e7

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 26, 2019, 14:15

mentioned in commit 0d6a1e9fa891e27883689bd65a8f7b46e991162c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 26, 2019, 14:15

mentioned in commit 83352742821de343b499b597c751667fc4d6a763

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 26, 2019, 14:15

mentioned in commit 12874bd9a67492a6d58d5aadd9ed8d5b737a1e0a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 26, 2019, 15:50

mentioned in commit 4dc530b338a4e434bd315d5f2d4102b563f49c77

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 27, 2019, 15:12

mentioned in commit 4032c81019e8dd69ca541e87f99f484ffde3db52

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 27, 2019, 15:12

mentioned in commit 357ab273a01711a592b0ca8de99b501e2c1cb62e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 27, 2019, 15:12

mentioned in commit 78d567dddea3c28f4e737db00a092ae8a82c405e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 27, 2019, 15:12

mentioned in commit 1581ff9cd6f6d8a2ce32d61446de300d85bae4e8

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 27, 2019, 15:12

mentioned in commit a8e04529d62f5c7c9894c45b83330823d4eb6bba

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 27, 2019, 15:42

mentioned in commit 6c540804827d18deb562afb3da19f4039a25c81a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 27, 2019, 15:42

mentioned in commit 0397b66e9bda61035253fa718eff59538a7d211d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 27, 2019, 15:48

mentioned in merge request !1435

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 27, 2019, 15:55

mentioned in commit c76881a12a4dc10194ea3999f6d7d76181c34244

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 27, 2019, 15:55

marked the task **Use new `SourceCacheService` in `SourceCache` for pulling and pushing sources.** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 28, 2019, 15:30

mentioned in commit 5ce4cc7499d8eab81f0fa5f9f3e93249d443605f

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 28, 2019, 15:30

mentioned in commit 6b42c2da0cc248ef0d0819c892feba6d10ca19f1

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 28, 2019, 15:31

mentioned in commit abea6490cb6036b1fa9c898879e5e20956007393

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 28, 2019, 15:31

mentioned in commit caba7d3a59ed24f1edf86366b8a7cf3675b9c1fc

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 28, 2019, 15:31

mentioned in commit b5e84029b07e95b281dfcc0da73f274e1b55b1c3

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 28, 2019, 15:31

mentioned in commit 47ace4076c34f43b9c92ebc01ef3f354b501f5d2

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 28, 2019, 15:45

mentioned in commit 4e2c3b28d89ded00f62e226ee5a3db8a96530c73

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 28, 2019, 15:45

mentioned in commit f9ffbfe9af2bb8563af54b4b7ccc98f5292da030

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 28, 2019, 15:45

mentioned in commit ac7a02fbef5fea5f8ace2357111e3e99794fb515

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 28, 2019, 15:45

mentioned in commit b80260e694c9ac88bd45b79319e10e8c82f7c84f

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 28, 2019, 15:45

mentioned in commit 3f3a29fed5e3dac3634208bf7b724314cfb2896d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 16:59

mentioned in commit 9497b02f9eae40e9dca97c1b325cc6ca6a52fe81

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 16:59

mentioned in commit 2a58f66d09600bdc79d6d25d771274bcc1544434

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 16:59

mentioned in commit 6b13a80e5f4e9792768b04e45266b74944daa643

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 17:39

mentioned in commit eee1512447206b28d62b7bce38e86d96e6c19a3c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 17:39

mentioned in commit e41517f305c23d5efce24ae4a91326fc81d93a32

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 17:39

mentioned in commit 82de872b3ec4eba90e8c022476bf760f350b81b2

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 17:39

mentioned in commit 5fc9ba356b967100260bbfc2aedfa19a193fbf86

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 17:39

mentioned in commit 2259e0453aedfa35f1a7539c19a629302fa9fd82

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 17:39

mentioned in commit 3cd1e50a38595da169e10f9c7f6b5912cb745264

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 17:39

mentioned in commit 14be3c3070f06f3d8194daa8474c035b5776fbc3

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 17:39

mentioned in commit 3063d1df3dba3ceab7ffa9fc7227cf4102d13c3d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 17:39

mentioned in commit 97858e21acf8497543e94f5338b035b12ff1ca1c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 17:39

mentioned in commit ec012e5cd21ce3e0840ad54cd0becd2cb21eb889

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 2, 2019, 16:23

mentioned in commit 0d69662b5d4711098d0bbf6f15b5c0f7da8098a7

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 2, 2019, 16:23

mentioned in commit 5dc76fdb7833fa71d89c2f56a4be098cecf7495b

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 2, 2019, 16:23

mentioned in commit a4e8907c60bffcb51c4057327a9300938df87956

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 2, 2019, 16:23

mentioned in commit 5158c9fce3dae4f88f20a1e6bf48a0d426ac2036

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 2, 2019, 16:23

mentioned in commit c12587ce8e1ef32f1b66ff0399d5b76650f57c90

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 5, 2019, 13:06

mentioned in commit ab06c00ded23866ec88ce9132fe3000c9bfe823b

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 5, 2019, 13:06

mentioned in commit 46418bf79a740fb6c906962e52c243243d2849bb

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 5, 2019, 13:06

mentioned in commit 8d7afd7514f701870ed8333b822a2bb2682ef0de

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 5, 2019, 13:06

mentioned in commit 1fb4716df7caae754501717ad519f5f1e5268a7c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 5, 2019, 13:47

mentioned in commit 2d48dc85f2814d6d2b04e48917c09a415cdbd540

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 5, 2019, 15:44

mentioned in commit b15b32376f6abe1735233bd5d85c42fd1ad5a703

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 8, 2019, 11:40

mentioned in commit bb2cf18be0aef7d6e394a0c6ff6d83eac737c60b

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 8, 2019, 11:40

mentioned in commit 6b6e04ddb1c03f683e3e5591f057207d1303e6b6

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 8, 2019, 11:40

mentioned in commit d493682609f8f96ed127f4083bad42fa2fabb250

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 8, 2019, 11:40

mentioned in commit c20eac1e7ac80e1dc36b23b04affacfbe2cca338

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 8, 2019, 11:40

mentioned in commit d61e21448953942ce90d457dad7189c0dda61bc7

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Jul 8, 2019, 12:17

closed via merge request !1435

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Jul 8, 2019, 12:17

mentioned in commit cf0516ba92fb4a220ae0086c411314cec4974df5

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 8, 2019, 16:41

mentioned in commit d1be05c771bdbe054f01eaaea977d4b20e401354

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 8, 2019, 16:41

mentioned in commit dc689098d164510eb22820776f9c8cf1cf1fd642

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 8, 2019, 16:41

mentioned in commit 38f7bffd87ffd901e316a7966fefc9d189658e19

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 8, 2019, 16:41

mentioned in commit c02c0170058f36eff722bb341edbed3feae18145

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 8, 2019, 16:41

mentioned in commit 107bae99f159d22cbedd155c5db9255782fad3c0
