### ISSUE TITLE
Tracker for hotspots to move to cython

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1039]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1039)
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on May 30, 2019, 12:21

## Summary

[//]: # (Summarize the bug encountered concisely)

We have some hotspots in the code base, that are stable and "leafs" in the codebase.

We should convert them to cython when it makes sense.

This ticket is to track the spots in the code that are potential candidates and coordinate the work made in that regard.

## Candidates

- [ ] `utils.url_directory_name`
- [x] `_loader.types.Dependency`
- [x] `_loader.loadelement._extract_depends_from_node`
- [x] `_loader.loader.valid_chars_name`
- [ ] `element.Element.dependencies`
- [ ] `_loader.Loader._check_circular_deps`
- [ ] `_loader.Loader._sort_dependencies`
- [ ] `node._assert_symbole_name` (needs inlining of the valid_chars)

## Not necessarily hot, but easy to convert now

- [ ] `_loader.Loader._collect_element`
- [ ] `_options.optionpool`
- [ ] `_yaml.FileInfo` use `__cinit__` instead of `__init__`
- [ ] `_yaml.ProvenanceInformation` use `__cinit__` instead of `__init__` 

## Other Cython-related optimizations

- [ ] Stop allowing negative indexing or lists in Cython
- [ ] Use `[[Gitlab user @cython]](https://gitlab.com/cython).freelist()` for heavily used extension types

Feel free to edit or comment on this issue to add more methods that should get cythonized.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @danielsilverstone-ct]](https://gitlab.com/danielsilverstone-ct) on May 30, 2019, 14:41

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @danielsilverstone-ct]](https://gitlab.com/danielsilverstone-ct) on May 30, 2019, 15:35

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on May 31, 2019, 14:08

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on May 31, 2019, 16:26

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on Jun 5, 2019, 11:30

marked the task **`_loader.loader.valid_chars_name`** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on Jun 7, 2019, 09:24

marked the task **`_loader.types.Dependency`** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on Jun 8, 2019, 10:32

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on Jun 8, 2019, 10:32

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on Jun 20, 2019, 10:27

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on Jun 20, 2019, 10:27

mentioned in merge request !1401

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on Jul 10, 2019, 08:52

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on Jul 12, 2019, 11:41

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on Jul 12, 2019, 17:07

marked the task **`_loader.loadelement._extract_depends_from_node`** as completed
