### ISSUE TITLE
Support separate end points for artifact caches

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1041]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1041)
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on May 31, 2019, 17:05

## Background

[//]: # (Provide a background or the root/source that justifies this task or action.)
BuildStream currently assumes that the ArtifactService/ReferenceService endpoint and the CAS endpoint are the same for a cache, this is not the case if we're using other projects for remote CAS (i.e. buildgrid). This also means that the storage service for remote execution can be the same as for buildstream caches.

## Task description

[//]: # (Short summary of the action to be executed)

* [ ] Extend configuration to support separate end points for the artifact service and the CAS. Should also be able to specify that both are provide by one end point with previous, which should also mean old configurations don't break.
* [ ] `CasRemote`/`ArtifactRemote` will need some refactoring to support initialising these separately in different remote objects.
* [ ] Update ArtifactCache to look at these separately, querying the artifact end points to get the metadata and then the CAS end point to pull/push artifact files. 
     * [ ] refactoring some code to separate it into artifact push/pull methods and then storage push_pull methods.
     * [ ] Loop through services and then storage end points to pull/push
* [ ] Reference/source cache methods will similarly have to change to support separate reference/source service and storage service.
* [ ] Add some tests for this.
* [ ] Update docs.

## Acceptance Criteria

[//]: # (Acceptance criteria should follow the S.M.A.R.T. principle https://en.wikipedia.org/wiki/SMART_criteria )
Able to use a separate `ArtifactService` and `CASCache` to cache artifacts.

----
[//]: # (To review information about possible relevant labels for this issue please view the list of labels: https://gitlab.com/BuildStream/buildstream/labels)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jun 3, 2019, 10:24

Some contextual discussion [here](https://gitlab.com/BuildGrid/buildgrid/issues/168)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 19, 2019, 11:40

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 19, 2019, 11:54

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Jul 1, 2019, 17:06

marked this issue as related to #1050

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Jul 26, 2019, 10:58

assigned to [[Gitlab user @tlater]](https://gitlab.com/tlater)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Jul 26, 2019, 18:06

changed title from **Support sep{-e-}rate end points for artifact caches** to **Support sep{+a+}rate end points for artifact caches**

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Aug 12, 2019, 13:09

mentioned in merge request !1540

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Sep 6, 2019, 17:03

closed via merge request !1540

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Sep 6, 2019, 17:03

mentioned in commit 20a920f4fd3641b43e714b6c9a9d57a7095c66c5
