### ISSUE TITLE
Use buildbox-casd for CAS access

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1042]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1042)
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jun 6, 2019, 11:07

## Background

BuildStream currently has its own CAS implementation with a local cache, client and server support. There are two major issues with this implementation:
* Local cache expiry doesn't scale, cleanup takes far too much time: #734
* Connections to remote CAS servers are not shared among job subprocesses: #810. This applies to both artifact servers and remote execution.

The BuildBox project is working on a local, caching CAS server called [buildbox-casd](https://gitlab.com/BuildGrid/buildbox/buildbox-casd/). It will implement a gRPC protocol called 'LocalCAS' in addition to the standard 'CAS', providing efficient access to the local cache. Local cache expiry will use a [simple approach](https://gitlab.com/BuildGrid/buildbox/buildbox-casd/issues/6) that is expected to be much faster than BuildStream's current local cache expiry.

## Task description

Using buildbox-casd in BuildStream for CAS access would solve the two major issues. While job subprocesses would still not be able to share the connection to buildbox-casd, establishing multiple local connection on the same host is much less of an issue. All remote connections would be handled by a single buildbox-casd process.

The move to buildbox-casd should also improve performance of CAS operations as it's written in C++, i.e., compiled instead of interpreted Python.

### BuildStream
* casd process/socket management
  * [x] Basic start/stop and channel setup
  * [x] Terminate buildbox-casd when bst raises an error (context manager)
* Use casd for CAS writes
  * [x] Use casd for add_object()
* Use casd to access remote CAS
  * [x] Use GetInstanceNameForRemote to initialize remote
  * [x] Use FetchMissingBlobs for individual and batch downloads
  * [x] Use UploadMissingBlobs for individual and batch uploads
  * [x] Check availability of remote CAS via casd
* Avoid CAS writes in main process (gRPC vs. fork())
  * [x] Use scheduler to fetch subprojects !1414
  * [x] bst source checkout: Do not import sources into CAS in main process !1427
  * [x] Fix non-frontend tests that write to CAS in main process
* CAS expiry
  * [x] Remove old expiry code
  * [x] Quota configuration
  * [x] Local cache / quota status display
* bst-artifact-server
  * [x] Use casd for timestamp updates
  * [x] Forward requests to casd instead of reimplementing them
  * [x] Verify proper operation with casd
* Infrastructure
  * [x] Add buildbox-casd to CI images
  * [x] Update installation instructions to include buildbox-casd
  * [ ] Consider adding static buildbox-casd binary to Python wheel
* Optimizations (some may be required for initial MR)
  * [x] Benchmark
  * [x] Batch CAS writes (add_object() calls) to reduce round trips #1132
  * [ ] Use FetchTree/UploadTree for directory downloads/uploads
* Documentation
  * [ ] Architecture docs to be updated (user facing docs do not need documentation) 
* Future work (not blocking initial MR)
  * [ ] Use casd for staging

### buildbox-casd
* Essential
  * [x] Use 0644 file permissions https://gitlab.com/BuildGrid/buildbox/buildbox-casd/merge_requests/37
  * [x] Implement GetInstanceForRemote()
  * [x] Support dynamic remotes in CaptureFiles() and CaptureTree()
  * [x] Implement FetchMissingBlobs()
  * [x] Implement UploadMissingBlobs()
  * [x] Fix FindMissingBlobs https://gitlab.com/BuildGrid/buildbox/buildbox-casd/issues/21
  * [x] Support dynamic remotes in FindMissingBlobs() https://gitlab.com/BuildGrid/buildbox/buildbox-casd/issues/31
  * [x] Write tests for new methods, ensure proper error handling
* Optimizations
  * [x] Implement FetchTree()
  * [ ] Implement UploadTree()

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jun 18, 2019, 10:40

mentioned in merge request !1382

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jul 3, 2019, 11:03

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jul 3, 2019, 11:05

WIP branch: https://gitlab.com/BuildStream/buildstream/commits/juerg/casd

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jul 3, 2019, 11:24

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jul 3, 2019, 11:42

mentioned in merge request !1446

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jul 5, 2019, 11:15

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jul 9, 2019, 09:47

marked the task **Fix FindMissingBlobs https://gitlab.com/BuildGrid/buildbox/buildbox-casd/issues/21** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jul 10, 2019, 10:18

mentioned in merge request !1465

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jul 12, 2019, 04:54

marked the task **Terminate buildbox-casd when bst raises an error (context manager)** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jul 12, 2019, 04:54

marked the task **Fix non-frontend tests that write to CAS in main process** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jul 22, 2019, 13:56

marked the task **Quota configuration** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jul 24, 2019, 15:08

marked the task **Verify proper operation with casd** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jul 24, 2019, 15:09

mentioned in merge request !1499

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jul 30, 2019, 11:51

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jul 30, 2019, 11:51

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Aug 8, 2019, 09:32

marked the task **Benchmark** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Aug 20, 2019, 08:17

marked the task **Add buildbox-casd to CI images** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Aug 20, 2019, 08:18

marked the task **Update installation instructions to include buildbox-casd** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Aug 29, 2019, 17:26

mentioned in merge request !1540

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Sep 5, 2019, 06:52

marked the task **Local cache / quota status display** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Sep 9, 2019, 17:23

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Sep 11, 2019, 06:52

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Sep 18, 2019, 15:51

marked the task **Support dynamic remotes in FindMissingBlobs() https://gitlab.com/BuildGrid/buildbox/buildbox-casd/issues/31** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Sep 18, 2019, 15:52

marked the task **Write tests for new methods, ensure proper error handling** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Sep 19, 2019, 19:49

marked the task **Check availability of remote CAS via casd** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Oct 8, 2019, 14:03

marked the task **Batch CAS writes (add_object() calls) to reduce round trips #1132** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Nov 4, 2019, 16:15

marked the task **Implement FetchTree()** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Dec 19, 2019, 12:04

marked the task **Forward requests to casd instead of reimplementing them** as completed
