### ISSUE TITLE
Configuration option for disabling blob fetching with RE

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1043]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1043)
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 10, 2019, 15:12

## Background

[//]: # (Provide a background or the root/source that justifies this task or action.)
A follow up to #832 as brought up [here](https://mail.gnome.org/archives/buildstream-list/2019-April/msg00027.html), this would allow users to configure BuildStream to stop fetching blobs in more scenarios where they're using RE, for the actually build targets and the run time dependencies. This can also be extended to sources, as if these are in the remote source cache, we only need the directory trees in order to compose these together.

## Task description

[//]: # (Short summary of the action to be executed)

* [x] Add configuration option to stop BuildStream from fetching blobs  
* [x] Change how artifacts are pulled to not pull actual file blobs if this option is set
* [ ] Change how sources are pulled similarly

## Acceptance Criteria

[//]: # (Acceptance criteria should follow the S.M.A.R.T. principle https://en.wikipedia.org/wiki/SMART_criteria )
Remote execution should continue to work but without file blobs being kept locally where possible.
Some extra tests should be added to check this is working as intended.

----
[//]: # (To review information about possible relevant labels for this issue please view the list of labels: https://gitlab.com/BuildStream/buildstream/labels)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 11, 2019, 16:59

mentioned in commit b9d87c0c68c5963638bd1c604878cf0439007c6b

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 13, 2019, 11:51

mentioned in commit 98957cfc0ed9003392cb0075281d398188925bdd

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 13, 2019, 15:14

mentioned in commit 031334e059a89fca51bccbdbc150f276036547f9

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 13, 2019, 15:14

mentioned in commit 0b42a02d1aac58338d6d487fbdcbbe3cf81901ec

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 13, 2019, 15:55

mentioned in commit accdb4cc2ddba35cdeaf1b064bd5578a21deb85a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 13, 2019, 15:55

mentioned in commit a502fa262c813e87eda085c739411ce913c30478

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 13, 2019, 16:30

mentioned in commit 87ab6eba186f456515a6f819824462c7f13d26d7

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 13, 2019, 16:30

mentioned in commit f9775947291efd528852c14686102c82c15a57f8

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 13, 2019, 18:00

mentioned in commit 914b6b92f4c36b315acb5efcbc370a66ed1f2d59

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 13, 2019, 18:00

mentioned in commit 3b033ce4ccbc0162fabf05f25b33ea1c5a72c2ba

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 14, 2019, 11:35

mentioned in commit d9647f127d58133a26e6daa20a6e4e8e902c3d4a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 14, 2019, 11:35

mentioned in commit 8ffe748e7600a81cee7baef37c6b0ebc34c89864

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 14, 2019, 11:46

mentioned in commit ea5447969183899839577219fa98393d8c8ddd8a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 14, 2019, 11:46

mentioned in commit 3b701de417c10cbf5b22d59aa5fb7c94b61d2fbf

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 14, 2019, 13:50

mentioned in commit b757c419f8c0e6b5ed03eb41b4e1572a1e2da1ec

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 14, 2019, 16:37

mentioned in commit c0409b8224f87b1f080fd311902db2c59ebd5f41

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 14, 2019, 16:37

mentioned in commit fc081c2738cbe28b3634d6bd74591bbe7b9284cb

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 17, 2019, 11:26

mentioned in commit b66e5d5096bd3e440ed86fa415b8f849173439d9

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 17, 2019, 11:26

mentioned in commit 6b901f65d49dc1f208a53e219c564893d543c32c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 17, 2019, 11:54

mentioned in commit 8d6511b7b4edabc5f231ac1be61d70108461044a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 17, 2019, 11:54

mentioned in commit 63ec956f3094533c7da91b98961f89b2a7176e81

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 17, 2019, 12:01

mentioned in commit a68e04526aabebd27679be87f8a4a826f40bea9d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 17, 2019, 12:08

mentioned in merge request !1402

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 17, 2019, 15:23

mentioned in commit bdaf93c491172b2c38cac52adc2df6dff6aa04ba

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 17, 2019, 15:23

mentioned in commit 2afcb8601ad5d98be9faba6439c84ae812868fd3

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 18, 2019, 16:25

mentioned in commit 67785500ca387d99789a850b4a8278ad9f963f8c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 18, 2019, 16:25

mentioned in commit a8c80964dfdbd098bc7138d63664d503a4c5f624

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 18, 2019, 16:25

mentioned in commit 3310c903f4b57a554a06273fc11e9dc4214bb9fc

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 18, 2019, 16:25

mentioned in commit edbb7971c08cfec9d0a0cae5ace86b95712d7d15

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 18, 2019, 16:27

mentioned in commit 7e55d55fba3d1de7da24a8333f9c9e455e7ce1e6

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 18, 2019, 16:27

mentioned in commit 3702c7ab8cac59d7db64fdd8574f4c2f06e29251

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 18, 2019, 16:27

mentioned in commit 24e200d026a3abcc1f8287dc639c06e5310c297a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 18, 2019, 16:27

mentioned in commit 972df5442faaf894740b7c4f38f5033a33a6be2c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 21, 2019, 17:14

mentioned in commit d6e2a37dcc65b6f2e14d3223b7942b071af051f5

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 21, 2019, 17:14

mentioned in commit 13292ea880534c9aa846aa1305dd782b7ad6b519

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 21, 2019, 17:14

mentioned in commit b029d83ee7b8ebcb7f37bae439722f3124c50fe5

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 21, 2019, 17:14

mentioned in commit fe7ae6e9abbb0c9c6b82b0fd571f55f426cbded3

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 24, 2019, 15:20

mentioned in commit 6f1845e77e95e579ee0dd53c3ea78cebab3f6143

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 24, 2019, 15:20

mentioned in commit d2ae876b738e7fe0409f7bc308ab090fdb350b43

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 24, 2019, 15:20

mentioned in commit 9cc3a30bd52c46f127ffae8ff5c7a8accc8d5e75

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 24, 2019, 15:20

mentioned in commit c8b5b7a2c8e334228d91af361c5659ed5e02203a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 28, 2019, 15:30

mentioned in commit 0b327da700f95ee6c1899958c74a0adf25435912

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 28, 2019, 15:30

mentioned in commit 632cbc5dd877cc6662d69ba84a150018af97f1a4

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 28, 2019, 15:30

mentioned in commit 4819b962815c01ccea27f1849f125029507e5504

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 28, 2019, 15:31

mentioned in commit ddcd7b7d1a21d330871c290a3ddf159eae33ec18

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 28, 2019, 15:31

mentioned in commit 8ad2db09f6f41e07ab457705f3dbf9ddc50481b0

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 28, 2019, 15:31

mentioned in commit 52af3bc0ef747d523694249782c66b8129cf62cd

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 28, 2019, 15:31

mentioned in commit bd432f891021a122c6a64b5c18e260f5614f568d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 28, 2019, 15:31

mentioned in commit b5cd52e5ca73c12a8c72226192ba3e55e31bea64

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 16:59

mentioned in commit cffc4a64648093871d9339b953eb779e3b0c0d28

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 16:59

mentioned in commit 6a9ded7209d604fed90f8c69e856d747652158e9

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 16:59

mentioned in commit 73cf0b6bf5ca6b050c967d6075a71de96a2dad1d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 16:59

mentioned in commit 77b65f8035a7f9bba3ff228f79894dcd2d9a2a85

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 17:14

mentioned in commit ae0095d5cc585937d7ef89ae3f7b0037f66c0177

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 17:14

mentioned in commit 9676fb4590b9171babe06f17b333efebd0c045dd

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 17:14

mentioned in commit 40052f1c6f38a63ed67a10dc27508b8aa11fd5ec

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 17:14

mentioned in commit f916b6144db85cb51a86173bad41225271506403

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 17:14

mentioned in commit 86a96ba3537652524b2a164e47b35161bacfe873

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 17:45

mentioned in commit 139e1b3406649a192b98e0b9c667b9ed76b35b34

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 17:45

mentioned in commit edce0a75e44c3e0abe49b5727efaea2366ef679c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 17:45

mentioned in commit 006dc50086146f543ec2e1f241c0583d597b8f4a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 17:45

mentioned in commit 04002f9cfeca00681c5e98f65ad9679bc352729a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 17:45

mentioned in commit 16bb122183635c7c436dc11c693d8f270b956fde

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 2, 2019, 15:04

mentioned in commit 3de067ce4e0e17c3423c25a13d869a23bf851cc6

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 2, 2019, 15:04

mentioned in commit bf849f2787e37073786bf2d8e81dca8b5ee55889

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 2, 2019, 15:04

mentioned in commit 0236d82ebd9447afa9860afdf0efc53aeaa7894e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 2, 2019, 15:04

mentioned in commit 80e7502f839beb55f7f113b4a9ac45470a4913f6

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 2, 2019, 15:04

mentioned in commit 1bffb6f2f37760e5b0df4e0d7327b55d1570552a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 2, 2019, 15:13

mentioned in commit cd371386fa5578d46376317e0d7fa6738445ce76

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 2, 2019, 15:13

mentioned in commit 9b5f3ff7814961a7afe97838fec124606932cfa6

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 2, 2019, 15:13

mentioned in commit 8b4d0091ca7030deb191076cb1c5457a4eaf06f9

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 2, 2019, 15:13

mentioned in commit d14be24328d2b5971f142dac530aca52819f2bc3

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 2, 2019, 15:13

mentioned in commit 70412747e12aa4509d085cd0cb08263eb2f76bfb

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 2, 2019, 16:16

mentioned in commit 09701bd7ed1667881e1cfdc6e832d1c0c597e4bc

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 2, 2019, 16:16

mentioned in commit 9cf1586f401d67973c85d72fcc9e214b8207e7ed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 2, 2019, 16:16

mentioned in commit fa852c370e9f1a9eb1886e0dde14e6aa01c822f0

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 2, 2019, 16:16

mentioned in commit f7c97af4bee85ed79f4fe5f1861779871c4d2e2c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 2, 2019, 16:16

mentioned in commit b3842be37959a66198c0025fd1b322308613dddc

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 2, 2019, 16:18

mentioned in commit 95cac0d4482703f081739ec5763d901b41b050c2

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 2, 2019, 16:18

mentioned in commit 79764466a5d09de0f75b153711f5a1dec549ef51

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 2, 2019, 17:51

mentioned in commit 261f51721eb635ab3832cf9f5c432943d7e66f28

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 2, 2019, 17:51

mentioned in commit 5a2734ea5fa446cc42122d885421050cc8bb6f1b

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 2, 2019, 17:51

mentioned in commit 6fcd4eea7c23277d8fdbf0a24b9c78a3bb9ab39c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 2, 2019, 17:51

mentioned in commit 0d0f4d0fcbfc9ff3c431b4f33b1862c813554b16

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 2, 2019, 17:51

mentioned in commit 5c7d03820e4c9bbdb26bf9fbe12bcb05ae716af7

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 2, 2019, 17:51

mentioned in commit 58982642e982121e2b15802f1b9c5009131a1263

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 5, 2019, 13:11

assigned to [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 5, 2019, 13:11

marked the task **Add configuration option to stop BuildStream from fetching blobs** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 5, 2019, 13:11

marked the task **Change how artifacts are pulled to not pull actual file blobs if this option is set** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 5, 2019, 13:11

marked the task **Change how sources are pulled similarly** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 5, 2019, 13:12

marked the task **Change how sources are pulled similarly** as incomplete

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 5, 2019, 14:00

Realised I forgot to do incomplete sources for !1402, but looking at it because some of the stuff isn't in place I think this will be worth doing in a separate issue which I've raised as #1066.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 11, 2019, 16:54

mentioned in commit 2a26d8a7020644fe95929aa5fc142ca2977cee03

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 11, 2019, 16:54

mentioned in commit b7ab32fe907ebc1cab6b0ef9809a2c90df92f7cb

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 11, 2019, 16:54

mentioned in commit 575fb5af0828e491f68f659cf0f053e22fe47035

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 11, 2019, 16:54

mentioned in commit d05710f79e129660a5383f5a8854960eac9a2d28

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 11, 2019, 16:54

mentioned in commit d9ee249e69634378037dcfa3c5657eb10e83d213

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 11, 2019, 17:28

mentioned in commit 4393c262adb0f44e61337f666ae8ba6a998df4cb

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 11, 2019, 17:28

mentioned in commit af9530c66c7392abde791dea1ad52cc657d31004

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Jul 11, 2019, 18:04

closed via merge request !1402

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Jul 11, 2019, 18:04

mentioned in commit 24426ebe31fc2ad297b352a1d332c7cf158ef5c2
