### ISSUE TITLE
Fetch missing blobs on demand

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1044]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1044)
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 10, 2019, 15:48

## Background

[//]: # (Provide a background or the root/source that justifies this task or action.)
Another follow up to #832 (closed) as brought up [here](https://mail.gnome.org/archives/buildstream-list/2019-April/msg00027.html), in cases where we haven't fetched the file blobs for objects, we want to ensure they are fetched or present the user with the option to fetch them when running commands like shell and checkout. I think it makes sense to have a `--pull` option to artifact checkout and shell, as the source checkout command does with `--fetch`, and ensure that this also fetches file blobs  when only directory trees are local. If this isn't specified and file blobs aren't present an appropriate warning should be given to the user.

Similar to #1043 this should also work for source checkout and directory trees there.

## Task description

[//]: # (Short summary of the action to be executed)

* [ ] Add fetch option to `bst artifact checkout` command
* [ ] Change `Element._pull` to fetch file blobs for a directory tree.
* [ ] Change `Element._fetch` and `Source._fetch` similarly.

## Acceptance Criteria

[//]: # (Acceptance criteria should follow the S.M.A.R.T. principle https://en.wikipedia.org/wiki/SMART_criteria )
Additional tests for fetching file blobs for a artifact checkout and shell commands.

----
[//]: # (To review information about possible relevant labels for this issue please view the list of labels: https://gitlab.com/BuildStream/buildstream/labels)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 11, 2019, 10:46

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 11, 2019, 16:59

mentioned in commit baa65d89c6bd4ec579495337f52795d148e1b046

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 11, 2019, 17:17

mentioned in commit 177977615d60cac711f7ecf5829b95d9ef861da4

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 11, 2019, 17:17

mentioned in commit eb1b1ef26e071699f5072b51a4e49275e89559e4

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 11, 2019, 17:37

mentioned in commit f69217fcbf36c211d480849147c35d9db2eca945

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 11, 2019, 17:37

mentioned in commit d427de12c368360f378f0f4fdbed7ecdfd4c048a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 11, 2019, 17:41

mentioned in commit 714a465dec1c79ec2da1d3a015e5ee21abd9e9f5

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 11, 2019, 17:41

mentioned in commit a76a0dbe143958bd7de776b8abf62569899b5fee

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 11, 2019, 17:55

mentioned in commit 1dc98f0f8a08ebcf39cea9558a3d3d09b1898054

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 11, 2019, 17:55

mentioned in commit 1ed715c7a50aafbfd10bcda04eaa2766ef70f4af

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 12, 2019, 16:48

mentioned in commit 022b141a181045ed2dd178afd6e0220d75e4b893

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 12, 2019, 16:48

mentioned in commit 8ad0ce533a13133544658396156f973d25629c08

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 12, 2019, 16:54

mentioned in commit 07ae3ea688be2f59531873cc46711c6654f10109

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 12, 2019, 16:54

mentioned in commit 82a8818f06a46f116cc95f8cace73050a8f30903

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 12, 2019, 18:16

mentioned in commit 049691b449b24685fb7d9c6c5f106b1ec3616f3b

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 12, 2019, 18:40

mentioned in commit 9b5923024527a755aa3d90d9be55218ecaf34cc0

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 12, 2019, 18:53

mentioned in commit 67f0c60c2bd6c67bb60c2610f5d282862addd91a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 13, 2019, 11:51

mentioned in commit e3a3949d43eee693b9b613c609b7cc0a9b0fa83a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 13, 2019, 11:51

mentioned in commit 9844f19e1a20ce1ad7b5bf1c430b954bcaadee76

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 13, 2019, 18:00

mentioned in commit 5e827c770cc389b0839d77581384e5697e40d13b

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 13, 2019, 18:00

mentioned in commit 9399b6cf401ff0618b3e38c51e1fa1f8a8d66336

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 14, 2019, 11:46

mentioned in commit bb78b2e5aef83165c0ce903cdee39c4a359cfe68

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 14, 2019, 11:46

mentioned in commit 3e8051aadfeeab8f93314b672611b40d6a7182c4

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Jun 14, 2019, 12:21

mentioned in merge request !1400

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 14, 2019, 16:37

mentioned in commit 942e0474406710d2f080ff8232da7cffa774d03e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 14, 2019, 16:37

mentioned in commit 2121bd933e79cd96fd56bb9c9634d7a02b2d7d27

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 17, 2019, 15:23

mentioned in commit 3dc6c9cdf3e18bc08df25faee00244478a784604

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 17, 2019, 15:23

mentioned in commit 6afae89ae25ffe900463436bccd47d98a5e56d57

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 17, 2019, 15:23

mentioned in commit 6d6576a6fdca711e4fa1657cc2d7958108042b40

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 17, 2019, 15:24

mentioned in commit 1379de1e7894ffd17053139e7b044254d0192fdb

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 17, 2019, 15:24

mentioned in commit a1f8a4df903b67a44d3821e4b8fd4b44f35a94a2

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 17, 2019, 15:24

mentioned in commit 9e3a9620a7a054e27e50e64da14cb5980f6bda06

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 20, 2019, 10:29

mentioned in commit 23002b4ee7ddbf96d0a7d0836c4e7602accd9c37

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 20, 2019, 10:29

mentioned in commit 4643db0e6f9be511e190e6526314b4b0cca2e8d3

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 20, 2019, 10:29

mentioned in commit 76d60ed2155a5caa95b7c2a886788f14004a0e80

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 20, 2019, 10:29

mentioned in commit 82cc9cdcb2e08ecd0382d950354f6ddba9fcf88c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 20, 2019, 10:29

mentioned in commit 4e8c2a20457e47e05fa2f95c6214baf0b2bbe86d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 20, 2019, 15:53

mentioned in commit 66384ac678d1cab21a04e95d5d4f3497334312a0

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 20, 2019, 15:53

mentioned in commit ea2a4af53addc85efd2758d1390f75325df177e6

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 20, 2019, 15:53

mentioned in commit 1e8a724d46b76d45d0e66fbd27c6f4be04c04027

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 20, 2019, 15:53

mentioned in commit 75cf18df6f3bb4420e40b4b4e9095365c9369e3e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 20, 2019, 15:53

mentioned in commit 1bff6416a5c8ad87ef24537f155927aaf4e95e47

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 20, 2019, 16:02

mentioned in commit 4bfba1d0ed0650de8cfc5baf2af5004c07d23c1f

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 20, 2019, 16:02

mentioned in commit 001b32ce217489273474b8d07071ca058d59e51e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 20, 2019, 16:02

mentioned in commit b4efce62c97a7592c5638612a098ee82b8a9869c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 20, 2019, 16:02

mentioned in commit 2340202d9400bde0d106526b6b2fb896fdf29a38

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 20, 2019, 16:02

mentioned in commit 7874738ddeb8eca7031b205352fb3216b6eb45c6

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 21, 2019, 10:54

mentioned in commit b5fb9542169df6fd5be379657f2b3fd1445a0fa8

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 21, 2019, 10:54

mentioned in commit 9521c5b0a6c315f48d0516454654ef614f28a467

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 21, 2019, 11:07

mentioned in commit 50df2ec9cfd8f2733de20d755578b7006c1a2c03

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 21, 2019, 11:07

mentioned in commit ed25bf83def694446ec4b34faae2d08082d2e9ba

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 21, 2019, 11:07

mentioned in commit 1f14d69eaa8f36fa886dee2bbabb53d588fd80c3

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 21, 2019, 11:09

mentioned in commit 94f5e4a6407c84c4117940312ca45a655d5d6446

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 21, 2019, 11:09

mentioned in commit 393dc45df56a330372145dfc6b4e5fc97761545c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 21, 2019, 11:09

mentioned in commit eb791ceb66fdc3160e9b0ed72c807e19b760b908

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 21, 2019, 11:09

mentioned in commit 4f6113d26bcff1775c88bbfa0c1e3683a6efdda6

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 21, 2019, 11:09

mentioned in commit 1264347efc120730b5efd0a6126d99805880941d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 24, 2019, 10:04

mentioned in commit c01ce490bf62535b31b53d532bdf7eb87c0217f7

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 24, 2019, 10:04

mentioned in commit 5d376ebcc1efb8d0839cd5f9bb352f29d087d391

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 24, 2019, 10:08

mentioned in commit fd2b630d1165d7033761875324b43645fbee45c6

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 24, 2019, 10:08

mentioned in commit c1571cfcfbac83397a1a997549396c75c4c8f9f5

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 24, 2019, 10:08

mentioned in commit c86258e055795c2100cc180bf9dd65819eb2cd96

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 24, 2019, 11:28

mentioned in commit 026e2f1ca70aa49fbad36cf9c85d45ff148deb47

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 24, 2019, 11:28

mentioned in commit 5bef6443225e1cc799beacfdacfe6a5ee0fd3b09

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 24, 2019, 11:28

mentioned in commit c69a6ee7a464bc651567e67217c8c093cc956f88

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 24, 2019, 11:28

mentioned in commit 7372381f42d6982b584e9d1176f1269728aebf1b

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 24, 2019, 11:28

mentioned in commit 521f1b5c227ee8daf5e82201c7a19a22809723a2

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 24, 2019, 11:43

mentioned in commit 86330faf4f0ababde265f1ac3e86733d1908ed44

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 24, 2019, 11:43

mentioned in commit 3255fe9d6b5facc0096e2585a157719898272e75

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jun 24, 2019, 11:43

mentioned in commit 2ab50f239d09cbe41f9a13bc581d8b69e974c0bd

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Jun 24, 2019, 12:29

closed via merge request !1400

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Jun 24, 2019, 12:29

mentioned in commit 5c8642b4c86fed13b0b29aaa01e21871d3a89a31
