### ISSUE TITLE
Remove the concept of update_state

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1054]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1054)
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jun 25, 2019, 11:30

## Background

From profiling, we have seen that `Element._update_state()` is a known bottleneck in our codebase. It is a complex area of the code which is (somewhat confusingly) handling state changes and is called very often.

We should aim to reduce our calls to `Element._update_state()` or, preferably, remove the whole concept.

## Task description
Now that !1344 has landed, we have introduced push-based element state handling within BuildStream, but we are still heavily relying on calls to `Element._update_state()` to monitor/control state change. For push-based state handling, we should be able to know when an element and its reverse dependencies have *probably* changed state.

I have opened this ticket to help track our removal of the concept of `Element._update_state()`.

Rough outline of the tasks are below (note that this might be prone to change):

* [x] Push-based queues: !1344
* [x] Notify reverse dependencies when an Element becomes cached: !1406
* [x] Remove ready for runtime checks from `Element._update_state()`
* [x] Remove `Element._update_state_recursively()`
* [x] Remove high level `Element._update_state()`
* [x] Refactor workspace handling so that they don't require special cased state monitoring (!1612)

Related to #902

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jul 3, 2019, 16:55

mentioned in merge request !1449

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jul 17, 2019, 05:38

marked the task **Remove `Element._update_state_recursively()`** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jul 17, 2019, 06:52

marked the task **Remove ready for runtime checks from `Element._update_state()`** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jul 17, 2019, 06:53

marked the task **Remove ready for runtime checks from `Element._update_state()`** as incomplete

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jul 17, 2019, 06:53

marked the task **Remove ready for runtime checks from `Element._update_state()`** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Aug 12, 2019, 11:35

assigned to [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Oct 16, 2019, 16:25

marked the task **Refactor workspace handling so that they don't require special cased state monitoring** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Oct 16, 2019, 16:29

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Oct 17, 2019, 12:01

assigned to [[Gitlab user @tlater]](https://gitlab.com/tlater)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Oct 17, 2019, 12:02

unassigned [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Oct 22, 2019, 10:41

mentioned in merge request !1660

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Nov 18, 2019, 17:27

closed via merge request !1660

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Nov 18, 2019, 17:27

mentioned in commit 26670d5dd6d08e0af187f9eeb33413495fbe9fa0

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @danielsilverstone-ct]](https://gitlab.com/danielsilverstone-ct) on Nov 19, 2019, 10:15

marked the task **Remove high level `Element._update_state()`** as completed
