### ISSUE TITLE
Supply options to turn off networking features

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1065]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1065)
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Jul 5, 2019, 11:49

## Background:

[//]: # (Provide a background or the root/source that justifies this task or action.)

BuildStream is perfectly capable of building offline, but to get it to
do so for whatever reason involves turning off my wifi.

This isn't always desirable - I can see someone working on a metered
connection, and being perfectly happy browsing the web, but not
wanting to download a 20GB artifact from a server (and instead
preferring to build that offline from sources they already have).

It would also be nice if we could disable specifically downloading
from artifact caches, so that we can try rebuilding an artifact (just
to see if we can still build from scratch, even if BuildStream should
technically guarantee that), and disabling fetching so that I don't
need to wait 20 minutes to realize that my proxy doesn't work and that
I therefore only have access to an artifact server.

We technically *do* have a way to do some of this, by setting
`fetchers: 0`, however I believe that the fact that we allow '0' as a
value to that is counter-intuitive, and even if this is how it works
internally, we should supply a different UI for that. This also gives
us an opportunity to fail faster and give better error messages.

## Task description

[//]: # (Short summary of the action to be executed)

We should add options to accommodate those use cases. In particular,
we should add:

* [ ] `bst --offline/--online`, that switches running *any* network requests.
* [ ] `bst --no-/artifact-server`, that turns on/off pushing/pulling.
* [ ] `bst --no-/remote-sources`, that turns on/off interacting with remote sources (Anything that inherits from downloadable? Might be realted to !1423).

This should obviously be implemented as a set of user configuration settings as well :)

Some discussion came up about allowing something like `bst --offline
fetch foobar.bst`, since the user clearly wants to fetch. Other tools
(e.g. [yarn](https://yarnpkg.com/blog/2016/11/24/offline-mirror/) or
[cargo](https://www.ncameron.org/blog/cargo-offline/)) do not permit
this, and from a scripting perspective it would allow checking whether
all sources have already been fetched, hence I would suggest not
creating a special case here.

We should also remove the option to set fetchers/builders to 0, since
this is counter-intuitive, and no longer necessary once these other
flags exist.

## Acceptance Criteria

[//]: # (Acceptance criteria should follow the S.M.A.R.T. principle https://en.wikipedia.org/wiki/SMART_criteria )

BuildStream has a more understandable and slightly more granular
method of disabling network interaction.

----
[//]: # (To review information about possible relevant labels for this issue please view the list of labels: https://gitlab.com/BuildStream/buildstream/labels)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Jul 5, 2019, 11:50

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Jul 5, 2019, 15:02

An alternative to `--no/-remote-sources` would involve setting up per-alias rules, such that we can avoid pulling from servers that are "far away". This might make more sense, especially in the case of proxy connections where some aliases may be available and some not.

We should also consider what this means for remote execution, although I'm not sure how remote execution is currently triggered.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jul 5, 2019, 16:19

> It would also be nice if we could disable specifically downloading from artifact caches, so that we can try rebuilding an artifact

For artifact servers (and source servers) I'd like more flexibility than a boolean flag. We currently have the issue that user config can't override artifact servers specified in project.conf (user config can add servers but not remove/modify project.conf servers), which can be very inconvenient, especially with junctions. I.e., I'd be in favor of something similar to what was proposed in !950 (`none`, `user` and `all`).

This may require further discussion but it shouldn't block the addition of an `--offline` option, if there is consensus on that.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 5, 2019, 23:51

I have a situation where I definitely want to pull/fetch but do not want to push (a case where I build a big image, and I want it to be downloadable but I don't want to put it in the artifact share). I'd also (or alternatively even) like to be able to disable artifact servers declared by project.conf from my user config.

Not sure I agree that `--fetchers 0` and `--pushers 0` for this purpose are counter intuitive, having `--no-pushers`/`--no-fetchers` aliases might help there, and of course wouldn't block an `--offline` mode to override both to 0.

That said, I would support any plan which either lets me control pull/push separately, or allows me to override project defined artifact servers from user configuration (which essentially allows me to do the same as `--no-pushers`).

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Sep 17, 2020, 16:06

marked this issue as related to #1240

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Sep 24, 2020, 07:19

marked #1240 as a duplicate of this issue

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Sep 24, 2020, 07:19

marked #1396 as a duplicate of this issue

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Sep 24, 2020, 07:19

marked this issue as related to #1396

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @nanonyme]](https://gitlab.com/nanonyme) on Oct 7, 2020, 18:40

I would even go as far that the overrides should be doable on the level of individual elements. Like if you have files that are turned into a compressed image, then you can specify that the element is built and locally cached but not pushed. This avoids more efficient usage of remote cache when you really are not going to ever re-use the compressed image anywhere else.
