### ISSUE TITLE
Incomplete sources with remote execution

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1066]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1066)
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 5, 2019, 14:00

## Background

[//]: # (Provide a background or the root/source that justifies this task or action.)
Follow up to #1043, sources also don't need to be complete in remote execution but this requires more work to get functional.

## Task description

[//]: # (Short summary of the action to be executed)

* [ ] Add argument to source cache pull that only fetches the directory tree
* [ ] Figure out which scenarios we only want the directory tree and use this when pulling sources from a source cache
* [ ] Ensure that commands such as source checkout fail cleanly and maybe have a `--pull` option or similar
* [ ] Add tests for this.

## Acceptance Criteria

[//]: # (Acceptance criteria should follow the S.M.A.R.T. principle https://en.wikipedia.org/wiki/SMART_criteria )
With sources in a remote source cache, we should be able to build elements without having to pull source files locally.

----
[//]: # (To review information about possible relevant labels for this issue please view the list of labels: https://gitlab.com/BuildStream/buildstream/labels)
