### ISSUE TITLE
Committers list should align with Gitlab users and permissions and be fully automated

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1071]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1071)
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jul 9, 2019, 12:35

## Background

I recently submitted [a patch to add a list of committers](https://gitlab.com/BuildStream/buildstream/merge_requests/1415) which just adds a text file of those who have full commit access, and outlines the policy to follow (copying subversion). 

It would be much better if this was aligned with the gitlab usres and automated. 

## Task description

* [X] Ensure all gitlab users and permissions are accurate - everyone should be a developer, with a small number of people as owners (those that already are owners)
* [ ] Those with commit access are currently 1) named individuals against the master branch (protected branch) and 2) anyone with 'Owner' or 'Maintainer' permissions - these people should be listed in the COMMITTERS file automatically - OR we could have the COMMITTERS file be the source of all truth and update the gitlab permissions
* [ ] Have a look at [Gitlab codeowners](https://docs.gitlab.com/ee/user/project/code_owners.html) to see if it's helpful
* [ ] Or a script, maybe on a cron job, might be good enough for now
* [ ] Tidy up and/or replace the original MR - https://gitlab.com/BuildStream/buildstream/merge_requests/1415

## Acceptance Criteria

* Committer policy should be clear and captured in CONTRIBUTING
* Committer list should be automated based on Gitlab permissions

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jul 9, 2019, 12:35

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jul 10, 2019, 11:04

mentioned in merge request !1461

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jul 11, 2019, 10:14

mentioned in merge request !1415

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 11, 2019, 17:53

assigned to [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 11, 2019, 18:01

[[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi)  is the last task still relevant?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jul 11, 2019, 18:10

marked the task **Ensure all gitlab users and permissions are accurate - everyone should be a developer, with a small number of people as owners (those that already are owners)** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jul 11, 2019, 18:11

[[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) yes, although will potentially need amending

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 22, 2019, 17:03

unassigned [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @AlexFazakas]](https://gitlab.com/AlexFazakas) on Jul 24, 2019, 14:23

assigned to [[Gitlab user @AlexFazakas]](https://gitlab.com/AlexFazakas)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @AlexFazakas]](https://gitlab.com/AlexFazakas) on Jul 24, 2019, 17:12

After a talk with [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) we decided that for now we'd try to automatically create a `COMMITTERS.rst` file by fetching all the relevant names and usernames through the Gitlab API. I believe I managed to do that, but before moving forward I wanted to ask a couple of questions to see how we should proceed:

1. How should `COMMITTERS.rst` be created? As it will contain some introductory lines (similar to [[Gitlab user @tlater]](https://gitlab.com/tlater) / [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) 's work  [here](https://gitlab.com/BuildStream/buildstream/blob/9ad0eb1e6d3eca9bcaa6bbf630e7cfbdda12cb3c/COMMITTERS.rst)), I was thinking always printing some lines (not nice, but I'm not sure what's a better looking workaround here).

2. I'm not sure how to set up the script to update the file periodically. What I had in mind was running it together with the overnight tests, but it also needs to commit the changes, should there be any, and I'm not sure how to do that. It might be a bit of an overkill using it once a day however. As it is right now, it takes about ~10 seconds to run on my machine, so it would add a small overhead to the overnight CI.

3. To be able to access the information, I'm currently using an access token, so we'd always need one ready for the script to run, that is also something to consider.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 25, 2019, 11:29

1. you can do that but you could also read a template file and write out that header with the appended table which would avoid hardcoding it

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @AlexFazakas]](https://gitlab.com/AlexFazakas) on Jul 25, 2019, 11:39

Not sure I understand, so we could maybe have a file like `.COMMITTERS_template.rst` in the repository, which the script would copy in `COMMITTERS.rst` and then append the table, for instance?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 25, 2019, 11:53

yes, that's one way, you could make it some other format if you wanted easier support for complex formatting

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @AlexFazakas]](https://gitlab.com/AlexFazakas) on Jul 25, 2019, 11:54

Makes sense. Thanks for the suggestion! :)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 25, 2019, 11:58

2. you can run that script on a new schedule (cron trigger) and job. i'm not sure if marge has permissions to commit any changes that come out of that but that could work

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @AlexFazakas]](https://gitlab.com/AlexFazakas) on Jul 25, 2019, 14:49

I'm not sure if we can commit changes to the repositories through a job. Some people suggested I use a hook, and after playing a bit with it I think it's doable, but then we add a roughly 10 second overhead whenever we commit something, which is too much. Not sure you meant about marge, however.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 25, 2019, 15:33

i think the hook shouldn't be on each push

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @AlexFazakas]](https://gitlab.com/AlexFazakas) on Jul 25, 2019, 15:39

I was thinking we could have a hook for every merge, but apparently these don't work with fast-forward merging, so I'm not sure if there's another option with hooks.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @AlexFazakas]](https://gitlab.com/AlexFazakas) on Jul 26, 2019, 16:37

mentioned in commit b49b551562519b28930c9f44cfcc6b3cd42026fe

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @AlexFazakas]](https://gitlab.com/AlexFazakas) on Jul 26, 2019, 16:38

mentioned in merge request !1505

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @AlexFazakas]](https://gitlab.com/AlexFazakas) on Jul 26, 2019, 16:47

mentioned in commit 5b513019024ec8b0918752da50b20069c4fd37f8

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @AlexFazakas]](https://gitlab.com/AlexFazakas) on Jul 29, 2019, 17:07

mentioned in commit fb1df62220830b28ca345b1f261c122137091888

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @AlexFazakas]](https://gitlab.com/AlexFazakas) on Jul 31, 2019, 11:22

mentioned in commit f3a936f5909c95249ad9556ee9795c1c176cc3ce

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @danielsilverstone-ct]](https://gitlab.com/danielsilverstone-ct) on Jul 31, 2019, 11:30

mentioned in commit 82c73a486de6dbda969ce837f56120c21406b503

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @AlexFazakas]](https://gitlab.com/AlexFazakas) on Jul 31, 2019, 16:33

mentioned in commit 446cbf3a2afc097748dd37abb6d18c3ca4d78f96

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Jul 31, 2019, 17:50

mentioned in commit 1388d72ac76c2de326d064290b383314db1454e8

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Jul 31, 2019, 18:13

closed via merge request !1505

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Jul 31, 2019, 18:13

mentioned in commit 3d224253b3448517f5bd36e68e9ff6ac205a0ca9

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Aug 6, 2019, 13:36

mentioned in commit 2c0ea1efd9c5a4f831d9326eac7c911627926908

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Aug 7, 2019, 12:08

mentioned in commit 9049ee90a9b1d94c252919649281d0d80a84a495
