### ISSUE TITLE
Cache Key Dictionary Changes

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1073]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1073)
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 10, 2019, 11:17

## Background

https://mail.gnome.org/archives/buildstream-list/2019-July/msg00004.html

# Formalize a public specification for the cache key dictionary

The `element.py` [cache key dictionary](https://gitlab.com/BuildStream/buildstream/blob/master/src/buildstream/element.py#L2203-2222) should have a formal public specification to ensure maximal key value/performance. 

## Tasks
* [x] Make field changes summarised at [list](https://mail.gnome.org/archives/buildstream-list/2019-July/msg00004.html)
    - [x] remove `context`
    - [x] remove `project`
    - [x] remove `cache`
    - [x] rename `artifact-version` to `core-artifact-version`
    - [x] rename `execution-environment` to `sandbox`
* [x] Replace `element` with `element-plugin-key`, `element-plugin-name`, and `element-plugin-version`.
* [ ] Split dependencies into `dependency-keys-strong` and `dependency-keys-weak`
* [x] Replace sources with a list of dictionaries of name, version, and key. This may be overwritten by the values of `workspaces` which is removed.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 10, 2019, 11:18

changed title from **{-cache key dictionary c-}hanges** to **{+Cache Key Dictionary C+}hanges**

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 10, 2019, 11:25

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 10, 2019, 11:27

mentioned in merge request !1466

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 10, 2019, 15:15

mentioned in commit 8fcc936ca28388591e7cfb43c8dbfab94ab1d400

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 10, 2019, 17:00

mentioned in commit 5d119d39a63a582333548e8b3fa07f0aa9535825

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 10, 2019, 17:11

mentioned in commit d7a43295ad09a332c3e5d356c64becc8f945b451

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 10, 2019, 18:48

mentioned in commit ad8f36b1becf1ae9106613d6bb451dd3e13844a7

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 11, 2019, 11:18

mentioned in commit ab6d784592507621c4b675f774dbde8017baeac8

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 11, 2019, 12:32

mentioned in commit 09f6b69dccb41b5828b65b934ae59b49bbef3377

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 11, 2019, 17:12

mentioned in commit 6f0d19208825cbdb7ad777d1b57e8d22e7b8f604

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 11, 2019, 17:49

mentioned in commit 26dca1cca31a32d5b71d1e7990c7b917199b0c1d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 11, 2019, 17:51

mentioned in merge request !1470

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 12, 2019, 09:39

mentioned in commit dd7241400618172d12136111a1707b24ed51a19c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 12, 2019, 09:48

mentioned in commit adb4882844c4f29c2ceac5751ff2ccb3933282d3

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 12, 2019, 16:07

mentioned in commit 040579bc3794ca7a4bf907e45cacf76066e4a90d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 12, 2019, 16:57

mentioned in commit 53e4fc57f9f9a97bb36f309a17dd0e149f897391

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 12, 2019, 18:07

marked the task **rename `execution-environment` to `sandbox`** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 12, 2019, 18:07

marked the task **Replace `element` with `element-plugin-key`, `element-plugin-name`, and `element-plugin-version`.** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 12, 2019, 18:07

marked the task **Make field changes summarised at [list](https://mail.gnome.org/archives/buildstream-list/2019-July/msg00004.html)** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 12, 2019, 18:07

marked the task **remove `context`** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 12, 2019, 18:07

marked the task **remove `project`** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 12, 2019, 18:07

marked the task **remove `cache`** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 12, 2019, 18:07

marked the task **rename `artifact-version` to `core-artifact-version`** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 18, 2019, 11:46

marked the task **Replace sources with a list of dictionaries of name, version, and key. This may be overwritten by the values of `workspaces` which is removed.** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 18, 2019, 11:46

marked the task **Replace sources with a list of dictionaries of name, version, and key. This may be overwritten by the values of `workspaces` which is removed.** as incomplete

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Aug 28, 2019, 17:19

!1548 has also introduced changes to the cache key

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 5, 2019, 13:06

mentioned in merge request !1563

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 5, 2019, 17:51

mentioned in commit f3d73ec2509d728ce58e5b3e6c2c8b8ef5ca5882

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 5, 2019, 17:53

mentioned in commit 48242f23214d68906cbd7164e71308882592aeeb

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 6, 2019, 18:03

mentioned in commit d613092f32a7104255f1db0de75af9c9bdf1ab74

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 9, 2019, 15:39

mentioned in commit c6bfaa0fa5cf1af890f3e10e3beeb43916f08440

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 9, 2019, 18:26

mentioned in commit d828864960ebbcb207e88353ff5affd1948fa0c7

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 10, 2019, 12:52

mentioned in commit 509edf831ffee52b1c84306e5062363ca5077f0e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 10, 2019, 16:52

mentioned in commit 0abec54e598629debab2c31d514060cdceb110c3

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 10, 2019, 17:22

mentioned in commit 49c9b591e7a13880190ccebbb054af9af4e02f4d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 11, 2019, 13:48

mentioned in commit 125ad8dc057ab208fc22332795fa1ca2dbc1a8bd

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 12, 2019, 10:44

mentioned in commit 9b5ddc40b732d83bff5ae1a8fd3e992f37e9b8a8

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 12, 2019, 15:35

mentioned in commit 5493d1abf6e508c1e93f3beddb947baeda9b4fd3

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 12, 2019, 15:36

mentioned in commit fe52e885b1a2be489a2a2785b67ef6a986d0642f

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 12, 2019, 18:50

mentioned in commit d33b77995ceb3bdd2d8937f17f0b6dd902e0a3b1

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 16, 2019, 11:09

mentioned in commit fab99438095fc389dbe10836e85b800276bd77c4

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 16, 2019, 15:14

mentioned in commit 0bfaf1cb1063072484fbd79e38a0b06d745507e3

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 16, 2019, 15:55

mentioned in commit 0af7feacf69d2163ffb396086124d5564b3ce63d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 16, 2019, 17:19

mentioned in commit 7ced4642aad5ed1f2e48bbef4d2c044e55cf7cd9

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 17, 2019, 10:20

mentioned in commit 29a9293b81ffe01d52eefdcaa6ee7696de76b553

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 17, 2019, 13:05

mentioned in commit f82c8d17074500f30dc71c4d9913e0b3504ad6bb

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 17, 2019, 16:23

mentioned in commit 2170497449e9fabdb6d903ecd3d5e7203ee2db16

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 17, 2019, 18:18

mentioned in commit f26ead2316df67e442abc8f8428132b812cce96a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 18, 2019, 10:56

mentioned in commit 022cef3cd8ee10b7eed09b240af76a0ad1280141

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 18, 2019, 12:14

mentioned in commit 51f10f54842a84da47eceff49c1fc1cb20d6e33f

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 18, 2019, 12:35

mentioned in commit 379aac07efc91c6e8ba5a999ed57055566ada0de

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 18, 2019, 13:58

mentioned in commit 08ae2208c5e7c061d13f16b1e40c7506060f86f7

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 18, 2019, 14:48

mentioned in commit 9bfc918a3c2ec342d0df08ce6eb7a1aa4716cbba

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 18, 2019, 14:51

mentioned in commit a141da6c9df7944cbbdeaa846d4cb096d4344499

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 18, 2019, 16:38

mentioned in commit e04ce36337a2c348fbb70af723c27afc425f8257

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 19, 2019, 12:39

mentioned in commit af4bbc96e37c7b2d12028138c398c0380803e3ca

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 19, 2019, 13:08

mentioned in commit 3c025ad64c0cb27a6ae399b4634f7c2681c79016

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 19, 2019, 14:55

mentioned in commit 4b6f7968f889645b107eb32251c6c73540897b79

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 19, 2019, 15:24

mentioned in commit ec48b1bb729e46425e3c9965bd0807ed964178ca

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 19, 2019, 17:12

mentioned in commit 54f3800457ca88236d72011d2556149980108ac4

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 19, 2019, 17:45

mentioned in commit 55d8b9398bb290f8daa6eaced305c25b09bb8176

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 20, 2019, 11:10

mentioned in commit 053ea05806a46dd02f21cdd92834542ef60cea64

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 20, 2019, 11:20

mentioned in commit bb28e096c27fc772e81b7dee5b703b2d3464e7e7

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 20, 2019, 11:26

mentioned in commit a151e8a101d8f87ff8a42c73ad3863b91c007f49

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 20, 2019, 19:07

mentioned in commit 06ff4bf0dc91474f6439b584d438cde527932e3e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 20, 2019, 19:38

mentioned in commit 97d40dc88702101035992e0f05bb08a65312c255

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 23, 2019, 17:48

mentioned in commit 91f07fa9a150831bc4e555d7b550a018f1e7901e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 24, 2019, 16:58

mentioned in commit b9e2af22bc94d108a27fc9a40f698b4822c7118e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 27, 2019, 17:52

mentioned in commit a34ced97f36022953d8eb5d7f52f7af04ad9f892

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 30, 2019, 15:25

mentioned in commit f2d458d0267383c0c85022aa20defe770e6ebfca

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Oct 30, 2019, 16:27

> Replace sources with a list of dictionaries of name, version, and key. This may be overwritten by the values of `workspaces` which is removed.

this task is NA now that workspaces use a plugin

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Oct 30, 2019, 16:27

marked the task **Replace sources with a list of dictionaries of name, version, and key. This may be overwritten by the values of `workspaces` which is removed.** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Oct 30, 2019, 17:59

mentioned in merge request !1679

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Nov 4, 2019, 11:19

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Nov 5, 2019, 12:56

> [ ] Split dependencies into `dependency-keys-strong` and `dependency-keys-weak`

NA now that names are always encoded for deps

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Nov 5, 2019, 12:56

closed
