### ISSUE TITLE
Add progress reporting across jobs in subprocesses

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1092]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1092)
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Jul 26, 2019, 14:22

## Background

As discussed in https://mail.gnome.org/archives/buildstream-list/2019-July/msg00020.html (an E-mail in response to #1029), it would be beneficial to be able to report the progress through a task, so that users know whether a task is hanging or making progress.

To facilitate this, !1482 adds in numerical progress reporting for the main process. 

## Task description

* [ ] Pass the Task object created by the scheduler into the Element that is running 
* [ ] Fix any IPC that is preventing notifications in the plugin reaching the frontend
* [ ] Add methods in Element to use the Task to report progress
* [ ] Implement progress reporting for whichever plugins seem appropriate

## Acceptance Criteria

It is possible to use function calls in the element plugins' implementations to report progress information that appears in the status display.

----
[//]: # (To review information about possible relevant labels for this issue please view the list of labels: https://gitlab.com/BuildStream/buildstream/labels)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jul 30, 2019, 16:03

mentioned in merge request !1358

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Sep 10, 2019, 11:31

assigned to [[Gitlab user @tlater]](https://gitlab.com/tlater)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Dec 2, 2019, 11:05

unassigned [[Gitlab user @tlater]](https://gitlab.com/tlater)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Dec 10, 2019, 13:17

If this is worked on, it should be ensured that the jobs are still picklable
