### ISSUE TITLE
Add progress reporting as a generic string

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1093]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1093)
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Jul 26, 2019, 14:26

## Background

As discussed in https://mail.gnome.org/archives/buildstream-list/2019-July/msg00020.html (an E-mail in response to #1029), it would be beneficial to be able to report the progress through a task, so that users know whether a task is hanging or making progress.

To facilitate this, !1482 adds in numerical progress reporting for the main process.

Some plugins will not be able to have meaningful numbers for reporting progress, but users would still like some way of knowing that the job is not stuck.

To facilitate this, the plugin could periodically report a string that came from the task's output, e.g. the last line of the output when running a BuildElement's commands.

## Task description

[//]: # (Short summary of the action to be executed)

* [ ] Write the appropriate rendering and length-calculating code in the Status renderer.
* [ ] Add methods for accessing it
* [ ] Implement in a suitable plugin to demonstrate its use (e.g. last line of output for buildelement)

## Acceptance Criteria

[//]: # (Acceptance criteria should follow the S.M.A.R.T. principle https://en.wikipedia.org/wiki/SMART_criteria )

----
[//]: # (To review information about possible relevant labels for this issue please view the list of labels: https://gitlab.com/BuildStream/buildstream/labels)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jul 30, 2019, 16:03

mentioned in merge request !1358

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Sep 10, 2019, 11:31

Note that these days this issue practically depends on #1092, because there are no tasks left in the main BuildStream process that would require this kind of output.

We'll want to implement progress reporting for plugins before tackling this, so that we can implement it for, say, buildelement.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Sep 10, 2019, 11:31

assigned to [[Gitlab user @tlater]](https://gitlab.com/tlater)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Dec 2, 2019, 11:05

unassigned [[Gitlab user @tlater]](https://gitlab.com/tlater)
