### ISSUE TITLE
Check whether progress reporting could be incorrect in certain cases (technical debt)

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1094]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1094)
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Jul 26, 2019, 14:31

## Background

!1482 adds a way to report progress when loading elements, but there are points where an element might be loaded or resolved that happen outside the scope of a SimpleTask.

Tests have been added to check that the tallies are correct when loading across a junction in a simple case, but the full spread of possibilities where elements might be loaded or resolved has not been investigated.

## Task description

[//]: # (Short summary of the action to be executed)

* [x] Trace through loader code to see which points `Loader._collect_element` are called to see which ones will and won't have a Task passed in.
* [x] Assess whether a Task *should* be passed in for those cases.
* [x] Write tests to cover any edge cases that are not already covered

## Acceptance Criteria

[//]: # (Acceptance criteria should follow the S.M.A.R.T. principle https://en.wikipedia.org/wiki/SMART_criteria )

----
[//]: # (To review information about possible relevant labels for this issue please view the list of labels: https://gitlab.com/BuildStream/buildstream/labels)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jul 30, 2019, 16:03

mentioned in merge request !1358

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Sep 10, 2019, 11:31

assigned to [[Gitlab user @tlater]](https://gitlab.com/tlater)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Sep 13, 2019, 17:42

This seems to only occur here: https://gitlab.com/BuildStream/buildstream/blob/master/src/buildstream/_loader/loader.py#L575

Which, given that this only loads a junction element and creates a Loader from it, which in turn is always given a Task when it loads elements, should be fine.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Sep 18, 2019, 18:33

mentioned in merge request !1608

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Oct 8, 2019, 14:26

marked the task **Write tests to cover any edge cases that are not already covered** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Oct 8, 2019, 14:26

marked the task **Write tests to cover any edge cases that are not already covered** as incomplete

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Oct 8, 2019, 14:26

marked the task **Trace through loader code to see which points `Loader._collect_element` are called to see which ones will and won't have a Task passed in.** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Oct 8, 2019, 14:26

marked the task **Assess whether a Task *should* be passed in for those cases.** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Oct 8, 2019, 14:27

marked the task **Write tests to cover any edge cases that are not already covered** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Oct 10, 2019, 13:45

closed via merge request !1608

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Oct 10, 2019, 13:45

mentioned in commit 6c6c581162ed7d87bad680330610e29d828d0f25
