### ISSUE TITLE
Implement `bst artifact show`

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1103]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1103)
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Aug 13, 2019, 11:16

## Background

A new artifact sub-command: `bst artifact show` was proposed by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on the mailing list (see: [here](https://mail.gnome.org/archives/buildstream-list/2019-May/msg00045.html)). The implementation of this command was then proposed by myself and discussed on the list (see: [here](https://mail.gnome.org/archives/buildstream-list/2019-August/msg00002.html)).

In the discussion, it was highlighted that it's important to have the `--deps` argument for this command. This means that we need to be able to load a dependency graph given an artifact ref. Therefore, implementing support for this will be considered a prerequsite to implementing `bst artifact show`.

## Task description

[//]: # (Short summary of the action to be executed)

* [x] Ensure that the proto has the necessary information which will allow it to reconstruct a dependency graph - (!1548)
* [x] ~~Add the ability to walk an artifact's dependency tree to the loader~~
* [x] Add the ability to load artifacts and their (build) dependencies - (!1553)
* [x] Write `bst artifact show` for the local cache case - (!1560: abbcc263563d6c3bd7b76f815576bf6f2da96707)
* [x] ~~Add remote support (via a `--remote`/`--all-remotes` flags)to `bst artifact show`~~
* [x] add remote support to `bst artifact show` - (!1560: bf6ca6615bb5b69defcc41f33625cbfc2b300f1a)

## Acceptance Criteria
We should be able to use `bst artifact show` to see if artifacts are available remotely.

## Further work
* Once the support for loading a dependency graph given an artifact ref has landed, we can then fix `artifact push/pull/checkout` to ensure that they can support artifact refs as arguments
    * This closes https://gitlab.com/BuildStream/buildstream/issues/822
* Refactor the loader so that we can perform artifact related jobs outside of a project
* Address artifacts only by cache key

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Aug 13, 2019, 11:59

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Aug 15, 2019, 16:18

mentioned in merge request !1548

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Aug 20, 2019, 11:11

marked the task **Ensure that the proto has the necessary information which will allow it to reconstruct a dependency graph** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Aug 20, 2019, 11:12

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Aug 20, 2019, 11:14

!1548 adds the project name of dependencies to the artifact proto, thus achieving the first task.

!1553 adds the ability to load artifact refs with their dependencies. When this lands, the second task will be done.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Aug 22, 2019, 17:48

mentioned in merge request !1560

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Aug 28, 2019, 17:03

marked the task **Add the ability to load artifacts and their (build) dependencies** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Aug 28, 2019, 17:06

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Aug 28, 2019, 17:06

Closed by: !1548, !1553 and !1560

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Aug 28, 2019, 17:06

closed
