### ISSUE TITLE
Split up the CONTRIBUTING doc

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1116]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1116)
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Aug 31, 2019, 14:24

## Background

I took an action at one of the irc monthly team meetings to split up the BuildStream CONTRIBUTING document into more manageable chunks that we could link to from the main page. The [recent ticket](https://gitlab.com/BuildStream/buildstream/issues/1115
) about adding docs on how to install buildbox dependencies reminded me to raise a ticket.

## Task description

Suggestions as to how it could be split up:

* [ ] Intro and Committer Policy, then links out to:
* [ ] Dependencies required to hack on master
* [ ] Coding Guidelines
* [ ] Principles followed for UI/UX design 
* [ ] Adding Core Plug-Ins
* [ ] Documentation
* [ ] Testing
* [ ] Measuring Performance 
* [ ] Process for releases

Also, we don't mention marge-bot in contributing, let's add those details there.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Sep 1, 2019, 12:19

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Sep 1, 2019, 12:20

Amended the description to add:
* [ ] Principles followed for UI/UX design 

Which we have been meaning to do for a while, and is captured in https://gitlab.com/BuildStream/buildstream/issues/1068

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Sep 10, 2019, 12:48

mentioned in merge request !1584

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Sep 12, 2019, 16:02

mentioned in commit 54d30ccf735602d1d6378f61445e511a6d594071

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Sep 12, 2019, 16:03

mentioned in merge request !1604

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Sep 13, 2019, 09:22

Also, we don't mention marge-bot in contributing, let's add those details there.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Sep 13, 2019, 09:32

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Sep 13, 2019, 16:35

mentioned in commit 081d5c6f494fbcd0328d636f9ea7cad7bdc64dd7

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Sep 13, 2019, 17:17

mentioned in commit 2b54ff7db5628b3074871136a651c3a2a6862b1e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Sep 13, 2019, 18:19

closed via merge request !1604

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Sep 13, 2019, 18:19

mentioned in commit 766c6c8d3e051011f90a920ece736de36f380bdd

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 18, 2019, 12:35

mentioned in commit f88755db041f46ade65723f1c9c80c234b1a1af8

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Sep 18, 2019, 14:51

mentioned in commit 6b36172c71fd05f87b6f715a9e0b685546290042

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Sep 27, 2019, 17:52

mentioned in commit 12059f3ecb65dbfb639ecf9f420ba6448901ffe5

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Sep 30, 2019, 15:25

mentioned in commit 0a6de9ec3fd24782279722185b59751887184e4c
