### ISSUE TITLE
Add CI for native windows support

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1163]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1163)
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 8, 2019, 14:11

## Background

NOTE: This is based on the assumption that win32 refers to the windows API, not running on a 32-bit Windows system, as there is some ambiguity.

There is an ongoing effort (#1021) to add native windows support to buildstream, and a need to ensure that this support doesn't bit rot, or at least where functionality breaks it is known exactly when this happens.

The proposed solution is to set up a CI runner and CI jobs to exercise the currently-implemented functionality.
Work has apparently been made to support:
* `bst init`
* `bst help`
* `bst workspace list` (possibly)

And there are currently experimental branches to allow `bst build` for import elements.

## Task description

[//]: # (Short summary of the action to be executed)

* [x] Manually set up a Windows system to run CI jobs in native Windows
  * [x] Install Python and Pip
  * [x] Install BuildStream's pip dependencies
  * [x] Install a native windows gitlab runner
* [x] Produce automated instructions to spin up a runner from scratch
  - There is already a script to spin up a runner at gitlab.com/jonathanmaw/wsl-setup-script that can be modified, though if there's spare time it might be worth looking into other tools (ansible or packer scripts?)
* [ ] Add gitlab CI for native windows to exercise `bst init` and `bst help functionality.
  - Using tox or pytest is not necessary, but will be simpler if tox or pytest "just work" (modulo nearly every test failing).
  - If these steps prove to be time-consuming, these tests should be set to only run on master,
    otherwise we will block buildstream's CI.
* [x] Install the experimental branches of `buildbox-common` and `buildbox-casd` in native windows.
  - Building these is likely to be highly time-consuming.
* [x] Produce automated instructions for `buildbox-common` and `buildbox-casd` installation.
  - It must be relatively easy to specify different refs of buildbox-common and buildbox-casd, so
    upgrading to the latest version of these (e.g. when there are more fixes) is easy.
* [ ] Add gitlab CI for native windows to exercise `bst build` on import elements.
  - It must be relatively easy to disable this or make it optional.

## Acceptance Criteria

* When CI runs against master, tests are run to check windows 10 support for:
  - `bst init`
  - `bst help`
  - `bst build` of an import element.
* The test for `bst build`ing an import element can be easily disabled.

----
[//]: # (To review information about possible relevant labels for this issue please view the list of labels: https://gitlab.com/BuildStream/buildstream/labels)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 14, 2019, 15:17

marked the task **Manually set up a Windows system to run CI jobs in native Windows** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 14, 2019, 15:17

marked the task **Install Python and Pip** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 14, 2019, 15:17

marked the task **Install BuildStream's pip dependencies** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 14, 2019, 15:17

marked the task **Install the experimental branches of `buildbox-common` and `buildbox-casd` in native windows.** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 14, 2019, 15:30

Rather than follow my checklist in precise order, it was more expedient to follow the instructions in #1154 (and the additional notes in https://gitlab.com/snippets/1902536), to put together a command-line version of those instructions, then convert them to commands in an Autounattend FirstLogon script (i.e. https://docs.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-shell-setup-firstlogoncommands).

Having gotten as far as installing buildstream with native windows support, I have hit a roadbump where the commands appear to be run (they're all present in C:\Windows\Panther\UnattendGC\setupact.log), but they don't seem to have had the required effect (the only effects I could find was that chocolatey is installed; and the path to buildbox-casd has been added to PATH, but that directory doesn't exist).

I am now trying to extract logging information for what went wrong.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 15, 2019, 13:04

It looks like the place where things started going wrong is that the PATH environment variable being set by chocolatey's installer was for a different user than the one that was running the unattend scripts.

I will try to get it working by using the full paths to the executables.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 16, 2019, 12:45

Using full paths to executables is working well.

I was encountering a problem where installing the chocolatey package for visualstudio2017buildtools and visualstudio2017-workload-vctools was timing out after spending 45 minutes apparently idle. The solution to this was to remove the "--install-recommended" option from the installer, since we probably don't need everything it can install.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 16, 2019, 14:57

It turns out there was one part of visual studio that was missing, Microsoft Visual C++. The chocolatey package vcredist2017 appears to be its equivalent.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 16, 2019, 15:01

Another problem was that installing gitlab-runner from chocolatey with the "/Service" parameter enabled would cause the installation to fail, because it failed to install a service for gitlab-runner.

This appears to be done by calling `gitlab-runner install`, so I can run that separately and see what the errors are from that.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 17, 2019, 17:38

marked the task **Install a native windows gitlab runner** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 17, 2019, 17:38

marked the task **Produce automated instructions to spin up a runner from scratch** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 17, 2019, 17:38

marked the task **Produce automated instructions for `buildbox-common` and `buildbox-casd` installation.** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 17, 2019, 17:42

I finally have automatic configuration to spin up a windows VM that has all of the dependencies required to install buildstream, and registers itself with gitlab.

Next up:

1. Modify buildstream's CI script to perform the tests for us.

2. (nice-to-have) Figure out why `bst build` on import elements is failing (looks to be the same symptoms as https://gitlab.com/BuildStream/buildstream/issues/1154#note_228835376)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 21, 2019, 17:40

I've encountered some annoying syntax issues while trying to get environment variables set for all users for the packages that were installed, which has been a bit of a drag, as I was sure I'd already put that to bed.

In between that, however, the runner does work (https://gitlab.com/BuildStream/buildstream/-/jobs/327145384), but is having some problems with cython at the moment.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Oct 22, 2019, 09:05

tbf this should probably install bb-common and bb-casd pinned by refs, is that what currently happens [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw)?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 22, 2019, 10:27

Currently I install it as part of the runner setup, since AIUI it's very time-consuming.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 22, 2019, 17:47

A possibility raised today is that building buildbox-common and buildbox-casd might not take as long as previously thought. If this turns out to be true, then it would make more sense to include the compilation of buildbox-common and -casd in gitlab-ci, instead of runner setup.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 22, 2019, 17:50

Also, while chasing the problem of gitlab-ci installing buildstream, the error seems to be unrelated to cython - the generated file *does* exist. I suspect that the problem is that gitlab-ci was running as system, rather than a user.

I am currently testing whether that is actually the cause.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 24, 2019, 14:41

By manually installing gitlab-runner using chocolatey, and specifying that it should create a `gitlab-runner` user, I managed to have more success - the compilation stage succeeded, but it failed to download one of buildstream's dependencies (ujson) due to an SSL certificate problem  (either ssl was misconfigured for that user or the certificates were missing).

Following on from that, I tried to get gitlab-runner to install a service running as the default user ("user"). Unfortunately, the process of giving a user permission to start services is non-trivial (chocolatey can do it, but in the unattend script fails to install the service for a reason I couldn't easily track down).

After a hunch brought on by [this comment](https://gitlab.com/gitlab-org/gitlab-runner/issues/2550#note_142727594), I tried `gitlab-runner run` from the desktop session instead of an ssh session, and the runner started normally.
Given that this is also how we start gitlab-runner in the WSL runner, this should at least be quite simple.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 28, 2019, 18:00

I think I have made all the changes I need for .gitlab-ci.yml (https://gitlab.com/BuildStream/buildstream/commits/jonathan/win32_ci), but I still end up with breakages in my automatic runner setup, which mean every successful test run so far has required manual intervention.

The specific obstacles I am currently grappling with:
* The only way I've found to be able to automatically start a gitlab-runner is to install a shortcut into a user's "startup" directory (i.e. C:\Users\user\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup).
  - This part is fine, but configuring the unattend script to perform the command fails. I think the only way I'll get it to work in a meaningful period of time will be to write a powershell script and run that, instead of inlining the commands.
* I also have to attach a powershell script as the profile script (in C:\Users\user\Documents\WindowsPowerShell\Profile.ps1).
  - This involves invoking some powershell commands, which, if they turn out to have the same problems as the "Startup" script, will involve another attached script.
* Currently, installing buildstream when not all of its dependencies have been downloaded fails due to missing/misconfigured SSL certificates. This only happens within the gitlab-runner, not when installed via the command-line.
  - The solution to this is to do that installation during runner setup, which requires the profile script to be installed (otherwise as soon as something needs to be compiled, it fails to find the necessary build tools).

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 29, 2019, 10:02

The shortcut in a "startup" directory and the installation of a "profile" script are now working as planned.
The installation of buildstream dependencies is almost working, too. The only thing left to do is to track down why windows-curses wasn't installed.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 29, 2019, 14:06

The latest build (https://gitlab.com/BuildStream/buildstream/-/jobs/336151651) was accomplished with no manual intervention in the VM.

Things remaining to do:
* Possibly move the build and install of buildbox-common and buildbox-casd into gitlab-CI, since they only take a couple of minutes apiece. It turns out that it takes longer to print the output of building them than it does to build them, thanks to a huge amount of warnings being printed.
* Have the installation script pushed somewhere public.
* Submit a MR for the .gitlab-ci.yml changes.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 29, 2019, 17:04

Having looked at how buildbox-casd is installed in the WSL runner, I'm less certain it can be safely built as part of gitlab-ci, or at the very least not in the time available.

In the WSL tests, a statically-compiled buildbox-casd binary is extracted and added to PATH.

I haven't looked up how to statically-compile a binary using Windows tools, so I'm not confident in how to do that.

The alternative is to simply install buildbox-common and buildbox-casd, but without a clear way to delete the old versions, we'd be installing newer versions over the top of older versions and hoping that doesn't lead to misleading successes / failures.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 30, 2019, 14:53

mentioned in merge request !1678

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Oct 31, 2019, 15:57

closed via merge request !1678

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Oct 31, 2019, 15:57

mentioned in commit 5c2fe471d9eda5b1924fc9a376d81b14c556e2d4
