### ISSUE TITLE
Add CI job for buildbox-run-bubblewrap with buildbox-fuse

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1226]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1226)
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Dec 3, 2019, 10:39

This depends on:
* [x] Add buildbox-run sandboxing backend !1738
* [x] Create buildbox-run-bubblewrap https://gitlab.com/BuildGrid/buildbox/buildbox-run-bubblewrap/issues/1
* [x] buildbox-casd: Add a FUSE backend for Stage() https://gitlab.com/BuildGrid/buildbox/buildbox-casd/issues/8
* [x] buildbox-fuse: Drop command execution https://gitlab.com/BuildGrid/buildbox/buildbox-fuse/merge_requests/21
* [x] buildbox-fuse: Set correct st_size for symlinks https://gitlab.com/BuildGrid/buildbox/buildbox-fuse/merge_requests/22
* [x] buildbox-fuse: Add option to disable writing to local cache https://gitlab.com/BuildGrid/buildbox/buildbox-fuse/issues/35
* [x] Add buildbox-run-bubblewrap and buildbox-fuse to CI images (and update buildbox-casd) https://gitlab.com/BuildStream/buildstream-docker-images/merge_requests/150
* [x] Add BuildStream CI job https://gitlab.com/BuildStream/buildstream/merge_requests/1752

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Dec 3, 2019, 16:51

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Dec 4, 2019, 11:33

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Dec 4, 2019, 16:05

marked the task **buildbox-fuse: Set correct st_size for symlinks https://gitlab.com/BuildGrid/buildbox/buildbox-fuse/merge_requests/22** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Dec 5, 2019, 11:16

marked the task **buildbox-fuse: Add option to disable writing to local cache https://gitlab.com/BuildGrid/buildbox/buildbox-fuse/issues/35** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Dec 5, 2019, 16:38

mentioned in merge request buildstream-docker-images!150

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Dec 5, 2019, 16:39

mentioned in merge request !1752

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Dec 5, 2019, 16:47

mentioned in merge request !1738

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Dec 5, 2019, 17:00

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Dec 6, 2019, 06:49

marked the task **buildbox-fuse: Drop command execution https://gitlab.com/BuildGrid/buildbox/buildbox-fuse/merge_requests/21** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Dec 9, 2019, 19:11

marked the task **Create buildbox-run-bubblewrap https://gitlab.com/BuildGrid/buildbox/buildbox-run-bubblewrap/issues/1** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Dec 9, 2019, 19:11

marked the task **buildbox-casd: Add a FUSE backend for Stage() https://gitlab.com/BuildGrid/buildbox/buildbox-casd/issues/8** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Dec 9, 2019, 19:11

marked the task **Add buildbox-run-bubblewrap and buildbox-fuse to CI images (and update buildbox-casd) https://gitlab.com/BuildStream/buildstream-docker-images/merge_requests/150** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Dec 10, 2019, 15:24

closed via merge request !1752

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Dec 10, 2019, 15:24

mentioned in commit a8fb5cd752586ea6cd09f090fa9bf9c24fa730cb

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Dec 10, 2019, 17:27

marked the task **Add buildbox-run sandboxing backend !1738** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Dec 10, 2019, 17:28

marked the task **Add BuildStream CI job https://gitlab.com/BuildStream/buildstream/merge_requests/1752** as completed
