### ISSUE TITLE
BuildStream linter

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1299]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1299)
In GitLab by [[Gitlab user @frazerclews]](https://gitlab.com/frazerclews) on May 4, 2020, 16:11

## Background

[//]: # Add a BuildStream linter

## Task description

[//]: # A BuildStream linter would make it easier for newcomers and projects with a large BuildStream codebase to handle problems in BuildStream, while at the same time enforce style guidelines to make BuildStream files more consistent and easier to read

* [ ] Decide on weather this should be something in a separte project or part of this one
* [ ] Go through a list of guidelines we want to add to the linter
* [ ] Make the linter

## Acceptance Criteria

[//]: # A program that can read BuildStream files and output nothing if everything is OK, or provide errors, warnings, or style guides that should be applied to a code base, stretch goal for first release would allow users to disbale certain errors. Anyone who has experience with BuildStream and parsing code should take part

----
[//]: # Enhancement, Infrastructure

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @frazerclews]](https://gitlab.com/frazerclews) on May 4, 2020, 16:13

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on May 4, 2020, 16:14

Would it be fair to say this is a duplicate of #485 ?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @frazerclews]](https://gitlab.com/frazerclews) on May 4, 2020, 16:19

Ah didn't see that, I guess the difference with mine is to also present errors and warnings in the `.bst` scripts as well as styling to help find possible errors

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on May 5, 2020, 10:16

marked this issue as related to #485

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on May 6, 2020, 11:11

yeah, I think this is a dupe of https://gitlab.com/BuildStream/buildstream/-/issues/638
