### ISSUE TITLE
Make element selection consistent across commands

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1349]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1349)
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Jul 3, 2020, 12:12

## Summary

BuildStream mainly offers two options to tweak element sections - `--except` and `--deps`. However they are not accepted uniformly by all commands.

For example, some commands like `show`, `source checkout` etc support `--except` option to exclude certain elements from the pipeline. However, others like `artifact checkout` don't.

Similarly, not all commands accept all values for `--deps`. For example, `source track` only accepts `all` and `none` whereas `show` accepts `all|none|build|run|plan`. Out of these, `plan` is probably the most tricky one, as mentioned in https://gitlab.com/BuildStream/buildstream/-/merge_requests/1893#note_335927435. We need a plan about how to handle `--deps plan` sensibly. But, it should be generally reasonable to add the other options to all the commands.

## Todo

Part of `--deps` unification was implemented in !1904. Here's what's left to do:

- [x] Unify `--deps` for the remaining commands
- [ ] Provide `--except` to commands more consistently, review where it should be added
- [ ] Have a plan for handling `--deps plan`, especially important from API perspective if it's going to move out of `--deps` option
- [ ] Implement the said plan

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Jul 3, 2020, 12:13

assigned to [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Jul 3, 2020, 12:13

mentioned in merge request !1975

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 13, 2020, 22:16

mentioned in commit 5965be6bbf23929f70dd4e845e43ca33abcae56a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 13, 2020, 22:17

mentioned in merge request !2027

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 13, 2020, 22:22

mentioned in merge request !1893

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 13, 2020, 23:26

mentioned in commit fd4b622ff77251d791a227719f25db19d4c10b22

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 14, 2020, 12:44

mentioned in commit abd86159faaa2aaec839339f6a5ab77c8fc1bae8

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 18, 2020, 21:30

marked the task **Unify `--deps` for the remaining commands** as completed
