### ISSUE TITLE
Can we replace/simplify some os.path.join()s for performance?

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#207]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/207)
In GitLab by [[Gitlab user @samthursfield]](https://gitlab.com/samthursfield) on Jan 25, 2018, 10:49

## Background

This issue was part of a list of things to investigate regarding performance.
Previously described by [[Gitlab user @samthursfield]](https://gitlab.com/samthursfield) as:

> As shown in the profile attached to !247, we spend a lot of time in os.path.join() -- for example 8 seconds of a 50 second staging operation. This would be worth optimizing if possible.

`os.path.join` contains some logic in order to cover many cases. It is possible that when used in a tight loop (while iterating over lots of files) it might be worth investigating. Especially if we are sure that the join we expect a is simple string concatenation.

We can consider extending this for other costly `os.path` functions.

## Task description (in order)

* [ ] Figure out which os.path.join() calls are indeed in a tight loop(s)
* [ ] Determine if those calls are simple enough & replecable
* [ ] Do performance comparisons with various projects
* [ ] Have a consensus on which parts to replace (consider readability & long term roadmap)

## Acceptance Criteria

It should provide significant performance gain while not complicating the codebase and making it unreadable.

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @samthursfield]](https://gitlab.com/samthursfield) on Jan 25, 2018, 11:18

[[Gitlab user @gokcennurlu]](https://gitlab.com/gokcennurlu) noticed that os.path.join is 50x slower than using `+` in simple testcase ... in the performance hotspot that is utils.link_files() it may be worth doing something a bit gross in the name of speed.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @gokcennurlu]](https://gitlab.com/gokcennurlu) on Jan 25, 2018, 11:32

```python
import timeit
import sys

statements=["""\
a = os.path.join('ASDASDASD', 'ASDASDASD')
""",
"""\
a = 'ASDASDASD' + '/' + 'ASDASDASD'
""",
"""\
a = '{}/{}'.format('ASDASDASD','ASDASDASD')
""",
"""\
a = '%s/%s' % ('ASDASDASD','ASDASDASD')
"""]

for s in statements:
    t = timeit.Timer(stmt=s, setup='import os')
    sys.stdout.write("> "+ s)
    sys.stdout.write("\t%.3f usec/pass\n\n" % (1000000 * t.timeit(number=100000)/100000))
```

Results:
```
> a = os.path.join('ASDASDASD', 'ASDASDASD')
	1.430 usec/pass

> a = 'ASDASDASD' + '/' + 'ASDASDASD'
	0.013 usec/pass

> a = '{}/{}'.format('ASDASDASD','ASDASDASD')
	0.336 usec/pass

> a = '%s/%s' % ('ASDASDASD','ASDASDASD')
	0.013 usec/pass
```

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @knownexus]](https://gitlab.com/knownexus) on Jan 25, 2018, 12:06

Have run through the codebase, we have no unnecessary function calls (instances where a variable could be used instead of a function call) so it looks like an alternative way of joining safely would be needed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @ghost1]](https://gitlab.com/ghost1) on Jun 18, 2018, 11:43

Wouldn't using `+` and `os.sep` be a faster safe way of joining in most cases?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @gokcennurlu]](https://gitlab.com/gokcennurlu) on Jun 18, 2018, 11:57

Yes, for the parts where we don't really need the logic of [this](https://github.com/python/cpython/blob/master/Lib/posixpath.py#L83) and/or when it is just a path `append` operation, this should speed up things. We should measure it though.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @ghost1]](https://gitlab.com/ghost1) on Jun 18, 2018, 12:43

```python
import timeit
import sys

statements=["""\
a = os.path.join('asdasdasd', 'asdasdasd')
""",
"""\
a = 'asdasdasd' + '/'+ 'asdasdasd'
""",
"""\
a = '%s/%s' % ('asdasdasd', 'adsasdasd')
""",
"""\
a = 'asdasdasd' + os.sep + 'asdasdasd'
"""]

for s in statements:
	t = timeit.Timer(stmt=s, setup="import os")
	sys.stdout.write("> "+ s)
	sys.stdout.write("\t%.3f usec/pass\n\n" % (1000000 * t.timeit(number=100000)/100000))
```

Output:
```
> a = os.path.join('asdasdasd', 'asdasdasd')
	0.750 usec/pass

> a = 'asdasdasd' + '/'+ 'asdasdasd'
	0.012 usec/pass

> a = '%s/%s' % ('asdasdasd', 'adsasdasd')
	0.012 usec/pass

> a = 'asdasdasd' + os.sep + 'asdasdasd'
	0.127 usec/pass
```

So it's about 6x faster than current speed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @toscalix]](https://gitlab.com/toscalix) on Jun 21, 2018, 08:05

It is not clear to me what it should be done. Can we describe it in the Ticket description please? If there is nothing left to be done or it is a somehow unrelated tasks, should we open a different ticket?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @gokcennurlu]](https://gitlab.com/gokcennurlu) on Jun 21, 2018, 11:52

changed title from **{-Lots of calls to os.path.join()-}** to **{+Can we replace/simplify some os.path.join()s for performance?+}**

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @gokcennurlu]](https://gitlab.com/gokcennurlu) on Jun 21, 2018, 11:52

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Jun 21, 2018, 13:55

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Jun 21, 2018, 14:05

[[Gitlab user @gokcennurlu]](https://gitlab.com/gokcennurlu) are you aware of any remaining areas in the codebase where this is relevant? Or even [[Gitlab user @samthursfield]](https://gitlab.com/samthursfield) ?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Jun 21, 2018, 20:05

I think we may have been discussing a real performance issue in #174, which the linked !247 addresses, but at this point this is a premature micro-optimization, we need benchmarks first to prove what we gain by making more changes around `os.path.realpath()` and/or `os.path.join()`.

Closing this until such a time that we can prove it's worthwhile.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Jun 21, 2018, 20:05

closed
