### ISSUE TITLE
Dog-Fooding: Build BuildStream with BuildStream

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#410]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/410)
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on May 29, 2018, 22:22

## Background

Also posted to the [mailing list](https://mail.gnome.org/archives/buildstream-list/2018-May/msg00067.html) about this, and then followed up on in [another thread](https://mail.gnome.org/archives/buildstream-list/2018-June/msg00020.html).

I think there are some clear benefits to dog-fooding:

* Demonstrate confidence in BuildStream.
* Increase the amount of real world use cases, thus identifying more bugs.
* Mitigating against the risk of developers working 'in a vacuum', by ensuring developers are also users of the tool.

There is a risk that this will prove more difficult than anticipated, and potentially serve as a distraction that does not bring as much benefit as desired, but I think this risk is quite low, overall.

Having spoken to people informally about this, there seems to be a general consensus that this is clearly a good idea, but BuildStream is probably not yet ready for it at the moment.

If there is something you know of which blocks dog-fooding, I ask for your contributions here to help me identify that. Please could I request that you link from this issue to any already open issue which is blocking dog-fooding from happening, or open up a new issue if something is not already captured.

## Task description

* [ ] Build BuildStream using BuildStream.

I plan to expand this once the specifics of the task become clearer...

## Acceptance Criteria

* [ ] Link to a subgroup in gitlab for the example project
* [ ] Successful demo of buildstream being built using buildstream 

I plan to expand this once the specifics of the task become clearer...

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on May 29, 2018, 22:24

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @toscalix]](https://gitlab.com/toscalix) on Jun 24, 2018, 15:47

[[Gitlab user @laurence]](https://gitlab.com/laurence) I believe there is further actions related to this topic sent to the mailing list. If there will be actions derived from those mails, they should be added to the description of this topic, right?

If the discussion is still ongoing, then a link to the thread would be the way to go.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jun 24, 2018, 16:48

Correct.

Currently, that conversation is still ongoing, and this ticket will be updated when the time is right.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jul 11, 2018, 10:57

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jul 11, 2018, 11:41

Notes taken from the GUADEC BoF of Weds July 11 2018: 

# Dogfooding

#### Introduction

* We have a problem that developers are making changes to buildstream without using buildtream so the only feedback we get is from users.
* We can advance some of those issues by using the tool ourselves.
there's been debate about best way to do this
* we could build a system to host buildstream in and use bst shell to run the test suit in this
* we could build other images as well  (flatpak/container) images out of this so that we can use the current version
* There's worries that we could end up over optimising for our own usecase

#### Potential blocker
* Linux kernel, before 4.18, does not support unprivilaged fuse mounting - you can't combine usernamespace and  FUSE, and we need FUSE.
* So one option is just to wait for 4.18 which is realeased in a couple of weeks

#### Other notes
* Valentine emphasises the point that the bottom line is simple: Our developers aren't using the tool and that using the tool in anyway is going to be a big step forward.
* It looks like we have users working with slightly different workflows: bst shell vs workspaces.
* Augustin has points he wants developers to consider in order to ensure we do not go too far.
* dogfooding is about testing a tool as it is consumed by users and use it as users do, mimetising their workflow as much as possible. It is advancing problems they will have.
* Dogfooding vs simulation/emulation.
* AB: simulate the dev workflow in one example and then set up test to run over and over again - that is a simulation / emulation, rather than dog-fooding
* we are testing as users *are going to* use the tool, not how they are using it at the moment. There is a risk of getting an experience that is not real.
* Let's ensure we don't set up an imagined workflow here - need to base it on actual use cases. 
* questions that this is actually dog fooding but still sees value in doing it...
* Problem is perhaps that bst is too different from the stuff being developed by downstream users
* We can test the workflow of developing using workspaces, but may not be able to test bst shell due to the above issues
* We could make an example building buildstream, buildgrid and buildbox
* Tristan M points out that python developer workflow means we'll never actually build anything using buildstream for buildstream
* we could use buildstream to build pakages from which we could install buildstream.

#### Summary
* Clear path forward is to have a project that we can open a workspace with, develop in that way, build a package that we can install.
* We may not get shell working because of kernel versions but it's something to look at. Building Buildbox is a good target. 
* So, outcome should be a workflow for devs to use bst files for 3 compenents to build - buildgrid, buildbox, buildstream.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @richardmaw-codethink]](https://gitlab.com/richardmaw-codethink) on Aug 7, 2018, 11:26

assigned to [[Gitlab user @richardmaw-codethink]](https://gitlab.com/richardmaw-codethink)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @richardmaw-codethink]](https://gitlab.com/richardmaw-codethink) on Aug 7, 2018, 11:31

The workflow we're hoping to support is to
be able to create workspaces for BuildStream components,
use `bst build` to provide BuildStream's dependencies
and test that it is still installable,
then ideally run BuildStream's test suite inside a `bst shell`.

1.  Create project skeleton for BuildStream .bst files super-project.

    This is a separate task to account for bike-shedding of the name
    and acquiring permission to create the GitLab project if necessary.

2.  Add BuildStream to BuildStream super-project.

    This should depend on freedesktop-sdk via a junction,
    and include any extra dependencies not in freedesktop-sdk.

3.  Test and Document the workflow.

    Ideally the documentation would be written
    such that it can be run as a test in CI.

4.  Add BuildBox to BuildStream super-project.

    This should depend on freedesktop-sdk via a junction,
    and include any extra dependencies not in freedesktop-sdk.

5.  Add BuildGrid to BuildStream super-project.

    This should depend on BuildBox as a runtime dependency
    and include any extra dependencies not in freedesktop-sdk.

Barring some miracle, we can't depend on Linux 4.18 being available
so we need to task one of:

6.  Add a flag to cripple `bst shell` enough
    that BuildStream may start its sandbox inside.

7.  Documentation and tooling for how to set up a freedesktop-sdk container
    that doesn't use user namespacing
    that we can install our buildbox and buildgrid artifacts into
    so we can run the test suite in an environment
    similar to if we had a working `bst shell`.

8.  Modify the definitions to produce a self-contained application bundle
    for BuildBox, BuildGrid and BuildStream
    that may be installed independently of the host platform.

    Difficult to estimate.
    BuildBox may be possible to handle by statically linking.
    To reliably bundle BuildGrid would require distributing a python runtime
    and I've no experience to draw an estimate from that.
    pip might be enough to install BuildGrid without problems,
    but we're still depending on the host system satisfying the dependencies,
    and we've experience with pip getting confused and breaking the host.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Aug 8, 2018, 16:35

Related with this, other ways of "dog-fooding":
- https://gitlab.com/BuildStream/buildstream/issues/548
- https://gitlab.com/BuildStream/buildstream/issues/549

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Aug 8, 2018, 16:35

marked this issue as related to #548

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Aug 8, 2018, 16:35

marked this issue as related to #549

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @richardmaw-codethink]](https://gitlab.com/richardmaw-codethink) on Aug 9, 2018, 12:55

mentioned in merge request !570

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Sep 11, 2018, 19:43

Related MRs that were found as a result of dog-fooding:

* https://gitlab.com/BuildStream/buildstream/merge_requests/780
* https://gitlab.com/BuildStream/buildstream/merge_requests/781
* https://gitlab.com/BuildStream/buildstream/merge_requests/783
* https://gitlab.com/BuildStream/buildstream/merge_requests/784
* https://gitlab.com/BuildStream/buildstream/merge_requests/788

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @richardmaw-codethink]](https://gitlab.com/richardmaw-codethink) on Sep 17, 2018, 12:00

https://gitlab.com/BuildStream/buildstream/merge_requests/781 is the last outstanding MR and is needing a rework.

Investigation of using 4.18 is postponed until after that, since using a 4.18 backport on debian still has the issue of proc being unmountable while [[Gitlab user @juergbi]](https://gitlab.com/juergbi) reported being able to nest bubblewrap.

Integration repository at https://gitlab.com/richardmaw-codethink/buildstream-integration is not tidy, but at minimum needs a license to be considered releasable, though should be moved under the buildstream project proper.
