### ISSUE TITLE
Create a CAS-backed virtual directory implementation

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#417]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/417)
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Jun 4, 2018, 15:37

## Background

After CAS-based artifact caches are in use (#387), we can allow certain elements in BuildStream to use the CAS directly instead of extracting to a filesystem first, which should improve performance.

## Task description

Implement CAS-based virtual directories using the abstract virtual directory implementation from #394.

* [x] Implement CASBasedDirectory
* [x] Switch Import and Compose elements to use the new CAS-based directory instead of file-based virtual directories.

## Acceptance Criteria

* [x] All existing tests should pass
* [ ] freedesktop-sdk should build correctly and we should be able to verify that the new CAS-based directory has been used
* [ ] Build time for freedesktop-sdk should be no worse than 10% slower than it was without this MR.

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Jun 4, 2018, 16:15

mentioned in merge request !481

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Jul 3, 2018, 14:58

Completed (!481) but needs !445 to be reviewed and merged first.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Jul 3, 2018, 15:10

marked this issue as related to #454

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Jul 13, 2018, 11:11

Currently working on CAS-to-CAS import which is a performance improvement; the rest of this MR can still be reviewed.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @toscalix]](https://gitlab.com/toscalix) on Jul 25, 2018, 11:35

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Aug 2, 2018, 09:54

marked the task **Implement CASBasedDirectory** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Aug 2, 2018, 09:54

marked the task **All existing tests should pass** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Aug 2, 2018, 09:56

!481 ready for review but doesn't include the Import/Compose elements - these can run integration commands so can't work until we have a local FUSE.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Aug 9, 2018, 16:52

Has been reviewed by [[Gitlab user @danielsilverstone]](https://gitlab.com/danielsilverstone)\-ct and [[Gitlab user @juergbi]](https://gitlab.com/juergbi), waiting for one further review from [[Gitlab user @juergbi]](https://gitlab.com/juergbi) before proceeding.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Aug 20, 2018, 08:44

marked the task **Switch Import and Compose elements to use the new CAS-based directory instead of file-based virtual directories.** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Aug 20, 2018, 08:46

!481 has been merged. I'm leaving this open for now as we don't have a good test of freedesktop-sdk or a time measurement for the build.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Aug 24, 2018, 17:01

Going to close this as there's no prospect of work being done in the next two weeks; we can open another ticket for performance if needed.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Aug 24, 2018, 17:01

closed
