### ISSUE TITLE
Migrate X86 image example from examples repo to main repo

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#438]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/438)
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jun 22, 2018, 11:56

## Background

Instead of having a separate repo for examples of BuildStream, we should migrate these to the main repo, or the bst-external repo, and include the relevant documentation.

## Task description

* [ ] Decide to migrate to main repo or bst-external
* [ ] Solve bst-external#3
* [ ] Update and amend the docs we currently have for authoring an image - https://gitlab.com/BuildStream/buildstream/merge_requests/262
  * [ ] Give the example a "name"
  * [ ] Create `doc/source/examples_${name}.rst`
  * [ ] Ensure we use the "literalinclude" rst directive to show the example `.bst` files
  * [ ] Ensure we link to the correct pages when talking about features
  * [ ] Ensure that we instruct the user to install bst-external (via pip) onto their system as this example makes use of the x86image and docker plugins
* [ ] Migrate the [X86 image example](https://gitlab.com/BuildStream/buildstream-examples/tree/master/build-x86image)
  * [ ] Create a sample project that lives in the directory `doc/examples/${name}/`
  * [ ] Create an integration test which runs in CI for the example, this is called `tests/examples/${name}.py`

## Acceptance Criteria

* [ ] Integrate the x86image example into the documentation

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Jun 22, 2018, 12:05

assigned to [[Gitlab user @tlater]](https://gitlab.com/tlater)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Jun 22, 2018, 12:06

Thanks for raising these [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) :)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Jun 22, 2018, 12:11

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Jun 22, 2018, 12:12

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Jun 22, 2018, 12:14

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Jun 22, 2018, 12:14

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Jun 23, 2018, 03:38

I wonder if we should put this in docs for `bst-external` instead.

Technically, the `x86Image` is not an upstream plugin, at least not yet. Maybe this should go into `bst-external` docs ?

On the other hand, it's a very important element, we should test it more and improve on it to at least prepare it to honor a stable configuration API contract - and move it upstream.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Jun 23, 2018, 03:59

Also, what should we do with !262 ?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Jun 23, 2018, 11:31

I believe !262 should be adopted to fulfill the requirements here.

I do agree that this would be better in the `bst-external` docs, perhaps we could also have an examples section in there?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @toscalix]](https://gitlab.com/toscalix) on Jun 24, 2018, 15:10

[[Gitlab user @laurence]](https://gitlab.com/laurence) given the comments, should this ticket remain as it is or should you reconsider it?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jun 24, 2018, 16:39

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jun 24, 2018, 16:41

updated description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jun 25, 2018, 10:10

marked this issue as related to bst-external#3

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Jun 25, 2018, 11:54

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jul 3, 2018, 14:35

Note that this example makes use of some bst-external plugins [here](https://gitlab.com/BuildStream/buildstream-examples/blob/master/build-x86image/project.conf#L10) thus requires the "BuildStream-external" package to be installed on the user's system. So we need to provide/direct the user to installation instructions for bst-external.

I've added a check box to the description to serve as a reminder to do this.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jul 3, 2018, 14:37

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Jul 4, 2018, 17:58

unassigned [[Gitlab user @tlater]](https://gitlab.com/tlater)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jul 27, 2018, 11:00

mentioned in commit c44db1c663106f877d7fb710a164709a49d97b96

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jul 27, 2018, 11:19

mentioned in commit ac3fc0bc9c9c9ef5057598bb95bc12f5d7ec53b2

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jul 27, 2018, 12:13

mentioned in commit 196cfffce5cbd873bbd773409d8d55ed848e8fc5

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Jul 27, 2018, 13:57

created branch [`438-migrate-x86-image-example-from-examples-repo-to-main-repo`](https://gitlab.com/BuildStream/buildstream/compare/master...438-migrate-x86-image-example-from-examples-repo-to-main-repo)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Jul 30, 2018, 16:35

Closing this issue and moving it to `bst-external`.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Jul 30, 2018, 16:35

closed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Jul 30, 2018, 16:43

reopened

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Jul 30, 2018, 16:43

moved to bst-external#14
