### ISSUE TITLE
Migrate Netsurf example from examples repo to main repo

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#439]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/439)
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jun 22, 2018, 11:57

## Background

Instead of having a separate repo for examples of BuildStream, we should migrate these to the main repo and include them in the documentation. Raising this before we forget. 

There are some issues with the projects currently which stops them building, which will need fixing before we migrate. So this ticket will need to be updated once these are better understood.

## Task description
* [ ] Migrate the [Netsurf example](https://gitlab.com/BuildStream/buildstream-examples/tree/master/netsurf-flatpak)

## Acceptance Criteria

* [ ] Link to documentation page showing X86 image example
* [ ] Ensure that the user is instructed to install BuildStream-external via pip as they will require the flatpak_image plugin

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Jun 23, 2018, 04:12

I think that we're going to want to:
* Land !471
* Restructure freedesktop-sdk project.conf such that it provides files to share configuration with downstream derived projects

... first, before we add a demo of how to build a flatpak. While it is currently possible right now the steps are not attractive, we would do better to simplify the process before advertising it.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jul 3, 2018, 14:39

Note that this example makes use of some bst-external plugins ([here](https://gitlab.com/BuildStream/buildstream-examples/blob/master/netsurf-flatpak/project.conf#L13) - note that the package name is also wrong here...) thus requires the "BuildStream-external" package to be installed on the user's system. So we need to provide/direct the user to installation instructions for bst-external.

I've added a check box to the description to serve as a reminder to do this.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jul 3, 2018, 14:40

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jul 27, 2018, 11:00

mentioned in commit c44db1c663106f877d7fb710a164709a49d97b96

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jul 27, 2018, 11:19

mentioned in commit ac3fc0bc9c9c9ef5057598bb95bc12f5d7ec53b2

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jul 27, 2018, 12:13

mentioned in commit 196cfffce5cbd873bbd773409d8d55ed848e8fc5
