### ISSUE TITLE
Remove VCS History

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#455]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/455)
In GitLab by [[Gitlab user @knownexus]](https://gitlab.com/knownexus) on Jul 3, 2018, 16:05

## Background
Connected to:
#376 Sources to only stage what is required for building, omitting large parts of VCS history

The original task required the removal of some git history from the cache.
This was being done to save space. See #376 for more information.

As this has become a large task, to allow the feature, and those dependent on it to go through sooner, it was decided that a partial issue be raised where the user can have either all of the VCS history or none of it.

[//]: #
We want to be able to control whether or not a project cache contains VCS history

## Task Idea / Overview

If `bst_format_version` is currently X, then the gate is X+1
Before the gate, the default value for the variable `vcs-history` is `keep`.
After the gate, the default value for that variable is `drop`.

In addition, a variable `vcs-history-git` has the default value
`%{vcs-history}` And similarly for `vcs-history-bzr`.

In elements, any of those may be overridden.

The `Source` plugins for `git` and `bzr`, look for a `history` key in their
source dictionary, if absent, the value `%{vcs-history-git}` or
`%{vcs-history-bzr}` is used as appropriate.

If the resolved value is `keep` then behaviour is entirely as it is now.

If the resolved value is `drop` then behaviour is changed:

1. The cache key now contains an entry `{"vcs-history":"drop"}`
2. Where possible flags for clone/branch are adjusted to reduce the amount
   of data moved into that directory before removal.  E.g. adding `-s` to
   the `git clone`.
3. Once the source is staged, the `.git` or `.bzr` directory is removed.

This approach means that if current behaviour is preserved by means of bumping
the format version and then including `variables: vcs-history: keep` in the
`project.conf`, the cache key calculation will be unchanged.

### Affected areas / concerns

1. It's possible that the variables (`vcs-history` etc) may need to be
   namespaced further in a `bst` "domain"?
2. This requires a number of global variables to be defined and validated
3. This requires changes to the `bzr` and the `git` Source handlers.

### Future proofing

If in the future we come up with a way to trim VCS history then we may do
another format bump to change the default from `drop` to `trim` and that can be
handled in a similar fashion without causing significant issue since each time
it is an active opt-in to the new behaviour which can be documented in the
`NEWS` file.

## Task description

[//]: # (Short summary of the action to be executed)

* [ ]  Add `vcs-history`, `vcs-history-git`, `vcs-history-bzr` variables to projectconfig.yaml
* [ ]  Set default of `vcs-history-git` and `vcs-history-bzr` to `vcs-history`
* [ ]  If `bst_format_version` is before defined point (Current + 1): set default of `vcs-history` to `Keep`
* [ ]  If `bst_format_version` is after defined point: set default of `vcs-history` to `Drop`
* [ ]  Add functionality to remove the VCS history based on flags`
* [ ]  If flag is `not` set to `keep`: add `{"vcs-history":"drop"}` to the cache key

## Related Issues
This task acts as a blocker for:
#311 #21 #376 #413 

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @knownexus]](https://gitlab.com/knownexus) on Jul 3, 2018, 16:07

changed title from **Remove {-Git-} History** to **Remove {+VCS+} History**

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jul 3, 2018, 18:01

Thanks for raising this.

I understand that it is considered as a blocker to some other issues being resolved, so please amend the description to refer to those issues, and link them via the 'related issues'. 

The 'Blocker' label, however, is now a label to be exclusively used for something that blocks a release, as per the [WIP Policy](https://gitlab.com/BuildStream/nosoftware/alignment/blob/master/BuildStream_policies.md). I will remove the label.

I will also add the appropriate metadata.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jul 3, 2018, 18:01

Ah, [[Gitlab user @toscalix]](https://gitlab.com/toscalix) did those things just as I was writing about them.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @knownexus]](https://gitlab.com/knownexus) on Jul 4, 2018, 12:07

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @knownexus]](https://gitlab.com/knownexus) on Jul 4, 2018, 12:08

mentioned in merge request !482

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @knownexus]](https://gitlab.com/knownexus) on Jul 4, 2018, 12:11

mentioned in merge request !474

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @knownexus]](https://gitlab.com/knownexus) on Jul 18, 2018, 11:17

unassigned [[Gitlab user @knownexus]](https://gitlab.com/knownexus)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @knownexus]](https://gitlab.com/knownexus) on Jul 20, 2018, 09:56

assigned to [[Gitlab user @knownexus]](https://gitlab.com/knownexus)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @knownexus]](https://gitlab.com/knownexus) on Jul 20, 2018, 10:26

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @knownexus]](https://gitlab.com/knownexus) on Jul 20, 2018, 10:32

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jul 20, 2018, 11:47

marked this issue as related to #376

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @knownexus]](https://gitlab.com/knownexus) on Jul 20, 2018, 13:39

The decision was made by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) to simply remove the .git and .bzr directories

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Jul 20, 2018, 13:45

mentioned in commit 2f18a81cee279274fc74c1911d6ee0ca2470f001

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Jul 20, 2018, 13:45

mentioned in commit 89ef00d9dea6db859decd31c5d269c036f140a95

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Jul 20, 2018, 14:05

This will be closed automatically by !556.

This no longer blocks the mentioned issues: #311 #21 #376 #413

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Jul 20, 2018, 15:29

mentioned in commit b662f17582bd6bfd3bacabfceb4250984ced9df7

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Jul 20, 2018, 15:29

mentioned in commit f484ab4f682ca09a2d5679df6309efb28e4b2429

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Jul 20, 2018, 15:52

closed via merge request !556

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @toscalix]](https://gitlab.com/toscalix) on Jul 25, 2018, 11:49

marked this issue as related to #487
