### ISSUE TITLE
Specify the behaviour when overwriting files, symlinks or directories

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#476]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/476)
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Jul 17, 2018, 14:57

## Background

When layering one artifact on top of another, we will find some directory entries which are the same in the existing directory tree as in the new tree. In most cases, the entry in the old world disappears and is replaced by the new one, except:

* Overwriting a directory with another directory should cause a merge, not a replacement
* Overwriting a symlink to a directory with another directory should cause a merge at the symlink's target.

These are probably obvious, but I think they should be explicitly stated.

The third case:

* Overwriting a file with a directory

Currently causes a crash in BuildStream. Should this be a straight replacement? We definitely need a test for it.

## Task description

* [ ] Figure out the specification
* [ ] Add the rules to the documentation
* [ ] Add a test for these rules

## Acceptance Criteria

* Rules are explicitly stated in the documentation
* Tests now cover all cases of replacing X with Y, where X and Y can be:

    * An ordinary file
    * A symlink to file
    * A symlink to directory
    * A broken symlink
    * A directory

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Aug 13, 2018, 09:48

mentioned in merge request !481

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Oct 3, 2018, 09:32

Now up at https://wiki.gnome.org/Projects/BuildStream/ImportRules - any edits welcom.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Oct 3, 2018, 09:32

closed
