### ISSUE TITLE
UI for inspecting build logs and failed builds from the artifact cache

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#536]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/536)
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Aug 1, 2018, 12:50

## Background

Now that we have landed Caching Failed Builds https://gitlab.com/BuildStream/buildstream/merge_requests/475 we need to add UI for users to interact with the failed build logs. 

#### An assumption:
* We only ever store one build (failed or successful) per artifact cache key.

#### Potential future optimisation:
* We can introduce a way of marking the artifacts as "failed" in the remote cache, in such a way that we don't need to download the whole artifact before knowing if it's failed.

## Task description
* [ ] `bst checkout {--hardlinks}` for failed build, which checks out failed build tree and stages dependencies
* [ ] `bst shell` for failed build, which sets up shell environment with SafeHardlinks wrapper around the failed build checkout
* [ ] `bst show` able to indicate 'failed' vs. 'successful' status, in addition to existing 'cached' vs. 'downloadable' states
* [ ] `bst show --logs` to view build logs embedded in an artifact
* [ ] Integration tests
* [ ] Documentation 

## Acceptance Criteria

* [ ] Have a user manually test that the above commands work as expected when inspecting the failed build logs.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Aug 1, 2018, 12:52

marked this issue as related to #76

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @franred]](https://gitlab.com/franred) on Aug 1, 2018, 14:56

> Now that we have landed Caching Failed Builds https://gitlab.com/BuildStream/buildstream/merge_requests/475 we need to add UI for users to interact with the failed build logs. 

I would say that this task is part of the one described in: https://mail.gnome.org/archives/buildstream-list/2018-July/msg00051.html

It does not only need to interact with failed build logs but with any log, which currently are not available to the user unless manually inspecting the cache directory ~/.cache/buildstream.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 2, 2018, 09:22

This appears to be a duplicate to #234, in fact, according to the headline.

Also this ignores the `bst artifact` command subgroup which is discussed [on the mailing list](https://mail.gnome.org/archives/buildstream-list/2018-July/msg00051.html) as [[Gitlab user @franred]](https://gitlab.com/franred) accurately points out.

The summary seems to lump a lot of stuff into the same bucket, so I ask [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) to please triage this more clearly into closable, separate issues.

We can keep this one open if you want to have a flagship issue, but the individual tasks would be better suited to block on the closing of separately filed individual issues. I think we don't really need this one in this case, though. For instance #234 is an issue regardless of whether builds have failed or not.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 2, 2018, 09:34

For the debugging of failed builds parts of this, I have filed #539

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 2, 2018, 09:35

I'm not sure what the `bst checkout` part of this is intended for, maybe this part needs to have a coherent proposal on the list.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Aug 2, 2018, 17:09

closed
