### ISSUE TITLE
Allow debugging of remotely failed builds

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#539]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/539)
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 2, 2018, 09:33

## Background

[//]: # (Provide a background or the root/source that justifies this task or action.)

This issue is technical debt introduced by #76 and should be addressed during the 1.3 dev cycle.

Since we now cache the failed build state and the build tree itself in the artifact caches, it is important to make it useful and provide the ability to debug a build artifact whether it failed remotely or locally, consequently changing and cleaning up some codepaths which handle debugging of local build failures in special ways.

## Task description

[//]: # (Short summary of the action to be executed)

* [x] Build directories in `~/.cache/buildstream/build` should now be cleaned up unconditionally
* [x] When a build fails and there is an interactive prompt, the code should now use the failed artifact in the cache (including the build tree) in order to reconstruct an environment for debugging.
* [x] Using the same mechanism, `bst shell` should now provide a way to launch a build shell from failed build artifact
* [x] The existing `bst shell --sysroot` option is collateral damage here, we should make it more coherent and have it work for any provided sysroot; e.g. it should work using a path to a directory where a `bst checkout` was performed.

## Acceptance Criteria

[//]: # (Acceptance criteria should follow the S.M.A.R.T. principle https://en.wikipedia.org/wiki/SMART_criteria )

We should have a unified way of debugging a failed build, and no separate codepaths for debugging a failed build which occurred locally or remotely.

For the collateral damage to `bst shell --sysroot`, if this is not fixed with this issue, a separate issue should be opened to address this breakage - whether this collateral damage is also a blocker to `1.4` is a separate debate.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 2, 2018, 09:40

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @toscalix]](https://gitlab.com/toscalix) on Aug 2, 2018, 10:28

marked this issue as related to #21

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 3, 2018, 11:17

mentioned in merge request !570

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 3, 2018, 11:18

marked this issue as related to #500

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Aug 8, 2018, 09:27

marked this issue as related to #234

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 10, 2018, 06:21

Note that this comment is relevant: https://gitlab.com/BuildStream/buildstream/issues/413#note_93675276

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @bethwhite]](https://gitlab.com/bethwhite) on Sep 3, 2018, 13:52

Addressed in the workspaces proposal on the mailing list [here][1]

[1]: https://mail.gnome.org/archives/buildstream-list/2018-August/msg00078.html

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Sep 27, 2018, 17:58

Hi, I've been looking into how to implement this, and I'm trying to make sure I have a clear idea of what needs to be done, since there's potential overlaps with #413 and the workspace DX discussion.

AIUI, the course of action is:
* Restructure buildstream shells (both from `bst shell` and the interactive prompt) to use the cached build trees instead of $CACHEDIR/buildstream/build/foo
* Check whether these changes also makes `bst shell --sysroot` take any old sysroot.
* Clean up build $CACHEDIR/buildstream/build/foo after build.

I think there is currently discussion around using the list of open workspaces to indicate which sources
to stage, and also some work being done to make `bst shell` take multiple targets as well.
I think it would make more sense to use the list of targets passed in on the command-line for if specific
 sources need to be staged (e.g. as part of debugging).
Perhaps the most common use-case where this matters (debugging, where you trace into a dependency) would
be handled by automatically staging the cached build trees of the target's direct dependencies, too.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Oct 1, 2018, 17:44

assigned to [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 2, 2018, 13:17

I've taken some time to think about how I'd split up the tasks, since there's the potential for overlap with related discussions on `bst workspace`, and I've come up with the following breakdown:

* Clean up builddir unconditionally
* Make interactive failure shell use the failed artifact
  - Find in the code where interactive failures are handled
  - Make it used the failed build's cached build tree
  - Figure out if I can add any tests for this
* Make bst shell --build work with failed builds
  - Find in code where bst shell --build reaches
  - Make sure it works with failed builds if they're cached
  - Stage the cached build tree in bst shell --build
  - Update tests to reflect the new underlying mechanism
* Make the shells stage other cached build trees
  - Need to resolve discussion on whether it's every open workspace, or as Daniel suggests, direct dependencies of targets instead.
  - Either way, comparatively simple
  - Add new tests to check these are staged
* `bst shell --sysroot` postmortem
  - Check whether it works after these changes and create an issue if it doesn't

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 10, 2018, 15:35

mentioned in commit 446f6c6442df15747406a305f9fb8b5c3e091d9f

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 10, 2018, 15:35

mentioned in commit bcd8c963af82806ae89c84a01e7679be16699c36

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 10, 2018, 15:35

mentioned in commit 2e8bf330a9eeb37fb8f4991731c13d94ce66bb0e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 10, 2018, 15:44

mentioned in merge request !869

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 10, 2018, 16:04

I've created a Merge Request for my work so far, however:

1. It is lacking a resolution to `bst shell --sysroot`.
   From my investigation, the core of the issue seems to be that sandboxes are instantiated with the arg `directory`, which is used to set `Sandbox._root` and `Sandbox.__scratch`.
   
   To be able to use a bare directory as a sysroot, I would need to work out what to do with the `scratch` directory - `scratch` *must* be on the same filesystem as `root`, and the only solution I can come up with is to be able to explicitly set `root` and `scratch` via `Sandbox.__init__`'s args, such that `root` is the bare directory, and `scratch` is a temporary directory created in `root`'s parent directory.

2. It takes no steps towards resolving discussions on whether to stage every open workspace, or whether to stage an element's direct dependencies (which appears to be part of #413 )

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 10, 2018, 16:24

Following discussion in https://irclogs.baserock.org/buildstream/latest.log.html#t2018-10-10T15:06:03, I am going to attempt to see if `scratch` is ultimately necessary when we're using `--sysroot`

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 11, 2018, 15:43

mentioned in commit aebc8b9493c6c4286fbc48fc8d9369869cdd0b78

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 11, 2018, 15:43

mentioned in commit 41966d38791de7cb061ec7c6bc70547a9e155173

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 11, 2018, 15:43

mentioned in commit e77e2755f1bbf400dfa3fa804a44ee53008b42e1

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 11, 2018, 15:43

mentioned in commit 1ab82354165c2ebb84a0c8b6d877a1bf41504b64

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 11, 2018, 15:43

mentioned in commit a7d1e4c8f6a967d1f7477cc0be238c4c86469d8b

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 12, 2018, 13:37

!869 is now as ready for review as it'll ever be.

There are still outstanding topics, but I can't resolve them in that MR without some discussion:
1. How do we catch regressions in the interactive interface?

2. Should this MR concern itself with whether we should be staging more than just the explicitly listed element in `bst shell --build`?

3. When using `bst shell`, either without `--build`, or with `--sysroot`, I am seeing that the working directory is set to a nonexistent directory that only makes sense with `--build`. I don't think this is a regression caused by this MR, should I create an issue for this behaviour or does one already exist? I couldn't find anything while searching 'shell'.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 12, 2018, 17:18

mentioned in commit 9acc0bab3aaf8dfd2652504ada4e5cfa84b62786

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 12, 2018, 17:18

mentioned in commit 3cd09f531197f3d4d6d27141f51ff347a050c4c4

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 12, 2018, 17:18

mentioned in commit 8ac611944e97885bc46ba4b15b1202e4d52fb644

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 12, 2018, 17:18

mentioned in commit 5bbf1ce03cb5a551a5d4f881a196ac2608e4ca8c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 12, 2018, 17:18

mentioned in commit 6e8c09cdb576b09e113457e783d4d7948314ae61

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 15, 2018, 13:52

mentioned in commit 025488c0c149f090ad0b73f11ff85537d6598815

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 15, 2018, 13:52

mentioned in commit 1f12658d34804749bb6ac79b5b8f7b7ff34dcb49

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 15, 2018, 13:52

mentioned in commit fd8d3d252641ee4bf1da35c619b7cf159479fab4

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 15, 2018, 13:52

mentioned in commit c73de1586b27dedbd4e279642ee05e8434a26e25

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 15, 2018, 13:52

mentioned in commit 9827a94f3d6a0f51134cb91d59f1d8559aa2b5b4

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 16, 2018, 14:42

mentioned in commit 6ce414cc1c211fed27a3f2482522c9f8876ea230

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 16, 2018, 14:42

mentioned in commit dca15992e0bb1ab6a37dcdb5f46e56937e8b55fb

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 16, 2018, 14:42

mentioned in commit aadfcbae2d774660904c29645100b50c81e5eedd

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 16, 2018, 14:42

mentioned in commit 8a86f90abd0c5493613b2c5cbd86b6b40b13abf8

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 16, 2018, 14:42

mentioned in commit 9b40fdf97377b87023744519d69325f4e3d9a8fc

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 17, 2018, 12:21

marked the task **The existing `bst shell --sysroot` option is collateral damage here, we should make it more coherent and have it work for any provided sysroot; e.g. it should work using a path to a directory where a `bst checkout` was performed.** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 17, 2018, 12:21

marked the task **Using the same mechanism, `bst shell` should now provide a way to launch a build shell from failed build artifact** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 17, 2018, 12:22

marked the task **Using the same mechanism, `bst shell` should now provide a way to launch a build shell from failed build artifact** as incomplete

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 17, 2018, 12:22

marked the task **Build directories in `~/.cache/buildstream/build` should now be cleaned up unconditionally** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 17, 2018, 12:22

marked the task **When a build fails and there is an interactive prompt, the code should now use the failed artifact in the cache (including the build tree) in order to reconstruct an environment for debugging.** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 17, 2018, 12:22

marked the task **Using the same mechanism, `bst shell` should now provide a way to launch a build shell from failed build artifact** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 18, 2018, 15:26

mentioned in commit d332cee4d50416dc985c7ee4a33f9c0f61eac8d0

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 18, 2018, 15:26

mentioned in commit 2e5f999d207da07e55e9d83981f79ed9c907a0ce

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 18, 2018, 15:26

mentioned in commit aaf72d293344de481976872319d3fd621a133982

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 18, 2018, 15:26

mentioned in commit 996a7351bfa5bfb812fad20bde4a55d250092bf2

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 18, 2018, 15:26

mentioned in commit 725eb473a6ae8277b6b8a3c91805e16cb8c6f783

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 18, 2018, 15:52

mentioned in commit 4059148b4d28e427d6bd439a806cfeb5c88c946d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 18, 2018, 15:52

mentioned in commit 420f4c6703cc4935725aa9163c5f73df14eee2af

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 19, 2018, 12:53

mentioned in commit 95c1956de89ec7d19c5175a35784757c4058989c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 19, 2018, 12:53

mentioned in commit dcf14ebb7e905d0a860bed5581accca92560ce04

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 19, 2018, 12:53

mentioned in commit c5a25f8ef1004bd7bd537fd8c4f93aace72009b1

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 19, 2018, 12:53

mentioned in commit d9fecdb455ff28ae63b2af6d8ec1dc0fb6b4d50a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 19, 2018, 12:53

mentioned in commit 89992cb1cd5244a6226fe483c72ae8860dde8dc2

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 19, 2018, 16:47

mentioned in commit f25349991cf13e70eed03b1d96aeaa0d0becafb5

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 19, 2018, 16:47

mentioned in commit 7faef8626e806c29021ecbf8866938109626ddba

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 19, 2018, 16:47

mentioned in commit eb2ac01e6de7568df1a53b08ef75321359e8521b

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 19, 2018, 16:47

mentioned in commit cff503c8bf5ceef8b3c51c410024ed15f83e463a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 22, 2018, 14:56

mentioned in commit 7b1da53add8bf7c893ac786d08f49a65d9d03547

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 22, 2018, 14:56

mentioned in commit cd957fea381b87d914f6b5c2150572ef1853ed32

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 22, 2018, 14:56

mentioned in commit 6422d2a6d86d592004e1f83721f6ba526ecc866d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 22, 2018, 14:56

mentioned in commit 33cbf675ee0f90e4d54e7d41640d360923c51131

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 22, 2018, 14:56

mentioned in commit aba5890c97d1216d9d74ecbd00c73712c690307f

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 22, 2018, 16:14

mentioned in commit d84b4cff192c08c820a4b43e6a47df2a3e31414a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 22, 2018, 16:14

mentioned in commit 1b3af5c78eff1e867a810a8c148144d483decb45

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 24, 2018, 17:48

mentioned in commit ce576b902dc6722c0bd2e35a9aa17a588d331d57

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 24, 2018, 17:48

mentioned in commit 8a4b9852cce33fac5397bee1b5b4296d77c68cfc

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 24, 2018, 17:48

mentioned in commit 8fea086f537d5e4b950821712a1f2cf2a3a84143

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 24, 2018, 17:48

mentioned in commit 99c8a298a0ccd62f238f38f1470966866f228f6a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 24, 2018, 17:48

mentioned in commit eda04bbb32fab17509a056f801810197bba4de7e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 24, 2018, 17:48

mentioned in commit f4b16a6ffb219e2ca53665461588123746b8d65d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 24, 2018, 17:48

mentioned in commit f51dae5e2addbdc644155691b55fdf3965268c2f

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 26, 2018, 13:44

mentioned in commit 98a4197835b8b57d15191803d80ddd60fc1ca678

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 26, 2018, 13:44

mentioned in commit 75d2726135a3cb0932f0cd93c81849291938b9dc

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 26, 2018, 13:44

mentioned in commit f6881bc394942ba45043c42ba146bd1247fb5f33

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 26, 2018, 13:44

mentioned in commit b7216276a53341a3a9798409a48fceb5ae4ebc31

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 26, 2018, 13:44

mentioned in commit ad7b182ed582e9b0fb4d66c4ec3551f3085c44ae

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 26, 2018, 14:19

mentioned in commit 664a51e1dd7364d847f05241f0d4d4dfb80162cb

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 26, 2018, 14:19

mentioned in commit e74dcf17dabc413244437850e1dcf434c1a55042

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 29, 2018, 14:17

mentioned in commit bdebc8ff77fa1445d8e84a8d8501ec680e76cb33

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 29, 2018, 14:17

mentioned in commit 74408e9b76a591ccb43749915b4ffb5a43d2ab1d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 29, 2018, 14:17

mentioned in commit b6bf3ee786bd70769cd70976150dd8873bda85e6

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 29, 2018, 14:17

mentioned in commit 71805704a0836c8e0e86e98521ff05a147f81055

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 29, 2018, 15:54

mentioned in commit edf214dee7b6fc07d476b69de478980e31dda0f6

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 29, 2018, 15:54

mentioned in commit ebf8f91bd1297df9e3e021500f35309db1366e7e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 29, 2018, 15:54

mentioned in commit 5af9373a38cffbd925d2d5ed65b4f1f48c5de8f8

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 29, 2018, 15:54

mentioned in commit e0cec60f1e5224c9337fbe7a2e9137e477cfdd70

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 29, 2018, 16:30

mentioned in commit 31c84e72c83d4849ba2fab3bb409832c36f521ec

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 29, 2018, 16:30

mentioned in commit 2eb8392e71c655a0c86bbb5945d8b1a31e71797e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 29, 2018, 16:30

mentioned in commit 651f881ec8a24ad2aa47191faaea11a10490bb18

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 29, 2018, 17:07

mentioned in commit 1e2b40471f06232aadbb2c1933dac1d5b0ed9e0c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 29, 2018, 17:07

mentioned in commit 7588b7905d5c3f48375fdef130ebcff899c15674

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 29, 2018, 17:07

mentioned in commit 840fc0db7aad06cf841984f821d8087fab724b94

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 29, 2018, 17:38

mentioned in commit 5d7b9a477587ce019fc8cda28be8c5e35d83b394

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 29, 2018, 17:38

mentioned in commit 1088de96dba4d3a60dec6fc099c72fc7998d5829

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 29, 2018, 17:38

mentioned in commit d79ca68e8c9757ecdc472ff57f974a52a6dc7950

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 30, 2018, 12:53

mentioned in commit 83ee7277287b5bd11dcccc7c9ab0c9601f3f6c31

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 30, 2018, 12:53

mentioned in commit dc097a5e8d803c6617370e3cf3516c8340bfc677

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 30, 2018, 12:53

mentioned in commit ab01ee6d7a41184b35c1d0aa61db9f892998b1e4

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 30, 2018, 12:53

mentioned in commit 9bb63f37d663ec077a43951df4ce63163056c000

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 30, 2018, 15:42

mentioned in commit 09ef8b254342638e828378c2f785963bcf9487da

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 30, 2018, 15:42

mentioned in commit 37afde0a6c6c48bfa18d9f8c495bd4d8bf1cece1

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 30, 2018, 15:42

mentioned in commit 79d1bb7f5f92739ffe0501360b7bdbdc6873a257

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 30, 2018, 15:42

mentioned in commit 825963b5cf7e6f2b116c0ed45300e52d178c691a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Oct 30, 2018, 15:42

mentioned in commit 9b89564f0ac8e8278207358ec3aa95c61ed19d96

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Nov 1, 2018, 13:13

This can be closed, the remaining bits are documented here by the new issue #740, and by this comment on the issue of optionally downloading build trees: https://gitlab.com/BuildStream/buildstream/issues/494#note_113202563

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Nov 1, 2018, 13:13

closed
