### ISSUE TITLE
Cleanup some debris incurred by !519

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#553]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/553)
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 5, 2018, 08:06

## Background

[//]: # (Provide a background or the root/source that justifies this task or action.)

Recently a workspaces example was added to the user manual, in MR !519, which has a few problems that need to be fixed.

## Task description

[//]: # (Short summary of the action to be executed)

* [x] Fix the `.. note::` statement at the beginning of the [workspaces tutorial](http://buildstream.gitlab.io/buildstream/developing/workspaces.html), the link is not rendering and the note box is not showing.
* [x] Fix the cheat invocation of `bst` with appended shell commands separated by `;`, which is just not supported and doesnt even work when building the docs (see the [online tutorial](http://buildstream.gitlab.io/buildstream/developing/workspaces.html#making-code-changes) and notice that the output of the `bst shell` invocation does **not** show the expected *"We can use workspaces"* text).
* [x] Move the stored session html to `doc/source/sessions-stored`, where the sessions are stored

Alternatively to moving the stored session html files to the place where we are storing them, one could attempt to refactor the Makefile and move all the stored session html files to `doc/source/session`, once one has ensured that docs build under every circumstance, and rebuild properly when `BST_FORCE_SESSION_REBUILD` is specified.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 5, 2018, 08:07

[[Gitlab user @phildawson]](https://gitlab.com/phildawson) please take a look at this :)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 5, 2018, 08:28

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 5, 2018, 09:15

mentioned in merge request !603

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 5, 2018, 10:33

mentioned in commit bf0ca2cea25a5537006b3d6376b6037b97eb9e84

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 5, 2018, 11:09

marked the task **Fix the cheat invocation of `bst` with appended shell commands separated by `;`, which is just not supported and doesnt even work when building the docs (see the [online tutorial](http://buildstream.gitlab.io/buildstream/developing/workspaces.html#making-code-changes) and notice that the output of the `bst shell` invocation does **not** show the expected *"We can use workspaces"* text).** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 5, 2018, 11:10

The support for running shell commands in the `bst2html.py` session files is added in !605

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Aug 13, 2018, 10:19

mentioned in merge request !644

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Aug 13, 2018, 12:09

marked the task **Move the stored session html to `doc/source/sessions-stored`, where the sessions are stored** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Aug 13, 2018, 12:10

marked the task **Fix the `.. note::` statement at the beginning of the [workspaces tutorial](http://buildstream.gitlab.io/buildstream/developing/workspaces.html), the link is not rendering and the note box is not showing.** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 25, 2018, 10:00

mentioned in merge request !732

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 25, 2018, 12:41

closed via merge request !732

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 25, 2018, 12:41

mentioned in commit d819fb6477b6c76a2c88cc59aa927fbf6019171e
