### ISSUE TITLE
Release BuildStream on PyPi

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#587]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/587)
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 15, 2018, 17:55

## Background

Current instructions to install BuildStream cloning the git repo, checking out the desired tag and doing a `pip install --user .`. If we release it on PyPi, we can cut down the process to a one-liner `pip install BuildStream`. Upgrading it would similarly be just `pip install --upgrade BuildStream` like any other Python package.

For managing releases, this should also give us an easy way to tell users how to install the latest stable release of BuildStream.

It is worth noting that this WILL NOT solve the distribution story for BuildStream. For that, see https://gitlab.com/BuildStream/buildstream/issues/332. The aim of this task is simply to make the `pip install` process more streamlined.

## Task description

[//]: # (Short summary of the action to be executed)

* [x] Ensure `setup.py` has all the necessary metadata
* [x] Release BuildStream on PyPi
* [ ] ~~Release previous BuildStream versions~~
* [ ] Setup automation to handle releases in future
* [x] Add documentation to the Install guide, this should become the *preferred* installation method instead of `git`.

## Acceptance Criteria

[//]: # (Acceptance criteria should follow the S.M.A.R.T. principle https://en.wikipedia.org/wiki/SMART_criteria )

One is able to install any versions of BuildStream released so far, using `pip`.

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @edbaunton]](https://gitlab.com/edbaunton) on Aug 15, 2018, 19:00

assigned to [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 22, 2018, 00:49

mentioned in commit ab1caac195d1f136c4bb0150cc500ba6d3504a75

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 22, 2018, 00:58

mentioned in merge request !695

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 22, 2018, 09:37

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 22, 2018, 09:37

Added documentation task to the tasklist here.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 22, 2018, 09:38

marked this issue as related to #332

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 22, 2018, 09:38

marked this issue as related to #528

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 22, 2018, 11:08

marked the task **Ensure `setup.py` has all the necessary metadata** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 22, 2018, 11:09

mentioned in commit 65cdd6dce9ad5fbaaef1c94d9dab68c9a89bc457

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 23, 2018, 17:07

So, we have 1.1.7 available on PyPi [[Gitlab user @]](https://gitlab.com/) https://pypi.org/project/BuildStream/. One should be able to simply `pip install BuildStream`, assuming all the host requirements are met. If not, the install process should fail in the same way it would fail when trying to install BuildStream from a git checkout.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 23, 2018, 23:31

mentioned in commit dd8fa80c811305d83ec3f5adc8350518ac16936e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 23, 2018, 23:32

mentioned in commit 93671320562f327291638765616336f83595c3f3

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 23, 2018, 23:35

mentioned in commit 183c268aba76f286fb7651453215cee9c6b6844a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 23, 2018, 23:36

marked the task **Release BuildStream on PyPi** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 23, 2018, 23:44

mentioned in commit b97c6dedf787ffc6cba7f7dd34f895b8db524487

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 23, 2018, 23:45

mentioned in merge request !717

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 24, 2018, 11:20

mentioned in commit 5bd6f7627ae0826e65296565ee04ac5b3c7c2419

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 24, 2018, 12:22

mentioned in commit 923bfaeca0d90e335b6cb24a2297d3c0e42275b3

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 24, 2018, 19:20

marked the task **Add documentation to the Install guide, this should become the *preferred* installation method instead of `git`.** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 24, 2018, 22:18

mentioned in commit efadd7bb0896bc222c86ce087215e34a6c0eb233

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 24, 2018, 22:20

mentioned in merge request !731

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 24, 2018, 22:22

mentioned in commit 2a29cd6208e9a757734184e85ea8531a257e0ae5

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 30, 2018, 22:26

[[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) Initially one of the things that I had listed as a todo item was to release previous versions of BuildStream on PyPI. I am now trying to look into how to do that and it seems like we will have to, at least, apply the patch from !695. Ideally, we'd also apply !718.

Doing so will require changing `setup.py` script for the previously released tags. Since the patches do not apply cleanly to these tags (which is kind of expected), doing so will require some manual steps too. Since this will _taint_ the original tarballs, it feels somewhat wrong to do it. So, I was wondering if we should do it?

The downside of not doing this is that people will not be able to install any versions of BuildStream < 1.1.7.

There is also a middle ground - we can choose to release only a selected group of tags on PyPI. For example, `1.0.0` and `1.1.0`.

What would you suggest doing?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @sstriker]](https://gitlab.com/sstriker) on Sep 1, 2018, 06:19

Out of curiosity, why do we [want to] backfill previous versions to pypi?

Cheers,

Sander

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Sep 1, 2018, 09:07

> [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) Initially one of the things that I had listed as a todo item was to release previous versions of BuildStream on PyPI

I don't think this really adds value, and any implementation of it requires some kind of hack, lets just not do this.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Sep 4, 2018, 11:49

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Sep 4, 2018, 11:57

[[Gitlab user @sstriker]](https://gitlab.com/sstriker) [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) The only reason we might want older releases on PyPI is for the sake of completeness. Since we can't see any real use-case for needing to install older versions via PyPI, I think it is safe to skip that step. We can always come back to this if needed.

I have crossed off this item from the todo list and now the only thing left to do is to automate the publishing step. Since we already talking about that in !731, let's continue that discussion on the merge request. After !731 lands, we should be able to close this issue.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Sep 14, 2018, 17:06

mentioned in commit f46afb8e7df7ce2d9f646aa0b809600eba7fc6a0

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Oct 16, 2018, 22:01

mentioned in commit 9c31f086dc53da1962ff92c36000b83bc479d65d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Nov 28, 2018, 16:36

mentioned in commit 6be2f3e488f5cbb922e02770ccd27b6d9822f162

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Nov 28, 2018, 16:47

mentioned in commit db537ab8f3191f8f8181feafda5a6716dd93ce22

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Nov 28, 2018, 16:57

mentioned in commit 865d5f4357a5041163d4cbc0c4b359b280edae5a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @abderrahimk]](https://gitlab.com/abderrahimk) on May 9, 2019, 10:27

I just wanted to mention that bst 1.2.4 is the last version on pypi, 1.2.5 and 1.2.6 weren't uploaded.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Jun 23, 2019, 17:30

[[Gitlab user @abderrahimk]](https://gitlab.com/abderrahimk) sorry about that. I completely forgot to upload the last couple of releases.

I have now uploded versions 1.2.5 - 1.2.7.

I will close this issue now. The only thing else I'd like to do at some point is automate the releases but that can come later.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Jun 23, 2019, 17:30

closed
