### ISSUE TITLE
Expose DownloadableFileSource to external plugin authors

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#610]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/610)
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Aug 28, 2018, 13:43

## Background

freedesktop-sdk have a plugin that uses the DownloadableFileSource. Since it's not available on the same level as ScriptElement, they have to use a fairly nasty workaround to access it. (https://gitlab.com/BuildStream/bst-external/merge_requests/48/diffs#fb08aba75dfacbf1cd0e50f0b80858984ee6f36c_0_11)

## Task description

[//]: # (Short summary of the action to be executed)

* [ ] Move _downloadablefilesource.py to the same level as scriptelement.py
* [ ] Add it to buildstream's __init__.py
* [ ] Update all of buildstream's sources to find it from its new location

## Acceptance Criteria

[//]: A plugin that is not part of the buildstream main repo can import DownloadableFileSource using `from buildstream import ...`

**note**: Since freedesktop-sdk use buildstream from the bst-1.2 branch, This will have to be backported as well as merged to master.

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Aug 28, 2018, 13:44

mentioned in merge request bst-external!48

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Aug 28, 2018, 13:49

created branch [`610-expose-downloadablefilesource-to-external-plugin-authors`](https://gitlab.com/BuildStream/buildstream/compare/master...610-expose-downloadablefilesource-to-external-plugin-authors)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Aug 28, 2018, 14:31

mentioned in merge request !743

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Aug 28, 2018, 16:14

assigned to [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on May 8, 2020, 17:47

mentioned in merge request !1908

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on May 11, 2020, 08:26

!1908 to address this

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on May 11, 2020, 09:57

closed via merge request !1908

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on May 11, 2020, 09:57

mentioned in commit 4adcb0583375bd533c58b5cd9cf827f62659cc08
