### ISSUE TITLE
Warn users when using a URL without an alias

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#612]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/612)
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Aug 29, 2018, 15:22

## Background

[//]: # (Provide a background or the root/source that justifies this task or action.)

The use of aliases within URLs is strongly advised within BuildStream. It would be nice for this to be a warning provided to the user. This warning could [configurable](https://buildstream.gitlab.io/buildstream/format_project.html#configurable-warnings) as fatal in a project for maintainers who wish to catch this sort of thing in CI. 

## Task description

[//]: # (Short summary of the action to be executed)

* [ ] Detect when sources use URLs without aliases
* [ ] Collect URLs and provenances
* [ ] Provide a warning summarising these instances 
* [ ] Revamp the changes from !627 to have warnings raised as exceptions by Context instead of Plugin. (As this summary of URLs will not be associated with a single plugin)

## Acceptance Criteria

[//]: # (Acceptance criteria should follow the S.M.A.R.T. principle https://en.wikipedia.org/wiki/SMART_criteria )

A user shall be provided with a warning when using URLs without aliases. These warnings shall be optionally fatal.

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Aug 29, 2018, 15:23

marked this issue as related to #597

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @toscalix]](https://gitlab.com/toscalix) on Aug 29, 2018, 15:37

marked this issue as related to #613

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 29, 2018, 21:12

Note: The SourceFetcher API introduced with source mirroring feature needs to be examined quickly to ensure that we do not break the invariant of always loading all the user configuration at `Plugin.configure()` time and validating at `Plugin.preflight()` at the latest (if not already validated in `Plugin.configure()`).

See these comments for background:
* https://gitlab.com/BuildStream/buildstream/merge_requests/700#note_96616804
* https://gitlab.com/BuildStream/buildstream/merge_requests/700#note_96618970

[[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw), it would be good to have a review of this and at least figure out a strategy this week, we need to know if and how we need to break the `SourceFetcher()` API contract before releasing `1.2`

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 30, 2018, 08:06

I've been looking at this a bit more deeply this afternoon.

So far I think one plausible solution is to change the API contract so that:

> `Source.mark_download_url()` **must** be called in `Plugin.configure()` for **every url in the configuration**

This would unfortunately require specific ordering of the calls, such that we require that the plugin call `Source.mark_download_url()` in the same order in which those urls will be used by `SourceFetchers`.

This is all complicated by the fact that a `Source` still requires that you use `Source.mark_download_url()` (or `Source.translate_url()`) even if you are going to use `SourceFetcher.mark_download_url()`, for the sake of tracking which does not use any fetchers.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Aug 30, 2018, 10:47

My thoughts of a solution on this were to wrap configure within something like this.

```
def __do_configure(self):
    self._configuring = True
    self.configure()
    self._configuring = False
```

And assert within mark_download_url() as such
`assert self._configuring, "mark_download_url() must be called from within configure()"`

This does not address the issue of `SourceFetchers` and `Sources` being instantiated during the fetch of another `Source`. Ideally, all `Sources` and `SourceFetchers` will be instantiated prior to or during `preflight`

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 30, 2018, 12:44

marked this issue as related to #620
