### ISSUE TITLE
Remote-execution client flow optimisation (technical debt)

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#628]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/628)
In GitLab by [[Gitlab user @martinblanchard]](https://gitlab.com/martinblanchard) on Sep 5, 2018, 16:13

## Background

Initial remote-execution implementation (BuildStream/buildstream!626) does not query the ``ActionCache`` itself but systematically forge and send a new ``ExecuteRequest`` (including full source tree upload), relying on the server to hit the cache by setting ``skip_cache_lookup`` to ``False``.

The expected client execution flow is documented in the [Overview section of the REAPI design document](https://docs.google.com/document/d/1AaGk7fOPByEvpAbqeXIyE8HX_A3_axxNnvroblTZ_6s/edit#heading=h.dc83hqun0etm).

Hit the ``ActionCache`` directly from the client would, first, be faster, and second, allow us to not engage a costly source push if the ``ActionResult`` is already cached.

## Task description

Implementation should include:

* [ ] Call ``GetActionResult()`` as a first server request.
* [ ] Jump to artifact pulling if the ``ActionResult`` is in cache.
* [ ] Continue to source pushing and ``ExecuteRequest`` forging if not.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @martinblanchard]](https://gitlab.com/martinblanchard) on Sep 5, 2018, 16:15

changed title from **Remote-execution {-execution-} flow optimisation (technical debt)** to **Remote-execution {+client+} flow optimisation (technical debt)**

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @martinblanchard]](https://gitlab.com/martinblanchard) on Sep 5, 2018, 16:16

mentioned in merge request !626

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @martinblanchard]](https://gitlab.com/martinblanchard) on Sep 5, 2018, 16:17

[Initial discussion](https://gitlab.com/BuildStream/buildstream/merge_requests/626#note_99042912) from BuildStream/buildstream!626.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Nov 16, 2018, 13:22

assigned to [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Nov 30, 2018, 17:23

mentioned in commit 41088dbbac27b0b407d00694f809f770247cc0e2

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Nov 30, 2018, 17:29

mentioned in merge request !982

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Dec 4, 2018, 11:06

mentioned in commit 0be62ea03e71e580488264551f704a178ae1af46

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Dec 4, 2018, 14:00

mentioned in commit 73362448289e55106c9700a716f638b476ab8a76

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Dec 5, 2018, 10:27

mentioned in commit f45fed59fa9d5c64c2708bcbf196787e19afed70

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Dec 5, 2018, 10:27

mentioned in commit b0d60833b80c9f095da38bbe9f0d39ade694d850

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Dec 5, 2018, 11:18

mentioned in commit 03ab479e625d6765184490ec93d6e86cbe9f7ccc

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Dec 5, 2018, 11:18

mentioned in commit b1ed882e9b3595a9bc9ccf724feed87b8e8f6d55

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Dec 5, 2018, 12:43

mentioned in commit 3cee0ec5ea5df23089c5da5ad3b53393a4d27ba5

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Dec 5, 2018, 12:43

mentioned in commit 744af45bd872e6606a69084e7da96c73b9b5e40d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Dec 5, 2018, 12:43

mentioned in commit bf26a2b2692ac74449deb6e0232a8d42ed795fd6

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Dec 5, 2018, 14:53

mentioned in commit f1741e26452577f65b5f0a5d2d9288ba36ffcbfc

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Dec 5, 2018, 14:53

mentioned in commit dcefa1be60d58cd517c503594e67ab30a13fbd95

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Dec 5, 2018, 14:53

mentioned in commit 69ef3e5e8885443c12abc4a53e23bb0d308fbedb

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Dec 5, 2018, 14:56

mentioned in commit b95f997459a0db61286b30319ca74f0f8cd99a2e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Dec 5, 2018, 14:56

mentioned in commit 33a95c31f600315b5cf6f9688281627886b58235

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Dec 5, 2018, 14:56

mentioned in commit b510474ca2ad6765a6d6b80afdbe49cde29b0e28

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Dec 5, 2018, 15:35

mentioned in commit 9d77351f0b05f6b37b4235742ac3a0ca2d6feb93

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Dec 5, 2018, 15:35

mentioned in commit 3641b6f6c24fc8d0965da5920a77413d36a32e17

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Dec 5, 2018, 15:35

mentioned in commit 4a56bf2a3a3c2b332a5e832b1f58c027a6608d07

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Dec 5, 2018, 16:36

closed via merge request !982

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Dec 5, 2018, 16:36

mentioned in commit a53d6d1f81913d639175cbd503d9d71ec7133a4e
