### ISSUE TITLE
Remote-execution user configuration (technical debt)

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#631]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/631)
In GitLab by [[Gitlab user @martinblanchard]](https://gitlab.com/martinblanchard) on Sep 6, 2018, 15:11

## Background

Initial remote-execution implementation (BuildStream/buildstream!626) only support project level configuration. As [discussed on the mailing list](https://mail.gnome.org/archives/buildstream-list/2018-August/msg00073.html), the remote build server one might want to use for a particular build should be a user-level configuration and project level configuration should be a convenient way of defining a default for people working around a project.

## Task description

[//]: # (Short summary of the action to be executed)

* [ ] Add user-level configuration entries.
* [ ] Add CLI options for specifying and/or overwriting configuration.
* [ ] Change element's logic so that remote execution service to use is determine by merging user and project configurations.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @martinblanchard]](https://gitlab.com/martinblanchard) on Sep 6, 2018, 15:13

mentioned in merge request !626

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @martinblanchard]](https://gitlab.com/martinblanchard) on Sep 7, 2018, 14:50

As mentioned in the initial remote-execution implementation review [here](https://gitlab.com/BuildStream/buildstream/merge_requests/626#note_99655776), we should also consider adding CLI options to `bst`.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @martinblanchard]](https://gitlab.com/martinblanchard) on Oct 2, 2018, 12:47

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @martinblanchard]](https://gitlab.com/martinblanchard) on Oct 2, 2018, 13:04

Below is a list of configuration elements we **may** want to expose in the CLI, to be discussed:
* `remote-executor`: URL for the remote-execution endpoint.
* `instance-name`: name of the instance targeted on the remote server.
* `priority`: execution priority for the build job.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Nov 22, 2018, 18:09

Might make sense to implement this together with https://gitlab.com/BuildStream/buildstream/issues/780

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @martinblanchard]](https://gitlab.com/martinblanchard) on Nov 30, 2018, 10:45

mentioned in merge request !952

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Dec 20, 2018, 13:27

mentioned in commit c3ac974c3606d5f35d9f3cf7c012a0c1b6fa2da7

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Dec 20, 2018, 14:14

mentioned in commit a11c2ef8597de78a85e7aa0ea7e6a95f40616188

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Jan 2, 2019, 10:12

mentioned in commit 8f0e52314769beb0d7b8cf461950996b4812b09c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Jan 2, 2019, 11:41

mentioned in merge request !1030

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Jan 2, 2019, 11:51

I have been looking at adding CLI option. I am afraid it would become to complicated to allow users to change part of the remote execution configuration.

It does not make much sense in the long term for setting URL without setting keys and certificates. Unencrypted connections are mostly for testing. So that means we need to set 4 options at once. It is easier to use a configuration file for that.

It is also not just one URL, but 3.

We can get into complex situations where we have overrides for some projects, not for some others. What would be the meaning of the command line option? Is that higher priority than an override from a user configuration? Or lower. What if we want from the command line, override just one project. Again, it is easier to just change the user configuration.

We could however have a kill switch similar to !950 but for remote execution.

Or maybe we should wait for the command line options until users have interesting use cases.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Jan 2, 2019, 11:52

a02fc6963b977da825a69dac388bc8652fdf5634 implements a kill switch, user/project config selection.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Jan 2, 2019, 11:53

assigned to [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Jan 3, 2019, 12:32

mentioned in commit 035cf50137a13f02733e9a07b416fa916798a214

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Jan 4, 2019, 12:32

mentioned in commit 890e6ba3ee016db99acf0df044a032fa182e5b97

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Jan 4, 2019, 14:15

mentioned in commit 79ef60becfbbb7e9189b69219f6ccdba2612dbdd

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Jan 8, 2019, 11:30

mentioned in commit bff37b67224677d19e0704edea8c821befb0e126

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Jan 9, 2019, 10:45

mentioned in commit 605f8d11dc830b7d3243735d1f340e16364c8d8c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Jan 9, 2019, 12:59

closed via merge request !1030
