### ISSUE TITLE
RFE: Allow easy way of building all elements

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#640]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/640)
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Sep 10, 2018, 13:37

## Background

When managing a BuildStream project, it is often desired to validate that all elements under the given project are building at all times. This is simple to automate when there is a single or a handful of leaf elements but becomes cumbersome to do it outside BuildStream as the number of elements begin to increase.

If there was a way to tell BuildStream to build all elements, something like `bst build --all`, that would solve this issue.

As part of this, we may need a mechanism to let BuildStream identify which files are bst elements (probably leveraging file extensions or similar).

## Task description

[//]: # (Short summary of the action to be executed)

*- Update by Phillip Smyth on 12th December 2018:*

* [ ] Introduce Default elements to `bst build`
* [ ] Add functionality for building the default element and all elements
* [ ] Introduce tests to cover the new functionality

*- End update by Phillip Smyth on 12th December 2018:*

## Acceptance Criteria

[//]: # (Acceptance criteria should follow the S.M.A.R.T. principle https://en.wikipedia.org/wiki/SMART_criteria )

*- Update by Phillip Smyth on 12th December 2018:*

~~One is able to build all elements in a project, using a single command.~~

This is now going to be default functionality, rather than using a command or flag

*- End update by Phillip Smyth on 12th December 2018:*

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Sep 19, 2018, 14:08

I'd follow what similar tools do and call it 'world'

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @sstriker]](https://gitlab.com/sstriker) on Sep 19, 2018, 17:13

'all' as a very common term in the build space.  'make all' as an example.
:all is a qualifier in bazel.  build=all in other places.  I don't think
that world is a better term here.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Sep 19, 2018, 17:21

There's also another caveat to consider, which I somehow overlooked when I wrote this issue - We already have `build --all`:

```
root[[Gitlab user @2540fc22af03]](https://gitlab.com/2540fc22af03):/src# bst build --help
...
Options:
  --all                        Build elements that would not be needed for the
                               current build plan
...
```

So, I guess we either need to change the meaning of `--all` (are people actually using `--all` the way it currently works?) or have a different option for this.

If we end up with both `--all` AND something like `--world`, that may not be very intuitive to users.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @knownexus]](https://gitlab.com/knownexus) on Oct 22, 2018, 14:33

Hey [[Gitlab user @cs]](https://gitlab.com/cs)\-shadow, What do you want your proposed version of `--all` to do that the current one doesn't?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Oct 22, 2018, 14:40

The proposed `--world` (or whatever we want to call it) would build all elements in the project, not just all elements in the plan.

Imagine a project that is structured like this.

```
    base.bst
       |
   libfoo.bst
       |
     / |  \
   /   |    \
app1  app2  app3
```

I would like some way of building all apps in a single command. For a small project, listing all the apps works but that is not very practical when the number of apps is in thousands.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @knownexus]](https://gitlab.com/knownexus) on Oct 22, 2018, 14:58

An option for this could be:
either some named flag e.g. --world
or just an empty `bst build` command 

Where it walks through every directory inside the `element-path` and attempts to build all files it finds (Possibly ignoring files beginning with a `.` e.g. `._pipeline.py.swp` to avoid editor files

This could potentially break in the situation where we have a project inside of another project, but I Don't think this is likely or supported anyway (I might be wrong)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Oct 22, 2018, 15:24

[[Gitlab user @knownexus]](https://gitlab.com/knownexus) something like that could work.

At some point, we also discussed having the possibility of specifying an extension, or a list of extensions, for elements in that project. To be honest, I don't know why that list has to be anything more than `.bst` but since BuildStream is not opinionated about names of elements, I don't think we should make any assumptions.

But, if projects are allowed to restrict what the elements can be named, then we can just walk the `element-path` directory looking for files with those extensions.

While walking the tree, if we find a directory with a `project.conf`, I think we should skip that directory, maybe after printing some warning message.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @knownexus]](https://gitlab.com/knownexus) on Nov 1, 2018, 10:37

assigned to [[Gitlab user @knownexus]](https://gitlab.com/knownexus)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @knownexus]](https://gitlab.com/knownexus) on Nov 2, 2018, 18:01

mentioned in merge request !926

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @knownexus]](https://gitlab.com/knownexus) on Dec 5, 2018, 15:21

mentioned in merge request !990

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @knownexus]](https://gitlab.com/knownexus) on Dec 12, 2018, 10:56

The current plan for this is to have `bst build` default to building all elements in a project, but to
fail if there are incompatibilities.
Alternatively, you can set a default target for `bst build` which will be
built instead of everything

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @knownexus]](https://gitlab.com/knownexus) on Dec 12, 2018, 11:14

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @knownexus]](https://gitlab.com/knownexus) on Dec 12, 2018, 11:15

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @knownexus]](https://gitlab.com/knownexus) on Dec 12, 2018, 11:16

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @knownexus]](https://gitlab.com/knownexus) on Dec 12, 2018, 11:17

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @knownexus]](https://gitlab.com/knownexus) on Dec 13, 2018, 14:18

mentioned in merge request !925

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jan 4, 2019, 06:59

assigned to [[Gitlab user @juergbi]](https://gitlab.com/juergbi)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jan 4, 2019, 06:59

unassigned [[Gitlab user @knownexus]](https://gitlab.com/knownexus)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jan 24, 2019, 15:15

> The current plan for this is to have `bst build` default to building all elements in a project, but to
> fail if there are incompatibilities.
> Alternatively, you can set a default target for `bst build` which will be
> built instead of everything

This is now available in master. Please verify that this solves this issue.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Feb 9, 2019, 13:55

unassigned [[Gitlab user @juergbi]](https://gitlab.com/juergbi)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on May 8, 2019, 12:19

Sorry for the dealy in responding here, this one slipped through the cracks.

I can confirm that this indeed solves the original issue.

Thanks all!

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on May 8, 2019, 12:19

closed
