### ISSUE TITLE
Error out if `%{max-jobs}` is substituted in `Element.node_subst_member()`

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#641]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/641)
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Sep 10, 2018, 20:00

## Background

Mentioning `%{max-jobs}` directly in build commands causes the generated cache keys to be different depending on the host environment and any dynamic resolution of `max-jobs`, which is why it should always be used with an `environment-nocache` env var instead.

Had to fix this recently in [gnome-build-meta](https://gitlab.gnome.org/GNOME/gnome-build-meta/merge_requests/77)

## Task description

Make sure that `Element.node_subst_member()` raises an informative error if it ends up substituting the special, protected `max-jobs` variable.

* [ ] Add the new LoadError and LoadErrorReason
* [ ] Raise the error in the correct condition
* [ ] Add a test case asserting we fail in the way we expect, if `max-jobs` is specified in build commands

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tacgomes]](https://gitlab.com/tacgomes) on Sep 11, 2018, 11:01

[[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) do we really want to enforce this in BuildStream? An user should have the freedom to use max-jobs as he wishes, despite the consequences.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Sep 13, 2018, 14:11

[[Gitlab user @tacgomes]](https://gitlab.com/tacgomes); The `gnome-build-meta` project accidentally used `max-jobs` in build instructions directly.

The result is that the cache keys are different on machines with different numbers of cores. People in `#release-team` mentioned that they were experiencing apparently random WebKit rebuilds as a result.

I think this is a pretty bad consequence, and one we could have saved the user from, right ?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Mar 6, 2019, 09:46

This is a duplicate of #287, and has been long since fixed in master and `1.2.x`

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Mar 6, 2019, 09:46

marked this issue as a duplicate of #287

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Mar 6, 2019, 09:46

closed
