### ISSUE TITLE
Dependencies for a pure artifact server are undocumented

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#648]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/648)
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Sep 12, 2018, 11:49

## Background

[//]: # (Provide a background or the root/source that justifies this task or action.)

We document an alternate install path for artifact-server-only BuildStream [here](https://buildstream.gitlab.io/buildstream/install_artifacts.html), but we do not list the dependencies of the server.

## Task description

[//]: # (Short summary of the action to be executed)

We should document the dependencies of the artifact server, since they will differ from main BuildStream. In particular, I believe neither fuse nor bubblewrap are required.

* [ ] Figure out the actual dependencies of the artifact server
* [ ] Ensure that the installation path works without unnecessary dependencies
* [ ] Document the new list of dependencies
* [ ] Update the relevant docker image

## Acceptance Criteria

[//]: # (Acceptance criteria should follow the S.M.A.R.T. principle https://en.wikipedia.org/wiki/SMART_criteria )

We should have a clearly documented set of dependencies for the artifact server.

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Sep 12, 2018, 12:03

Interestingly, running the artifact server seems to load the `fuse.py` file, which will fail if libfuse is not available. This might be a bug.
