### ISSUE TITLE
Setup our own x86_64 runners

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#657]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/657)
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Sep 17, 2018, 16:02

## Background

We have been using the baserock runners for a while (for free), better to use our own to have more control over them

## Task description

* [x] Get the hardware
* [x] Setup gitlab-runner on them
* [x] Document setup somewhere
* [x] Disable baserock runners

## Acceptance Criteria
* Baserock runners are disabled and everything keeps working

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Sep 17, 2018, 16:02

marked the task **Get the hardware** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Sep 17, 2018, 16:02

marked the task **Setup gitlab-runner on them** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Sep 17, 2018, 16:06

I've spent some time with [[Gitlab user @tacgomes]](https://gitlab.com/tacgomes) today.

This runners provided by Codethink are configured as group runners of the Buildstream group (so any repo in BuildStream group can use them). The runners are:

- codethink-x86_64-1 (ip 78.40.148.171)(tags: codethink,x86_64)
- codethink-x86_64-2 (ip 78.40.148.183)(tags: codethink,x86_64)

[[Gitlab user @tacgomes]](https://gitlab.com/tacgomes) maybe you want to put this info in a wiki somewhere?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Sep 17, 2018, 16:06

marked the task **Document setup somewhere** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Sep 17, 2018, 16:07

marked this issue as related to #370

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Sep 17, 2018, 16:08

assigned to [[Gitlab user @tacgomes]](https://gitlab.com/tacgomes)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Sep 17, 2018, 16:28

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @toscalix]](https://gitlab.com/toscalix) on Sep 18, 2018, 11:38

* We know now the Codethink machines we have access to.
* I am working on getting to know the process to assign the current CI runners use by BuildStream to the BuildStream project.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tacgomes]](https://gitlab.com/tacgomes) on Sep 19, 2018, 09:31

A BuildStream group account was created on the Digital Ocean could platform. The members of the account at the moment of this writing are [[Gitlab user @tacgomes]](https://gitlab.com/tacgomes) and [[Gitlab user @jjardon]](https://gitlab.com/jjardon).

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tacgomes]](https://gitlab.com/tacgomes) on Sep 19, 2018, 09:55

Current infrastructure used by BuildStream:

- Digital Ocean 1GB Standard droplet to act as bastion
- Several Digital Ocean 8GB Standard droplets created on demand
- bst-artifacts-gnome.codethink.co.uk Virtual Machine (unused)
- ostree-gnome.codethink.co.uk Virtual Machine (unused)
- 8 Moonshot Sleds

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @toscalix]](https://gitlab.com/toscalix) on Sep 19, 2018, 15:01

moved to BuildStream/nosoftware/alignment#38

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tacgomes]](https://gitlab.com/tacgomes) on Sep 19, 2018, 18:36

marked the task **Disable baserock runners** as completed
