### ISSUE TITLE
Retire `source-bundle` command

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#672]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/672)
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Sep 22, 2018, 21:17

## Background

As discussed in [this thread](https://mail.gnome.org/archives/buildstream-list/2018-September/msg00064.html) the `source-bundle` command is "a bit of an ugly, underused, undertested beast". Since it is not too often used and its functionality is very narrow, it would make sense to fold it into `source-checkout` as an option and get rid of `source-bundle` command.

## Task description

[//]: # (Short summary of the action to be executed)

* [x] Add `bst source-checkout` command - !820
* [ ] Add `--tar` option to `bst source-checkout`
* [ ] Add an option to `bst source-checkout` to generate a build script in addition to the sources
* [ ] Remove `source-bundle` command

## Acceptance Criteria

[//]: # (Acceptance criteria should follow the S.M.A.R.T. principle https://en.wikipedia.org/wiki/SMART_criteria )

- `bst source-bundle` command is removed from the CLI, but its functionality is supported by `bst source-checkout`.  

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Sep 22, 2018, 21:39

changed title from **Retire {-source-checkout sub-}command** to **Retire {+`source-checkout` +}command**

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Sep 22, 2018, 21:39

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Sep 22, 2018, 21:48

changed title from **Retire `source-{-checkout-}` command** to **Retire `source-{+bundle+}` command**

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Sep 22, 2018, 21:48

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Oct 11, 2018, 14:53

Are we okay with removing the *source-bundle* command completely without continuing the support it but keeping it deprecated ?

Strictly speaking this is an API break, which we never ever want to do, especially never again after `1.4`. Seeing as this command is not used very much, I think it would be acceptable to lump this in with the workspace related API breaks we intend to introduce; but we should be careful to document these breaks somewhere front and center.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Oct 11, 2018, 23:15

OK - [[Gitlab user @willsalmon]](https://gitlab.com/willsalmon) and [[Gitlab user @tpollard]](https://gitlab.com/tpollard) can we include this one in the overall workspace UX changes plan pls?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Oct 12, 2018, 10:15

[[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) I guess so, but it's not strictly workspace related. Making sure they land together would be plausible though?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Oct 12, 2018, 11:59

I mentioned that we could lump this in with the intentional API breaks related to workspaces, such that they are the only API breaks that ever happen and we advertise them all together with `1.4` and a clear message that this will not happen again.

That doesn't make this work related to the workspace refactorings otherwise.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Nov 13, 2018, 18:32

Mark as blocker as this is one of the features we want to try to have for 1.4: https://mail.gnome.org/archives/buildstream-list/2018-October/msg00080.html

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Nov 19, 2018, 09:48

mentioned in commit 6459386302dc77600d65833730181ea45997f666

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Nov 19, 2018, 10:18

mentioned in commit 2a9577e704aae22538a97ce8e55eede48d42b26d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Nov 19, 2018, 10:51

mentioned in commit 54a9ce54ccd28da7313116ebdbb5f849d81a462e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Nov 19, 2018, 11:24

mentioned in commit 0f571f59ca5affebe2165804e3a2026e5c4ef6bc

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Nov 19, 2018, 11:24

mentioned in commit 712f7dc9d1532a3ec481728f3c64b744dc1db6e7

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Nov 19, 2018, 11:24

mentioned in commit bd1b4fcd0fb0e86c4a0bc20dcf826c5674c3dd13

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Nov 19, 2018, 11:24

mentioned in commit 92f21853b7a5bc028df1eb718e4785dfc3f466da

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Nov 19, 2018, 12:55

mentioned in commit 896bb4601176e7ce7de1039fda85960ac4867943

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Nov 19, 2018, 16:20

mentioned in commit 2b353ea5ba31da0ab02fd90e957ffd0e261d1b9a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Nov 19, 2018, 16:20

mentioned in commit 7f75326cf9bee63ec52f0d216bfa5702a0482abd

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Nov 19, 2018, 16:20

mentioned in commit 9021316d3792ec1d3fce3003ff48978db985379f

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Nov 19, 2018, 16:20

mentioned in commit b157354f920d7c3fa5a1c1d054ed611f2119c69b

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @chiaratolentino]](https://gitlab.com/chiaratolentino) on Nov 19, 2018, 16:31

marked the task **Add `bst source-checkout` command - !820** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Nov 19, 2018, 16:41

mentioned in commit 355ddf289024c0e5278c35221a0261ecb25087e1

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Nov 19, 2018, 16:41

mentioned in commit 7735b3c446822af645bff69bd0b9216eb1e90a6a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Nov 19, 2018, 16:41

mentioned in commit 04a5b52000f8c26049180da5c0b4d4a92502a088

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Nov 19, 2018, 16:41

mentioned in commit ccb2d17c3505fb16f9dd1a3c5ca95d40fadc5929

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Nov 19, 2018, 16:43

mentioned in merge request !959

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Nov 28, 2018, 09:50

mentioned in commit 325ac03082cb499f0e9b6585888a29647cfe890a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Nov 28, 2018, 14:16

mentioned in commit 86ddbe55c93f8ea5a7a3ebbab522a9524fd361ae

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Nov 30, 2018, 11:50

mentioned in commit 3f63a61403f426e2949f93ba8bee47ebf0b667cb

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Nov 30, 2018, 11:50

mentioned in commit 944bee76d45ada5b7a9d77399002e92873790a4c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Nov 30, 2018, 11:50

mentioned in commit b41670b9cd3fa79f10dd7d8934165dd9a31f6700

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Nov 30, 2018, 11:50

mentioned in commit 0cefde483c49aaca893742694e2c6a0fbaed5998

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Nov 30, 2018, 13:27

mentioned in commit 7c3283e5b8d0304011e620f64b63f45383c1e511

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Nov 30, 2018, 13:27

mentioned in commit 41a84a6f45cd56d81caf6797351a55ee7da11cdb

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Nov 30, 2018, 13:27

mentioned in commit 6d50a2338132bdea0d9ca8563f5eeab626c19055

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Nov 30, 2018, 13:27

mentioned in commit f143bfb8ca1463dec42bc441fddc584fc4260850

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 3, 2018, 10:16

mentioned in commit 10f0413284eff3a7d839a2be15ecb68c85f26593

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 3, 2018, 10:16

mentioned in commit 590658fe75450d6a0434404301a8c423816a9a1e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 3, 2018, 10:16

mentioned in commit 3f3f718f3f11a3eb75802dfe879270a973d0c184

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 3, 2018, 13:17

mentioned in commit 0978ccb3cf9926a4dbda81fc7f4075b524b3ec1b

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 3, 2018, 13:17

mentioned in commit 7e0f6c532b4a988b7a0648569df83651f9e706af

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 3, 2018, 13:17

mentioned in commit adcd81bdaee8a5016d0c2bf132856f2e23bd269d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Dec 3, 2018, 15:56

mentioned in commit 15b74c13183b0797939eb95e01c7d097edb2bef7

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 4, 2018, 11:39

mentioned in commit e0aea036a841cd95c88a8aa883630b8d1d3c5af8

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 4, 2018, 11:39

mentioned in commit 24dbbb089d348bfeabaf77cd461d4cce4111ba10

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 4, 2018, 13:32

mentioned in commit 772b106fa0e3168e11abb30890f757acb492e0cc

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 4, 2018, 13:32

mentioned in commit 68bcb08e5a63402b88db2d8f949327e5f1c5156b

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 4, 2018, 13:32

mentioned in commit 292c76c6024bdb325df9103f0d1d8c5810f6c2e5

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 4, 2018, 13:32

mentioned in commit d8631291aa1a45efe98dfc21b7d48e7509d9076e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 5, 2018, 11:52

mentioned in commit 02c112073a25a316bd002f8c1b15682c4fee5c47

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 5, 2018, 11:52

mentioned in commit ba8958c7286660dcfce1e1a8391cdf65dde151ce

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 5, 2018, 13:40

mentioned in commit 267c138d248a062cdaedeac127319070f1a1cc3f

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 5, 2018, 13:40

mentioned in commit 1d5197dd19e118b6f56dbcfea642ecb2547c4426

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Dec 5, 2018, 17:19

mentioned in commit c3eb6006bbea5fe43df2bf050802090ac6344379

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 6, 2018, 16:13

mentioned in commit b0290026f70f6a20eb0e06f562c9389d626e30b4

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 6, 2018, 16:13

mentioned in commit 051042bf6a3193bc2778174116cb3c6b91239d03

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 6, 2018, 16:54

mentioned in commit 9a997fb22484b25530d062f7f367d78e2d8881cf

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 6, 2018, 16:54

mentioned in commit aed2037c9c4dc6252f6a28b4c899d6ffe7737fbe

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 10, 2018, 09:59

mentioned in commit c4718b6061c467f1472e1ae11e032dc33c9750ce

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 10, 2018, 09:59

mentioned in commit fe5fa6b17afe53d71f0ceb933864b1aeac1b8063

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 12, 2018, 09:56

mentioned in commit 564441aa35e473c5f745a5503639566a8f179360

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 12, 2018, 09:56

mentioned in commit 4f9465938d3bd14091cd63fe439ab03a742c6394

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 12, 2018, 09:58

mentioned in commit 9700a581cd1ccf7728e4a10ad9d1b1273bab9f63

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 12, 2018, 09:58

mentioned in commit 5f4607c626e8d385252157e206d74be5c86cf199

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 12, 2018, 12:24

mentioned in commit e79f05d985f0ddf7b3a4ae4b58eae73255db36f1

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 12, 2018, 12:24

mentioned in commit 463698a0b53fd6b3f31968a690475d3bd93b5137

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 12, 2018, 12:26

mentioned in commit 27601661d3b00b6c4fb2f1573d863f5fff9361ae

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 12, 2018, 12:26

mentioned in commit b9c3551b2a0dcd1ba16770bd209bf2967afcfff2

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 12, 2018, 12:29

mentioned in commit f12119e466351c7edb434e8ca8089e9be6c77a50

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 12, 2018, 12:29

mentioned in commit 7fa0a3ab4e9763a2d2f355478bcd618578d4b88e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 12, 2018, 15:13

mentioned in commit 85c61894d8871f6096fbd164280eb529981b40c6

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 12, 2018, 15:13

mentioned in commit d55b9e398ca4d95e2ffe70580cddf7911c161d20

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 12, 2018, 15:45

closed via merge request !959

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Dec 12, 2018, 15:45

mentioned in commit ec909605039d4b96ed6cfc935907502c0c7079c1
