### ISSUE TITLE
FileBasedDirectory can contain stale cached information

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#680]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/680)
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Sep 25, 2018, 11:33

## Background

`FileBasedDirectory` contains an index calculated from the file system which can become stale if the underlying directory is altered outside of the virtual directory API. Additionally, `Sandbox` objects cache `FileBasedDirectory` objects, returning the same instance for multiple calls to `get_virtual_directory`. This means the `FileBasedDirectory` may be out of step with modifications done to the file system. This was the cause of issue #664.

Currently we address this by:
* Making the underlying directory name a secret unless `Sandbox.get_directory` is called
* Invalidating the cached copies of `FileBasedDirectory` objects in the sandbox if `get_directory` is called, and stopping caching any further instances.
* Making it clear in the API what happens if you modify the underlying directory and keep a `FileBasedDirectory` object live.

This still allows for some bugs which may be difficult to track down in the future.

## Task description

This is a suggested course of action; other ideas are welcome.

* [ ] Construct a prototype version of FileBasedDirectory which has no local state
* [ ] Run some benchmarks on `FileBasedDirectory` and see whether the no-local-state version is slower
* [ ] If it is, find other options. If it's not, just use the no-local-state version.

Daniel Silverstone also suggested this mitigation:

> Should the virtual directory objects contain a reference to their parent sandbox, and have that sandbox maintain a monotonic counter which can be checked against to assert() if the counter has the wrong value.  Said counter being incremented by `.get_directory()` ?

## Acceptance Criteria

Equivalent functionality after the change and no drop in performance.

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Sep 25, 2018, 11:35

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Sep 25, 2018, 11:35

mentioned in merge request !818

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @toscalix]](https://gitlab.com/toscalix) on Oct 1, 2018, 08:53

assigned to [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Oct 3, 2018, 09:34

MR is merged but I'd like to test performance before closing this.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Oct 10, 2018, 13:44

MR  !818 mitigated this somewhat but doesn't do the tasks listed in the description, which are still outstanding.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Feb 12, 2020, 15:46

The index was dropped in !1181. Closing.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Feb 12, 2020, 15:46

closed
