### ISSUE TITLE
Let's Encrypt certificate needs to be renewed

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#683]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/683)
In GitLab by [[Gitlab user @tacgomes]](https://gitlab.com/tacgomes) on Sep 27, 2018, 14:47

## Background

[//]: # (Provide a background or the root/source that justifies this task or action.)

The Let's Encrypt certificate will expire on Dec 26 07:39:46 2018 GMT and must to be renewed before that date.

## Task description

The website deployed by this repo supports encrypted communication through HTTPS using a TLS digital certificate provided by [Let's Encrypt].

These certificates are valid only for three months, and thus need to be periodically renewed. In order to do so, follow these steps.

* [ ] Untick "Force domains with SSL certificates to use HTTPS" on the [page settings].

* [ ] Clone and run the [certboot] tool to generate a new certificate:

      git clone https://github.com/certbot/certbot
      cd certbot && ./letsencrypt-auto certonly -a manual -d docs.buildstream.build

   When the ACME challenge token is displayed, do not press `enter` yet.

* [ ] Open the [ci settings], expand _Variables_ and update the value of the `ACME_CHALLENGE` variable with the new token.

* [ ] Manually run a [pipeline for _master_] to force the website to be redeployed.

* [ ] Once the pipeline finishes and thus the website is redeployed, go back to
the terminal and press `enter` now to continue. This will generate new
`fullchain.pem` and `privkey.pem` files.

* [ ] On the [domain settings] replace _Certificate (PEM)_ with updated `fullchain.pem` and _Key (PEM)_ with updated `privkey.pem`.

* [ ] Tick back "Force domains with SSL certificates to use HTTPS" on the [page settings].

* [ ] Update the due date for this issue for three months later.

[Let's Encrypt]: https://letsencrypt.org/
[certboot]: https://certbot.eff.org/
[ci settings]: https://gitlab.com/BuildStream/buildstream/settings/ci_cd
[page settings]: https://gitlab.com/BuildStream/buildstream/pages
[domain settings]: https://gitlab.com/BuildStream/buildstream/pages/domains/docs.buildstream.build/edit
[pipeline for _master_]: https://gitlab.com/BuildStream/buildstream/pipelines/new

## Acceptance Criteria

It is possible to access https://docs.buildstream.build with no warnings displayed concerning the certificate.

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tacgomes]](https://gitlab.com/tacgomes) on Sep 27, 2018, 14:48

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tacgomes]](https://gitlab.com/tacgomes) on Sep 27, 2018, 15:12

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @danielsilverstone-ct]](https://gitlab.com/danielsilverstone-ct) on Mar 29, 2019, 08:50

Is this now dealt with?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Mar 29, 2019, 16:01

[[Gitlab user @danielsilverstone]](https://gitlab.com/danielsilverstone)\-ct No. I will do that now.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Mar 29, 2019, 16:05

But we should close this one. We publish the documentation through another repository now. And both the website and the documentation certificates are dealt at once on: https://gitlab.com/BuildStream/website/issues/10

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Mar 29, 2019, 16:32

I am closing this issue here because of that.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Mar 29, 2019, 16:32

closed
