### ISSUE TITLE
Package Buildstream in the official Fedora repositories

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#686]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/686)
In GitLab by [[Gitlab user @bochecha]](https://gitlab.com/bochecha) on Sep 28, 2018, 18:48

## Background

Installing Buildstream on Fedora would be much easier if it was available to the package manager.

I have been maintaining some unofficial packages in my Copr for quite some time now: https://copr.fedorainfracloud.org/coprs/bochecha/buildstream/

However, having Buildstream in the official Fedora repositories would be much better than in an obscure third-party repository.

I have started the process, this issue is just to keep track of it and give some visibility so others know this is coming. :slight\_smile:

https://bugzilla.redhat.com/showdependencytree.cgi?id=1634449&hide_resolved=0

## Task description

*   [x] Get python-arpy in Fedora (missing dependency)
    *   [x] [reviewed and accepted](https://bugzilla.redhat.com/show_bug.cgi?id=1634009)
    *   [x] built
    *   [x] in updates-testing
    *   [x] in stable
*   [x] Get python-grpcio in Fedora (missing dependency)
    *   [x] [reviewed and accepted](https://bugzilla.redhat.com/show_bug.cgi?id=1634014)
    *   [x] built
    *   [x] in updates-testing
    *   [x] in stable
*   [x] Get Buildstream in Fedora
    *   [x] [reviewed and accepted](https://bugzilla.redhat.com/show_bug.cgi?id=1634449)
    *   [x] built
    *   [x] in updates-testing
    *   [x] in stable
*   [x] Update the Buildstream installation instructions (https://gitlab.com/BuildStream/website/merge_requests/106)

## Acceptance Criteria

On a clean Fedora system, without any required configuration, one can run the following to install Buildstream:

```
$ sudo dnf install buildstream
```

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @bochecha]](https://gitlab.com/bochecha) on Sep 30, 2018, 09:39

marked the task **in updates-testing** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @bochecha]](https://gitlab.com/bochecha) on Sep 30, 2018, 22:07

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @bochecha]](https://gitlab.com/bochecha) on Sep 30, 2018, 22:10

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @bochecha]](https://gitlab.com/bochecha) on Oct 8, 2018, 17:41

marked the task **in stable** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @bochecha]](https://gitlab.com/bochecha) on Oct 8, 2018, 17:41

marked the task **Get python-arpy in Fedora (missing dependency)** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @bochecha]](https://gitlab.com/bochecha) on Dec 16, 2018, 10:31

marked the task **[reviewed and accepted](https://bugzilla.redhat.com/show_bug.cgi?id=1634014)** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @bochecha]](https://gitlab.com/bochecha) on Dec 17, 2018, 23:56

marked the task **built** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @bochecha]](https://gitlab.com/bochecha) on Dec 18, 2018, 00:09

marked the task **[reviewed and accepted](https://bugzilla.redhat.com/show_bug.cgi?id=1634449)** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @bochecha]](https://gitlab.com/bochecha) on Dec 18, 2018, 10:19

marked the task **in updates-testing** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @bochecha]](https://gitlab.com/bochecha) on Dec 18, 2018, 16:43

marked the task **built** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @bochecha]](https://gitlab.com/bochecha) on Dec 19, 2018, 11:00

marked the task **in stable** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @bochecha]](https://gitlab.com/bochecha) on Dec 19, 2018, 11:00

marked the task **Get python-grpcio in Fedora (missing dependency)** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @bochecha]](https://gitlab.com/bochecha) on Dec 19, 2018, 11:00

marked the task **in updates-testing** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @bochecha]](https://gitlab.com/bochecha) on Dec 20, 2018, 20:23

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @bochecha]](https://gitlab.com/bochecha) on Dec 22, 2018, 20:16

marked the task **in stable** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @bochecha]](https://gitlab.com/bochecha) on Dec 22, 2018, 20:16

marked the task **Get Buildstream in Fedora** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @bochecha]](https://gitlab.com/bochecha) on Dec 22, 2018, 20:17

mentioned in merge request website!106

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Dec 23, 2018, 16:07

closed via merge request website!106

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Dec 23, 2018, 16:07

mentioned in commit website[[Gitlab user @b56b337087d9dfb12f3dd1abf11b6ff7a2779da7]](https://gitlab.com/b56b337087d9dfb12f3dd1abf11b6ff7a2779da7)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Dec 23, 2018, 16:08

marked the task **Update the Buildstream installation instructions (https://gitlab.com/BuildStream/website/merge_requests/106)** as completed
