### ISSUE TITLE
Better handle artifact server unimplemented methods

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#688]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/688)
In GitLab by [[Gitlab user @martinblanchard]](https://gitlab.com/martinblanchard) on Oct 1, 2018, 14:21

## Background

At the moment, calling an unimplemented method would raise an unhandled `NotImplementedError` on the artifact server side. Would be better to simply return a gRPC error with an `UNIMPLEMENTED` status to the client.

## Task description

* [x] `ContentAddressableStorage.BatchUpdateBlobs` (implementation in progress BuildStream/buildstream#676).
* [ ] `ContentAddressableStorage.GetTree` (no implementation plan yet).
* [ ] `ByteStream.QueryWriteStatus` (no implementation plan yet).

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @martinblanchard]](https://gitlab.com/martinblanchard) on Oct 1, 2018, 15:24

marked this issue as related to #676

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @martinblanchard]](https://gitlab.com/martinblanchard) on Oct 2, 2018, 09:20

marked the task **`ContentAddressableStorage.BatchUpdateBlobs` (implementation in progress BuildStream/buildstream#676).** as completed
