### ISSUE TITLE
Alter SandboxRemote to use separate CAS store

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#750]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/750)
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Nov 5, 2018, 16:41

## Background

Remote Execution currently uses the Artifact Cache to store and transmit filesystems and commands. Since !922, the Artifact Cache and Content-addressable storage cache are separate entities and we can just use a CASCache object for remote execution. Currently the configuration option for the artifact cache is used to select the cache for remote execution, so we'll need to add more configuration options.

Related to #659.

## Task description

* [ ] Add a configuration option which allows us to specify the endpoint for a CASCache separate to the artifact cache.
* [ ] Rewrite SandboxRemote so it uses only CASCache, rather than ArtifactCache.
* [ ] Remove the parts of ArtifactCache that are currently only used by SandboxRemote.

## Acceptance Criteria

Equivalent remote execution functionality with the additional option to use a separate endpoint for remote execution storage.

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Nov 9, 2018, 17:28

mentioned in merge request !946

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Nov 27, 2018, 18:17

closed via merge request !946

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Nov 27, 2018, 18:17

mentioned in commit 2a8a3b19966a25eff30391e9f50dbe9610d20c33
