### ISSUE TITLE
Improve the documentation related with the disk space quota used by default by BuildStream.

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#769]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/769)
In GitLab by [[Gitlab user @toscalix]](https://gitlab.com/toscalix) on Nov 19, 2018, 09:47

## Background

Based on the discussion generating while processing the ticket number #733 there was an agreement about improving the user documentation when it comes to improve the documentation related with the disk quota. The goal should be to improve it before the release of 1.4

## Task description

Tasks to be executed:
* [ ] Better document the default disk space quota used in BuildStream in the user documentation.
* [ ] Include a couple of examples of a different quota based on different but common use cases.
* [ ] Add this improvement to the release notes (NEWS)

## Acceptance Criteria

* Link to the user documentation where this information has been improved.

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @toscalix]](https://gitlab.com/toscalix) on Nov 19, 2018, 09:47

marked this issue as related to #733

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Nov 19, 2018, 10:56

This has been done in !939

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Nov 19, 2018, 10:56

closed
