### ISSUE TITLE
Execution Environment Requirements

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#775]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/775)
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Nov 20, 2018, 16:48

## Background

[Discussion on the mailing list](https://mail.gnome.org/archives/buildstream-list/2018-November/msg00003.html). Marking this as a blocker for 1.4.

This will allow us to use remote execution (with services that supports it) to build projects on different OS's and architectures. This will involve adding user configuration options that are used for `SandboxConfig`, and then passed into `Platform` message within the `Command` message uploaded. It should default to the host OS and architecture if nothing is specified and can be specified in both project and element options.

This will change the architecture option in `SandboxConfig`, `machine_arch`, to one proposed in the mailing list, which is slightly different to `uname -m` and incorporates the endianness of the system. Particularly important for architectures such as ARM that can be set either way.

If specified we also want to be able to build 32-bit builds on a 64-bit machine.

## Task description

* [ ] Add option for users to set sandbox configuration OS and architecture.
* [ ] Update `machine_arch` to use proposed list, checking endianness of system.
* [ ] Use this to set the `Platform` part of the `Command` message.
* [ ] Change local sandboxes to use personality/linux32 if building a 32bit library on a 64bit computer.
* [ ] Add os project option type, very similar to the already existing arch project option type.
* [ ] Report an error when attempting to build locally with an incompatible os or arch configuration. We already have Platform.check_sandbox_config(), which I expect to be usable for this.

## Acceptance Criteria

Users can now specify OS and architectures, and this is sent correctly to remote execution services within the `Platform` message.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Nov 21, 2018, 18:24

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Nov 21, 2018, 18:24

assigned to [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Nov 21, 2018, 18:25

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Nov 21, 2018, 18:31

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Nov 22, 2018, 10:54

Additional tasks:
* Add `os` project option type, very similar to the already existing `arch` project option type.
* Report an error when attempting to build locally with an incompatible `os` or `arch` configuration. We already have `Platform.check_sandbox_config()`, which I expect to be usable for this.

> different to `uname -m` and incorporates the endianness of the system

At least on Linux I think `uname -m` already distinguishes between big and little endian on architectures that support both. I.e., a mapping from `uname -m` to the platform-independent name should suffice on Linux.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Nov 22, 2018, 11:00

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Nov 22, 2018, 11:36

marked this issue as related to #523

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Nov 23, 2018, 15:24

mentioned in merge request !969

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Dec 5, 2018, 15:28

closed via merge request !969

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Dec 5, 2018, 15:28

mentioned in commit eb1ed4108b75ed919f471e448fa6088b1503a328
