### ISSUE TITLE
Add support for running tests in BuildStream

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#776]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/776)
In GitLab by [[Gitlab user @chiaratolentino]](https://gitlab.com/chiaratolentino) on Nov 22, 2018, 14:26

## Background

[//]: # (Provide a background or the root/source that justifies this task or action.)
From the [discussion on the mailing list](https://mail.gnome.org/archives/buildstream-list/2018-October/msg00058.html):

> As software integrators, we would like to run tests as part of BuildStream
> builds and be able to validate (at a later stage in build) that the tests for a
> given element have passed. Ideally, such tests should have the following
> properties:
> 
>   1.) Tests should not block reverse dependency builds.
>
>   2.) Strong association between an element and its tests.
>
>   3.) Additional dependencies for testing an element should not be required
>       while building it.
>
>   4.) Elements should be able to assert that the tests for their dependencies
>       have passed.
>
>   5.) Test elements are not necessarily pass-through elements - they can have
>       meaningful output such as coverage reports.

## Task description

[//]: # (Short summary of the action to be executed)

The proposed solution is to introduce the concepts of 'conditions' and 'abstract dependencies'. For more detail, see the [full proposal from the mailing list](https://mail.gnome.org/archives/buildstream-list/2018-November/msg00038.html)

* [ ] Add a new ```conditions``` field to the bst element file with subfields ```provides``` and ```requires```, e.g.

```yaml
conditions:
  provides:
    tested:
    - app-test.bst
    packaged:
    - app-pkg.bst
  requires:
    - tested
```
* [ ] Add abstract dependencies (https://gitlab.com/BuildStream/buildstream/issues/777)

* [ ] Add functionality to ```bst show``` to check the ```conditions``` fields of an element (for possible sample outputs, see the examples under part 3 of the mailing list proposal)

* [ ] Expose a Python API for staging an element's build tree (see part 4 of the mailing list proposal for the justification for this)
* [ ] Provide a method to guarantee that the build tree we want to stage (for the purposes of running tests) exists in the dependency artifact

## Acceptance Criteria

[//]: # (Acceptance criteria should follow the S.M.A.R.T. principle https://en.wikipedia.org/wiki/SMART_criteria )

Users can run tests as part of the build of an element such that the test properties outlined above are satisfied.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @chiaratolentino]](https://gitlab.com/chiaratolentino) on Nov 22, 2018, 14:27

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Nov 23, 2018, 11:32

'[ ] Expose a Python API for staging an element's build tree (see part 4 of the mailing list proposal for the justification for this)' is soon to be landed as a new api 'checkout_artifact_subdir()' to the artifactcache. It's currently part of my WIP for staging buildtrees into workspaces, but could be landed separately.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @chiaratolentino]](https://gitlab.com/chiaratolentino) on Dec 14, 2018, 10:46

There are still some implementation details that need to be worked out for this solution to having testing support in BuildStream. Mainly, to do with:
> Provide a method to guarantee that the build tree we want to stage (for the purposes of running tests) exists in the dependency artifact

See also: https://mail.gnome.org/archives/buildstream-list/2018-December/msg00112.html

This issue might have to be put on hold for now

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on May 28, 2020, 12:30

# Update

From [blocker list discussions](https://mail.gnome.org/archives/buildstream-list/2020-April/msg00013.html):

```
It was discussed that it would be undesirable for Elements to gain
unnecessary complexity, and it would be undesirable to have a situation
where an existing artifact can later be modified by virtue of it, and
it's dependencies having been "tested".

In the original discussions there were concerns also about scheduling,
and the availability of build trees at the time of test (testing an
element can often require the presence of the element's build tree).

While we prefer not to add any complexity in the core, we recognize that
testing is considered a first class operation by users.

Blocker: Revisit this discussion with a clear proposal, and evaluate
         later whether this would be a breaking change.
```

Adding this to the milestone:

* A clear proposal needs to land on the mailing list and be accepted
* Need to determine if an implementation would be a breaking change
  * If it is a breaking change, it remains a blocker
  * Otherwise, it can be removed from the milestone

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on May 28, 2020, 12:34

marked this issue as related to #1327

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on May 28, 2020, 12:35

Marking #1327 as related because it will quite possibly be a blocker to resolving this issue.
