### ISSUE TITLE
Add `bst source` command group

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#814]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/814)
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Dec 7, 2018, 18:58

## Background

See https://mail.gnome.org/archives/buildstream-list/2018-November/msg00106.html and its replies for full context. The summary is that similar to how we plan on having a `bst artifact` command group to handle all operations related to artifacts, it would make sense to have a `bst source` command group to handle all source operations.

## Task description

[//]: # (Short summary of the action to be executed)

* [x] Add new source command group
* [x] Move fetch, track and source-checkout commands under the new group
* [x] Mark fetch and track commands as obsolete

## Acceptance Criteria

[//]: # (Acceptance criteria should follow the S.M.A.R.T. principle https://en.wikipedia.org/wiki/SMART_criteria )

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Dec 10, 2018, 19:39

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Dec 10, 2018, 19:51

mentioned in commit 6d37cd9fe338720910ef8e2713a22200e0ee6d11

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Dec 10, 2018, 19:53

mentioned in merge request !1003

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Dec 10, 2018, 21:13

mentioned in commit 2354997e818e69c785e118186d76fbedb1700d67

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Dec 14, 2018, 15:31

mentioned in commit dc8e332ddb2ad6beb1a3e73315fba43151609af7

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Dec 14, 2018, 15:33

mentioned in commit 7d0ec397606d44cda4cdedeed164ec20cb7e7e51

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Dec 14, 2018, 18:50

mentioned in commit 72e3b5c9b965fbc1dba06e2e4e5b4fdeb25fcd13

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Dec 14, 2018, 19:34

mentioned in commit 629a6e52410f97edb386e59c48b7a7c28b3bf30a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Dec 14, 2018, 20:07

closed via merge request !1003

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Dec 14, 2018, 20:07

mentioned in commit b23bec551839e4d652a23a349fed96c885d7f7f5

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Dec 17, 2018, 11:14

marked the task **Add new source command group** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Dec 17, 2018, 11:14

marked the task **Mark fetch and track commands as obsolete** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Dec 17, 2018, 11:14

marked the task **Move fetch, track and source-checkout commands under the new group** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Dec 18, 2018, 12:57

marked this issue as related to #822
