### ISSUE TITLE
Consistent UX for fetching and pulling

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#819]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/819)
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Dec 17, 2018, 18:47

## Background

See https://mail.gnome.org/archives/buildstream-list/2018-December/msg00000.html and its follow-ups for details on the discussion.

BuildStream should provide a consistent UX for pulling (or fetching, in case of sources) sources, artifacts, build trees, junctions etc. For all such things, we should provide the following:

- Options for both `--pull` and `--no-pull` case (or, `--fetch` and `--no-fetch` in case of sources) should be added to the top-level `bst` command.
- It should be possible for users to configure the default behavior, not just via CLI, but also using config files.
- So long as it is non-intrusive, BuildStream should default for fetching/pulling things that are needed.
- No matter what is the default provided by BuildStream, it should be possible to override it. The overrides should work in the following order (highest priority item listed first):
  1. CLI flag
  2. User config
  3. BuildStream default

## Task description

[//]: # (Short summary of the action to be executed)

* [ ] Add `--fetch`/`--no-fetch` as top-level options, with support for user config, and remove similar options from existing commands.
* [ ] Add `--fetch-junctions`/`--no-fetch-junctions` as top-level options, with support for user config.
* [ ] Add `--pull`/`--no-pull` as top-level options, with support for user config, and remove similar options from existing commands.
* [ ] Add `--no-pull-buildtree` as top-level option (`--pull-buildtree` already exists), with support for user config.

## Acceptance Criteria

[//]: # (Acceptance criteria should follow the S.M.A.R.T. principle https://en.wikipedia.org/wiki/SMART_criteria )

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Jul 5, 2019, 13:35

Interestingly, we added a `--pull` command to `bst artifact checkout`, and ignored everything else about this issue! We'll need to add this to `bst source checkout` (or well, make these things public flags).

From some recent discussion, we decided to change this a little; we want to make `--pull` the default option for all commands, and change the semantics of `--fetch` a little (see #1065).

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @sstriker]](https://gitlab.com/sstriker) on Jul 5, 2019, 15:25

Just to clarify, an implicit --pull should only download any objects to
satisfy the operation being performed.  For example bst artifact show only
requires the Artifact proto.  Whereas bst artifact checkout requires the
contents of the artifact as well.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Apr 24, 2020, 08:00

mentioned in merge request !1882

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Sep 29, 2020, 16:54

mentioned in commit 8ce3c6d90ecc7e6dd012d61db4df0f2d05c5d61c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Sep 29, 2020, 16:54

mentioned in commit 498e683e1defb3fe919ee14ce26f43868ec1c3c8

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Sep 29, 2020, 16:57

mentioned in merge request !2077
