### ISSUE TITLE
Mark bst checkout/pull/push as obsolete

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#822]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/822)
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Dec 18, 2018, 12:56

## Background

[//]: # (Provide a background or the root/source that justifies this task or action.)

See https://mail.gnome.org/archives/buildstream-list/2018-November/msg00106.html and its followups for full context.

As we aim to provide `bst artifact` group of commands to do all operations related to artifacts, we should fold the existing commands that do similar things in that group. So, in addition to providing new commands like `log`, `list` etc, we should also look into moving `pull`, `push` and `checkout` under that group (similar to how we did so for the `bst source` group).

## Task description

[//]: # (Short summary of the action to be executed)

* [x] Provide new functionality under `bst artifact` group - See WIP !1008.
* [x] Mark `bst chekcout` as obsolete (this should be done in the same way as we handle `fetch` and `track`).
* [x] Move `pull` and `push` under `bst artifact` group, and mark them as obsolete.

## Acceptance Criteria

[//]: # (Acceptance criteria should follow the S.M.A.R.T. principle https://en.wikipedia.org/wiki/SMART_criteria )

All functionality that requires dealing with artifacts, should be moved under `bst artifact` command group, and existing alternatives should be marked as obsolete.

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Dec 18, 2018, 12:57

marked this issue as related to #812

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Dec 18, 2018, 12:57

removed the relation with #812

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Dec 18, 2018, 12:57

marked this issue as related to #814

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jan 8, 2019, 09:45

mentioned in merge request !1045

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @richardmaw-codethink]](https://gitlab.com/richardmaw-codethink) on Jan 9, 2019, 13:03

mentioned in commit bd6e584eb73c12ed5000c695a8486dfdd4facd99

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @richardmaw-codethink]](https://gitlab.com/richardmaw-codethink) on Jan 9, 2019, 14:08

mentioned in commit 87728df7803968c099f1092d4f4039a6c2f5c20c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jan 9, 2019, 14:38

mentioned in merge request !1049

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @richardmaw-codethink]](https://gitlab.com/richardmaw-codethink) on Jan 9, 2019, 14:39

mentioned in commit 1b93af8edfc9a449a9c99b1d4083ff5936f20228

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @richardmaw-codethink]](https://gitlab.com/richardmaw-codethink) on Jan 9, 2019, 16:24

mentioned in commit 831df5a9ac851fbb66f20f1f205bda5da2723f95

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @richardmaw-codethink]](https://gitlab.com/richardmaw-codethink) on Jan 9, 2019, 17:05

mentioned in commit a323e6752c1f6929c43b75591a348c101360640e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jan 10, 2019, 14:07

mentioned in commit c7c38be174af9225b73fa6f43485b59f146a7149

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jan 17, 2019, 12:19

mentioned in commit 6665fcafe5c3958fbf30a5c703c81fd4a0887f5b

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jan 17, 2019, 13:08

mentioned in commit ebfce986f3d1e55be417650370b8c65c524c0a8a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jan 17, 2019, 14:45

mentioned in commit 5aa409448c0bb539b82d85bb27a4e0da5296412f

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jan 21, 2019, 09:58

mentioned in commit 610c9d830a5f6aef9463d7eeab6abafdde42acb5

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jan 22, 2019, 12:42

mentioned in commit fbd159390e97a26f85bb7e8d6284b14bb77083ff

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jan 22, 2019, 16:28

marked the task **Mark `bst chekcout` as obsolete (this should be done in the same way as we handle `fetch` and `track`).** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jan 22, 2019, 16:28

marked the task **Move `pull` and `push` under `bst artifact` group, and mark them as obsolete.** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jan 22, 2019, 16:30

UPDATE: These commands are now all obsolete in the sense that they are contained within the artifact subcommand group. However, they're yet to handle artifact refs. Some work is currently being undertaken to do this properly (further details can be found [here](https://mail.gnome.org/archives/buildstream-list/2019-January/msg00040.html)). This issue will be closed once `bst artifact checkout/pull/push` can handle artifact refs *as well as* element names.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Feb 18, 2019, 15:38

UPDATE: Ensuring that the `bst artifact checkout/pull/push` commands could support artifact refs was put on hold until we refactored how we dealt with artifact refs. This refactor has now landed: !1101

We should be in a position to amend `checkout/push/pull` so that they can handle refs.

See: https://gitlab.com/BuildStream/buildstream/issues/773#note_142351074 for more detail.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Aug 28, 2019, 16:56

mentioned in merge request !1565

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Aug 29, 2019, 12:47

mentioned in merge request !1568

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Sep 5, 2019, 14:47

marked the task **Provide new functionality under `bst artifact` group - See WIP !1008.** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Sep 5, 2019, 14:51

I think this has now been achieved:

- Initial move to the artifact subcommand group: !1045
- Ability to handle artifact refs as arguments: !1065 & !1068

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Sep 5, 2019, 14:51

closed
