### ISSUE TITLE
Partial, file-free local CAS

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#832]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/832)
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Dec 20, 2018, 18:05

## Background

This is a "WIP" issue and the description may change.

In an environment which makes heavy use of remote execution, it is not necessary to have all the files for an element on the local machine, only the directory structure to enable staging. We want to modify local CAS to make the file contents optional.

Original mailing list post which started this: https://mail.gnome.org/archives/buildstream-list/2018-November/msg00022.html

The expected behaviour of partial CAS is:

* The default behaviour will be that all runtime dependencies of a built artifact will end up on the machine which ran `bst build`, such that the user can do a checkout, shell or further local builds without any network access.
* We may add an option which removes that requirement for builds.
* When pushing an artifact to an artifact cache, or pushing source directories to a remote execution service, it is still the local `bst`'s responsibility to ensure all file contents are on that server and push them itself if necessary.

When pushing, we will now check our *full* list of expected objects against the server; if the server reports missing blobs in there and we do not have it, we have to query all remotes to obtain it. This means pushing now may involve pulling.

## Task description

* [x] In `Element`/`ArtifactCache` check for the presence of all file blobs of an artifact instead of only checking for the ref, i.e., trigger `pull()` on partial artifact
* [x] Make sure `pull()` can complete a partial artifact
* [x] Add support for completing a partial artifact in `SandboxRemote`
* [x] Mandate all elements/plugins to support virtual directories when remote execution is configured (drop fallback to local builds)
* [x] Consider artifacts with missing file blobs as cached when remote execution is configured and the element is not a runtime dependency of the build target
* [x] Skip pulling file blobs from artifact cache when remote execution is configured and the element is not a runtime dependency of the build target
* [x] Skip fetching output files from remote execution CAS server if the element is not a runtime dependency of the build target and the files are not required for artifact pushing

## Acceptance Criteria

* The goal is to reduce network bandwidth and speed up builds. We should provide some evidence that this works.

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Dec 21, 2018, 11:53

I feel there's quite a lot of overlap with the buildtree push/pull work here, in terms of missing references and attempting to 'complete' an artifact. Something to consider.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Mar 5, 2019, 13:27

assigned to [[Gitlab user @juergbi]](https://gitlab.com/juergbi)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Mar 12, 2019, 09:45

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Mar 13, 2019, 11:10

mentioned in merge request !1225

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Mar 14, 2019, 18:26

mentioned in merge request !1232

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Mar 25, 2019, 10:20

marked the task **In `Element`/`ArtifactCache` check for the presence of all file blobs of an artifact instead of only checking for the ref, i.e., trigger `pull()` on partial artifact** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Mar 25, 2019, 10:20

marked the task **Make sure `pull()` can complete a partial artifact** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Mar 27, 2019, 18:49

marked the task **Add support for completing a partial artifact in `SandboxRemote`** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Apr 1, 2019, 12:42

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Apr 3, 2019, 19:40

mentioned in merge request !1278

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Apr 12, 2019, 11:38

marked the task **Mandate all elements/plugins to support virtual directories when remote execution is configured (drop fallback to local builds)** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Apr 12, 2019, 11:38

marked the task **Consider artifacts with missing file blobs as cached when remote execution is configured and the element is not a runtime dependency of the build target** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Apr 12, 2019, 11:38

marked the task **Skip pulling file blobs from artifact cache when remote execution is configured and the element is not a runtime dependency of the build target** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Apr 12, 2019, 11:38

marked the task **Skip fetching output files from remote execution CAS server if the element is not a runtime dependency of the build target and the files are not required for artifact pushing** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Apr 17, 2019, 08:44

Initial support for partial local CAS has been merged. Closing this issue.

Possible follow-ups are described here: https://mail.gnome.org/archives/buildstream-list/2019-April/msg00027.html

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Apr 17, 2019, 08:44

closed
