### ISSUE TITLE
Cover the use of WSL in CI

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#852]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/852)
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Jan 9, 2019, 15:30

## Background

Some users are unable to use a pure linux environment, and the next best thing for a Windows user is WSL.

Thanks to !726, WSL works, after a fashion, but we are currently lacking coverage of this in gitlab CI.

## Task description

* [x] Devise a prototype of running buildstream's CI on WSL
* [ ] Devise a reliable way to set up and configure a WSL CI runner
* [ ] Submit documentation for setting up and confgiuring a WSL CI runner
* [ ] Submit a MR extending .gitlab-ci.yml to include a WSL-specific test

## Acceptance Criteria

1. buildstream's CI runs tests on a WSL runner.
2. A user with minimal experience of WSL and gitlab internals can follow instructions to add a new WSL runner.

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Jan 9, 2019, 16:27

After borrowing the computer Phillip used to work with buildstream on WSL, I was able to get it running gitlab-runner, and ran a CI worker (https://gitlab.com/BuildStream/buildstream/-/jobs/143383993). gitlab-runner is running in "shell" mode here, so it's running with barely any isolation and relies on bespoke setup.

My next step will be investigating various containerisation solutions, and see how much of the setup can be automated.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Jan 17, 2019, 12:05

marked the task **Devise a prototype of running buildstream's CI on WSL** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Jan 17, 2019, 12:27

Status update:

I have a basic prototype of WSL as a CI runner (based on a laptop provided by [[Gitlab user @knownexus]](https://gitlab.com/knownexus)), where most of the tests that are run pass.
A lot of tests are skipped because WSL doesn't provide a sandbox (because we lack a fuse implementation)

I have a script provided by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) that spins up and configures a Windows 10 VM with WSL, and am currently extending it to setting up a gitlab runner as well. (pushing it to gitlab so there's some visibility is forthcoming)

Because buildstream on WSL currently skips tests that don't provide a sandbox, I've been looking into how to integrate it into [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur)'s work on using remote execution in tests (i.e. spinning up containers for an artifact cache server, buildgrid coordinator and buildgrid worker), and have a plan of the following:
* A linux-based computer running a Windows 10 VM
* This linux-based computer also running containers for the artifact cache, buildgrid coordinator and buildgrid worker.
* The script that sets up the windows-based VM will also be responsible for pulling in all the necessary certificates and gitlab registration tokens for configuring the VM.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Jan 17, 2019, 13:12

The scripts to setup a Windows 10 VM have been pushed to https://gitlab.com/jonathanmaw/wsl-setup-script

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Jan 17, 2019, 13:45

> Because buildstream on WSL currently skips tests that don't provide a sandbox

I think this is okay for now. Even if skip all the tests that require a sandbox, that would already give us some value. And later we can separately add tests for testing with BuildGrid etc. That seems like something that would be useful for linux tests as well but seems slightly orthogonal to this issue.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Jan 22, 2019, 13:30

The mailing list discussion (https://mail.gnome.org/archives/buildstream-list/2019-January/msg00025.html) is related to this issue.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Jan 25, 2019, 16:04

mentioned in merge request !1108

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Feb 6, 2019, 15:29

closed via merge request !1108

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Feb 6, 2019, 15:29

mentioned in commit 256bcde5e09848f62b3621c4db0e56440d293889

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Mar 15, 2019, 13:48

Sometimes the wsl runner takes a long time to pass the CI pipeline, holding everything back for up to an hour (see [here](https://gitlab.com/BuildStream/buildstream/-/jobs/177768679)). I'm not sure if this is an infrastructure issue, but it might be worth making the test manual for now, especially as it can hold up marge bot from merging branches.
