### ISSUE TITLE
YamlCache reads the entire file's contents to see if the file is in the cache

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#891]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/891)
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Feb 1, 2019, 15:00

## Background

YamlCache is a class that speeds up the parsing and provenancing of yaml by maintaining a cache of yaml parsing that is persistent across BuildStream executions.
Currently, it reads all of a file's contents to decide whether it has changed since it was put in the cache.
There should be an easier way to do that - statting a file and comparing its mtime works in most cases.

There are currently three distinct cases where we load yaml, listed in order of most to least common:
1. Element file from a checked-out project. mtime is very suitable for this.
2. Element file from a junctioned project. mtime is not suitable for this because these files are a checked-out Source each buildstream invocation.
3. Element file from a workspace of a junctioned project. mtime *should* be suitable for this, but I am not sure whether it actually loads the file from the workspace.

## Task description

[//]: # (Short summary of the action to be executed)

* [ ] Write a test case to check whether changes in a workspace of a junction are being picked up.
  * [ ] If not being read, fix this.
* [ ] Use the file's mtime when checking for changes in an element in a checked-out project, or a workspaced junctioned project.
* [ ] Use the junctioning element's cache key when checking for changes in an element in a junctioned project - plus potentially changes to the Element API if acquiring this information breaks encapsulation.
* [ ] Ensure that the yamlcache is being exercised for element checkouts, junctions and workspaced junctions with tests.

## Acceptance Criteria

Unless completely unavoidable, YamlCache does not need to read the contents of a file to know whether it is cached.

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Feb 1, 2019, 15:56

I've tested these changes on linux, and on WSL, and any difference is extremely marginal.

In the files below, "no-read" is with my changes, and "with-read" is from master.

[no-read-no-cache-show.cprofile](/uploads/43f90ebd224c3c5c703a65e9a81c9168/no-read-no-cache-show.cprofile)

[no-read-with-cache-show.cprofile](/uploads/a398d69af80957c2e0d46996a1567827/no-read-with-cache-show.cprofile)

[with-read-with-cache-show.cprofile](/uploads/e447c5c358402da1d8ee7e0b12d93515/with-read-with-cache-show.cprofile)

[with-read-no-cache-show.cprofile](/uploads/21412b38582ea7ba6ec687a76ce831a1/with-read-no-cache-show.cprofile)

I suspect this just indicates that the major slowdown isn't from WSL, but is from not using an SSD.

I will retry these changes later on spinning rust over USB and see if there is a more pronounced improvement.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Feb 1, 2019, 16:00

Have you tried this with cold page/dentry cache?

``echo 3 > /proc/sys/vm/drop_caches``

This might not be supported on WSL, though, in which case you may have to reboot before each test to ensure a cold page/dentry cache.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Feb 4, 2019, 15:54

mentioned in merge request !1126

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Feb 4, 2019, 17:24

I've tested these changes on WSL with the project directory on the external disk over USB, and the results are no better. 

[master-no-yamlcache.cprofile](/uploads/79ac870596b0e4a0fede66bd26d93962/master-no-yamlcache.cprofile)

[master-with-yamlcache.cprofile](/uploads/1650767ecb78947aabdd6265429846b2/master-with-yamlcache.cprofile)

[no-read-no-yamlcache.cprofile](/uploads/6d93fcf525265407fd73656de78c39ca/no-read-no-yamlcache.cprofile)

[no-read-with-yamlcache.cprofile](/uploads/44924c8344fe8451cd9ed31cebb546f3/no-read-with-yamlcache.cprofile)

It would seem that there's an equal amount of latency to read the contents of the file compared to statting the file.

Next, I will test whether a difference exists on native linux (i.e. what if there is equal latency because of the ext4 emulation layer). If I fail to see a performance improvement there, then I will close this issue, as there is no meaningful performance gain from reading the inode over reading the contents.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Feb 5, 2019, 12:49

On native linux, with the project on spinning rust over USB, with drop_caches, the time saving is minor (~2s of a ~40s runtime)

[master-no-cache.cprofile](/uploads/e761f4d2798905d08c4bfc55e52a7210/master-no-cache.cprofile)

[master-with-cache.cprofile](/uploads/3e0bd506af4531bf9864f4e8495f76e2/master-with-cache.cprofile)

[no-read-no-cache.cprofile](/uploads/bb82ce03111ff0eba6e4fef2876b962c/no-read-no-cache.cprofile)

[no-read-with-cache.cprofile](/uploads/a10627756f66520a24cc246ac3cf33ee/no-read-with-cache.cprofile)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Feb 5, 2019, 15:11

unassigned [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Feb 5, 2019, 15:12

Given the benefits of this optimisation are very small, I'm putting this issue down and looking at #895 instead

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Feb 5, 2019, 17:03

> Given the benefits of this optimisation are very small, I'm putting this issue down and looking at #895 instead.

Fair enough, I have a suspicion that the benefits of this optimization are only very small because the hugest bst projects are fairly small (perhaps the cost of a `stat()` is similar to the full read of a file that is small enough to be transfered in a single buffer ?).

Judging from the performance gained by fixing workspaces to use mtimes instead of exhaustively (and quite needlessly) hashing file content, we will gain a lot of performance here for any project which consists of about 6GB of `.bst` files (e.g., like a built WebKit workspace).

Perhaps it's still worth swapping out the hashing algorithm for a local mtime approach too, just for the peace of mind that this wont cost more for larger files.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Feb 15, 2019, 18:02

I had another look, this time about whether there are improvements when loading yaml from junctioned elements. I had the suspicion it might be a useful improvement because we don't need to make any syscalls to know whether it's cached (we already have the junction element's cache key).

[master-with-cache.cprofile](/uploads/464f8ea1acc92cfe6f442cf73601b9e8/master-with-cache.cprofile)

[no-read-with-cache.cprofile](/uploads/4b565aec7eb05c5f5d9296954f6705ca/no-read-with-cache.cprofile)

There is no appreciable improvement on my linux laptop. It might still be worthwhile if there's a decent improvement on WSL.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @danielsilverstone-ct]](https://gitlab.com/danielsilverstone-ct) on Mar 29, 2019, 08:33

Since !1257 merged, we no longer have a `YamlCache` so this issue can be closed.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @danielsilverstone-ct]](https://gitlab.com/danielsilverstone-ct) on Mar 29, 2019, 08:33

closed
