### ISSUE TITLE
Setup cache server for overnigth jobs

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#897]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/897)
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Feb 6, 2019, 11:04

## Background
This will have two benefits:
- Overnight test will not build everything from scratch all the time (cache key of bst master is different from bst-1.2) (there is already a separate test for testing overnigth jobs without cache)
- There will be a place to test a remote cache server works with buildstream

## Task description

* [x] Setup cache server using the one included in buildstream (see https://gitlab.com/BuildStream/infrastructure/infrastructure/-/merge_requests/1)
  * [x] Supports master
  * [x] Supports bst-1 branch
* [x] Change CI to point to it (see https://gitlab.com/BuildStream/buildstream/-/merge_requests/2004)

## Acceptance Criteria
Overnight tests use the new cache server

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Feb 6, 2019, 12:38

The overnight tests should also still ensure nothing fails doing clean builds. In general I do think that buildstream should provide a remote cache of some sort.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Feb 6, 2019, 12:40

> The overnight tests should also still ensure nothing fails doing clean builds

Yeah, there is already a separate test for that; let me update the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Feb 6, 2019, 12:40

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Jul 10, 2020, 14:10

changed title from **Setup cache server** to **Setup cache server{+ for overnigth jobs+}**

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Jul 10, 2020, 14:10

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Jul 10, 2020, 14:10

assigned to [[Gitlab user @willsalmon]](https://gitlab.com/willsalmon)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Jul 10, 2020, 14:14

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Jul 10, 2020, 14:15

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Jul 22, 2020, 12:21

assigned to [[Gitlab user @tcanabrava]](https://gitlab.com/tcanabrava)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @willsalmon]](https://gitlab.com/willsalmon) on Jul 24, 2020, 16:31

mentioned in merge request !2004

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Jul 27, 2020, 10:56

marked the task **Setup cache server using the one included in buildstream** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Jul 27, 2020, 10:56

marked the task **Supports master** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Jul 27, 2020, 10:56

marked the task **Supports bst-1 branch** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Jul 27, 2020, 10:57

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Jul 27, 2020, 14:33

mentioned in commit fecf3534d887e52b5bf5bbc5ef6861a54d858d12

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Jul 28, 2020, 10:48

marked the task **Change CI to point to it (see https://gitlab.com/BuildStream/buildstream/-/merge_requests/2004)** as completed
