### ISSUE TITLE
Remove BuildStream version 1.2 form Debian Buster packaging

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#901]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/901)
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Feb 11, 2019, 12:42

## Background

Quoting from the [notes from the gathering](https://docs.google.com/document/d/1bENn0gIHDPyTXaRwqSoA2F11gn55vvWLB7qMIe3Pk1U/edit):

'We need to get 1.2 removed from Debian buster before it gets released (soon). We don’t want to commit to maintaining it for the lifetime of he release'

Given the changes agreed to the release model, this isn't ideal.

## Task description

* [ ] Update BuildStream's documentation and website with an update on the Release Policy change
* [ ] State clearly that version 1.2 is not stable and not intended for general consumption
* [ ] Reach out to Debian maintainer to remove BuildStream 
* [ ] Update the BuildStream website accordingly 

## Acceptance Criteria

* [ ] BuildStream removed from Debian packaging before Buster is released 
* [ ] Website and docs updated accordingly

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Feb 11, 2019, 12:49

Taking in account we have several distros packaging buildstream already (see https://buildstream.build/install.html), I think more that telling each maintainer of each distro to remove a package, the real fix is to fix buildstream docs to clearly state 1.2.x is not recommended for general consumption, and It's going to be deprecated soon

Then is distros jobs to decide what to do

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Feb 11, 2019, 12:52

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Feb 11, 2019, 12:52

OK, have amended the description.

Clearly, though, we do need to reach out to Debian specifically to get it removed before the release of Buster.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Feb 12, 2019, 14:24

marked the task **Update BuildStream's documentation and website with an update on the Release Policy change** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Feb 12, 2019, 14:24

marked the task **Update BuildStream's documentation and website with an update on the Release Policy change** as incomplete

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Feb 13, 2019, 08:07

Currently, key contributors have stated that they will not invest in 1.2 support, and the project in general is not promising any other stable release in the near future.

I think that discouraging usage of the only stable version would be a bad mistake.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Feb 19, 2019, 14:14

That makes sense, closing this issue.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Feb 19, 2019, 14:14

closed
