### ISSUE TITLE
Expose templated tests for source plugins

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#944]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/944)
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 5, 2019, 15:07

## Background

[//]: # (Provide a background or the root/source that justifies this task or action.)
  
  We have a whole battery of tests which run against a variety of
  source plugins, these are currently scattered across various tests.
  We want to make it possible for plugin authors to leverage these
  templated tests. This way, a plugin author will be able to test a
  source plugin's basic functionality with as few lines of code as
  possible. And will only have to write tests from scratch which cover
  edge cases and failure modes specific to their plugin.

## Task description

[//]: # (Short summary of the action to be executed)
  * [x] - Consolidate the current code for templated tests - !1215
  * [x] - Make it easy to provide new repo types to the template framework - !1261
  * [x] - Expose the necessary plugin author facing api in buildstream.plugintestutils - !1261 

----
[//]: # (To review information about possible relevant labels for this issue please view the list of labels: https://gitlab.com/BuildStream/buildstream/labels)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 5, 2019, 15:09

marked this issue as related to #937

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 7, 2019, 15:53

mentioned in commit 7b63ce6d4a7f1559b3a309f19a7c1c45c0dbc6d0

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 7, 2019, 15:53

mentioned in commit 464a16ed9a6abbce304fa87fab9c3acdce52a9cc

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 7, 2019, 15:53

mentioned in commit a64a480c5e1d731f3b16e69e9d97326e5d877633

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 7, 2019, 15:53

mentioned in commit e4f9d74e87e42ef6d4cc01eb4ce9d5aef60caae9

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 7, 2019, 15:53

mentioned in commit 315428095a7c7180747893a2af55fadf5bf7a323

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 8, 2019, 16:27

mentioned in commit 2d8b144c9bcb5f7b3d05b95ff82577307769666f

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 8, 2019, 16:27

mentioned in commit f4e54dba0f00f9e542000364d39577ccd52de9f3

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 8, 2019, 16:27

mentioned in commit 2983201f15ee1d9950cf242abfc09214ccc925b6

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 8, 2019, 16:27

mentioned in commit c26e74c9494e1877ecc0e3edd231237f483b8422

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 8, 2019, 16:27

mentioned in commit 8a9753bd32d50e01296d987f934eeaec339a654f

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 8, 2019, 16:27

mentioned in commit 0a25efe565748190af1e350999a0de1315c7d0c7

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 8, 2019, 16:51

mentioned in commit b73b490f03a61bf2234e9199d64b4e9552b46098

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 8, 2019, 16:51

mentioned in commit 312dca29c7aa4f275ad0c8e2e82f1f9afc90886d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 8, 2019, 16:51

mentioned in commit 98801e72e52d8c29d9e1207f4e0ecd320c79588f

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 8, 2019, 16:51

mentioned in commit 2a6b3eec4479c700a66912a0edaad83c226d2dcd

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 8, 2019, 16:51

mentioned in commit f21539bb4a65d0b78c2d945e1299023e7dfe1eda

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 8, 2019, 16:51

mentioned in commit 768b4fdd8a21361b7afba3e6169e3a322e2d86ce

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 8, 2019, 18:00

mentioned in merge request !1215

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 11, 2019, 10:21

mentioned in commit 47fd4d8cb99d75bf0361c987b837df569a1940ef

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 11, 2019, 10:21

mentioned in commit 8e48143ac25e5cad04ae2c135199cde6335f0c6f

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 11, 2019, 10:21

mentioned in commit be8b2d2d9842a324eb483af8e77d26759bee7d4c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 11, 2019, 10:21

mentioned in commit 7742df7790dbd9feef3d0cfa294482f6933102e7

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 11, 2019, 10:21

mentioned in commit a5a467cb1b872e1d2c2771320fc2039db8445730

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 11, 2019, 10:21

mentioned in commit 26d2dd8eb5314e4f8139112d5f59802eae5cd46d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 11, 2019, 11:29

mentioned in commit 64757517bdb504c7a4822303dff779b8861a5c7c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 11, 2019, 11:29

mentioned in commit e7f9756dbec65178c5126a249ce630d17682f37b

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 11, 2019, 11:29

mentioned in commit 36657e20e439a766919aee3127a43c85995d5cfd

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 11, 2019, 11:29

mentioned in commit 3a7ae9f5263ab5c6b8b5bbfeb0f778efedccc7b1

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 11, 2019, 11:29

mentioned in commit ea1e25e91af901f5edeceea613d206ab59aadf0a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 13, 2019, 17:43

mentioned in commit a00f8b375cce105587bf47fc107e62abf9cea269

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 13, 2019, 17:43

mentioned in commit 6ad30069e7ee8da40ad89d56b8a7bf572d3dd7a5

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 13, 2019, 17:43

mentioned in commit 908b469911ec1469a2c04b64ed7f4b23ebf5f87b

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 13, 2019, 17:43

mentioned in commit 905c2c41682e679dfaf8b8f22345fd20dabc358a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 13, 2019, 17:43

mentioned in commit fd926f7c030ad3679d93ab323dfaef4ac5cd284e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 13, 2019, 18:10

mentioned in commit b51efac20b8320e60f535ee657c0a96771dd7f7d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 13, 2019, 18:10

mentioned in commit 96c3713ceaf9921a4a7521f0b159316f8c1ac4c0

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 13, 2019, 18:10

mentioned in commit beb4c251e51102cee24d1385aec82222c9cd2145

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 13, 2019, 18:10

mentioned in commit d2f9ca38fb8ddabce1d6164e88776e088a068a8a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 13, 2019, 18:10

mentioned in commit 11c61a90d79fd8aa5fb818f3e10df19e36f5c5e7

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 13, 2019, 18:10

mentioned in commit 1a288d202831b4bec95e94f67f66f7c2cbe85d38

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 14, 2019, 10:13

mentioned in commit 7ecf392b990c1f9610f84df2ae3ed4b72afa5e64

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 14, 2019, 10:13

mentioned in commit f6dc1ff3637092b363dbced871b2f8955532b4ab

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 14, 2019, 10:13

mentioned in commit 4a873b9f5f4e55ec5c7bd1a3614c50da3ffdf4ca

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 14, 2019, 10:13

mentioned in commit 88f6ceda1ae53c8a18b72bd685ad93bb1b5d96fa

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 14, 2019, 10:13

mentioned in commit 2daf893b302b3155f44517248a3cfe7063376a60

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 14, 2019, 10:13

mentioned in commit 37786a65cf99aafb410a616764e1425e31837eca

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 26, 2019, 11:45

mentioned in commit c4eaba17e9ae5fb7b214145716e6933a088a687a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 26, 2019, 11:54

mentioned in commit 708845e72a590c173753ad11c6d670c7482177c0

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 26, 2019, 14:48

mentioned in commit b3ffe5b8f2d5fd37f4c2063d21cdeda6aed6db8a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 26, 2019, 15:11

mentioned in commit 8b984529ea5f179b2942736ccf063fc1edfaf25e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 26, 2019, 15:39

mentioned in merge request !1261

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 26, 2019, 16:44

mentioned in commit 30f69d48011fb876d6ea1e8da466d2d903dcc93d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 27, 2019, 10:30

mentioned in commit 662d7113811ce793514b50ff30bffe8cfed1a55c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 27, 2019, 13:58

mentioned in commit da5a629dcb8073f247d0c3c1e92fbacab21651e2

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 28, 2019, 15:00

mentioned in commit 11097fe18a994b17738e8ab57a927cfad7db5d0a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Mar 29, 2019, 11:08

mentioned in commit e39174decf2c81f753d9b6c63fd16639a8120141

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Apr 4, 2019, 10:04

mentioned in commit de42f02f863fd174bd4e6e06e95cac97abe5ffcd

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Apr 9, 2019, 09:43

mentioned in commit f02b033368c464b49f2d922d9f4a04ed270daf1e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Apr 9, 2019, 14:16

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Apr 10, 2019, 09:57

mentioned in commit 1a628961290e7a714e537881208f5cf1ff5db434

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Apr 10, 2019, 16:50

mentioned in commit 4d19638f69fa51177e304ac5179cfcb9eaa893b5

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Apr 11, 2019, 16:49

mentioned in commit 3ecd8ae6c23db1ae8bdd80bf7b2074099b7dc0fc

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Apr 12, 2019, 14:54

mentioned in commit 2d075c9920584bc55d667d64c58281e6de0b8455

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Apr 12, 2019, 16:06

mentioned in commit ec0f0757b4b06c0c3055c2dd1c5e6a1052ce05d5

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Apr 16, 2019, 15:20

marked the task **- Make it easy to provide new repo types to the template framework - !1261** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Apr 16, 2019, 15:20

marked the task **- Expose the necessary plugin author facing api in buildstream.plugintestutils - !1261** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Apr 16, 2019, 15:20

closed
