### ISSUE TITLE
Finer grained source caching (tech-debt)

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#982]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/982)
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Apr 2, 2019, 17:22

## Background

[//]: # (Provide a background or the root/source that justifies this task or action.)
A follow up to !1124 and !1214, sources are currently cached and staged altogether, due to some plugins (i.e. patch) requiring previous sources staged to make sense. Being able to more finely cache sources would be beneficial however, allowing more sharing between both elements and different projects.

To allow for this we need to add another flag to plugins, very similar to the existing flags `BST_REQUIRES_PREVIOUS_SOURCES_TRACK`/`FETCH`, for staging. This should only require changes to logic in the `Element` class, to ensure that sources are staged appropriately depending on whether they require previous sources or not. All sources before a source plugin marked to require previous sources to stage will have to be staged together as they currently are, all afterwards can be staged separately. This will have to be taken into account both where they are staged and where they are cached, as well as for key generation.

## Task description

[//]: # (Short summary of the action to be executed)

* [ ] Add `BST_REQUIRES_PREVIOUS_SOURCES_TRACK`, and logic in `Element` that uses it.
* [ ] Look through and mark relevant plugins with this flag (think it's only patch in the main repo)
* [ ] Add some tests to ensure that sources are staged separately when possible.

## Acceptance Criteria

[//]: # (Acceptance criteria should follow the S.M.A.R.T. principle https://en.wikipedia.org/wiki/SMART_criteria )
Extra tests that show sources are staged separately when appropriate.

----
[//]: # (To review information about possible relevant labels for this issue please view the list of labels: https://gitlab.com/BuildStream/buildstream/labels)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Apr 2, 2019, 17:23

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Apr 2, 2019, 17:23

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Apr 30, 2019, 18:13

mentioned in commit 6bc6f22f0c8bce165539885f84ad22f4e75c3ba6

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Apr 30, 2019, 18:15

mentioned in merge request !1319

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on May 1, 2019, 10:46

mentioned in commit a17ab4e1706a760edbb1a2e02c67892318dc1878

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on May 1, 2019, 11:20

mentioned in commit b018d21a9b6cc0cd40c5108a1ab12087d49f5664

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on May 8, 2019, 12:40

mentioned in commit 12fd8281da1cfee6e41f92056345c2f4cb806639

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on May 8, 2019, 15:23

mentioned in commit ffb81bd2d1612518dbd3e0a881a359203059f1f5

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on May 8, 2019, 15:28

mentioned in commit 7456f2a6956fa768ec0120e527f747a72fef15a3

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on May 9, 2019, 16:43

mentioned in commit f60dc8b16b8dc4916f4a96c917fa732d0323464f

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on May 9, 2019, 16:43

mentioned in commit 7bad9897038ec8b44be232a2033d1022a7af3b4b

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on May 9, 2019, 16:44

mentioned in commit be47bb5a431acc92d83a1ef94dbc6fda93d7ac96

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on May 9, 2019, 16:44

mentioned in commit 12e244d753587f0df82d529397e04a4146742d58

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on May 13, 2019, 13:56

mentioned in commit acd6c75bbd7def9c9a80d663313044d9ed6211c9

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on May 13, 2019, 13:56

mentioned in commit bd30f1b97bd76a7c38f6217d1bc7d660d155389d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on May 14, 2019, 11:26

mentioned in commit 7ad87c75bdf7c1961189bc92f271fcaf4aa75019

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on May 14, 2019, 11:26

mentioned in commit 0c33a3e14b65754717f4bac9c160c198b2b72744

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on May 14, 2019, 14:05

mentioned in commit 36559be383f2148b103b0b5034dc9a231d93f0be

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on May 14, 2019, 14:05

mentioned in commit 995ff5ac2b357fb7da716eabc4b436b8e05d6f26

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on May 14, 2019, 15:08

closed via merge request !1319

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on May 14, 2019, 15:08

mentioned in commit 615c93b5e9c8ddc6734a13cc55b17f33b6c3182f
