### ISSUE TITLE
Further remote execution testing

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#994]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/994)
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Apr 12, 2019, 10:06

## Background

Now that we are testing remote execution in CI (https://gitlab.com/BuildStream/buildstream/merge_requests/1239), perhaps we should consider broadening our remote execution tests.

Currently we have two "simple" remote execution tests in [*tests/remoteexecution/simple.py*](https://gitlab.com/BuildStream/buildstream/blob/master/tests/remoteexecution/simple.py) which:

1. Build autotools with remote execution, check it out and verify it contains the right "stuff"
2. Build autotools remotely (again), then shell into it and execute `/usr/bin/hello` and ensure we get the right output.

This is a great start to remote execution testing in BuildStream but it far from comprehensive. I propose that we simply add some more tests. 

## Task description

I'd imagine that there is an endless number of tests we could write for this, however, to start with I propose that we should add the following tests: 

* [ ] Build *something* 'bigger' than autotools.
    - The autotools example is great, however, why don't we try to build something a bit 'bigger', for example, a subset of freedesktop? Although I'd recommend avoiding the base ostree import for CI jobs as this is slow.
* [x] Build *something* via a junction.
    - We already have a junction example in our docs. This just builds an element which depends on autotools via a junction, we could use this.
* [x] Build autotools with `bst --cache-buildtrees always build autotools/amhello.bst`
    - This should mean that the buildtree of the artifact is locally cached (once built remotely), we should verify that it is there.
    - We'd have to obtain the correct digest and then extract the *builddir* from the artifact.
    - Some of our integration tests do something similar already.
* [x] Write an element that **will fail when built** and verify that this artifact contains a buildtree.
    - Again, we'd have to obtain the correct digest and then extract the *builddir* from the artifact.

I'm open to any more suggestions, but I would like to avoid flooding this issue with so many additional tests that it never closes.

-----

## Aside: Running the remote execution test-suite locally

To run the remote execution tests, you need to have a buildgrid instance up and running, and at least one bot on port 50051.
Now, I personally did not find it trivial to get `tox -- --remote-execution tests/remoteexecution` to produce 'passing' tests. However, here is what my final setup looked like:

1. These tests require a couple of environment vairables: `export ARTIFACT_CACHE_SERVICE=http://localhost:11001 REMOTE_EXECUTION_SERVICE=http://localhost:50051`
    - Note that I don't even think you need ARTIFACT_CACHE_SERVICE... but hey ho.
2. I had to slightly modify [Martin's Docker-compose manifest](https://gitlab.com/BuildGrid/buildgrid.hub.docker.com). To use these clone my fork: https://gitlab.com/jennis/buildgrid.hub.docker.com/tree/jennis/work_with_bst_tests and checkout the branch jennis/work_with_bst_tests

Now, you should be able to run the remote-execution tests, from one terminal:

    docker-compose -f Composefile.buildstream.yml up --scale bots=2

Then, from another terminal, change to your BuildStream clone and:

    export ARTIFACT_CACHE_SERVICE=http://localhost:11001 REMOTE_EXECUTION_SERVICE=http://localhost:50051
    tox -- --remote-execution tests/remoteexecution

Alternatively, you can install BuildGrid and BuildBox fuse then start your own local buildgrid instance (with all the correct configuration...) and BuildBox (fuse) worker. Just follow the README instructions for both repos, but I found this difficult to get working.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Apr 12, 2019, 11:54

I definitely think testing the buildtree use-cases via remote-execution is of value

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on May 10, 2019, 13:48

changed title from **Further remote exe{-uc-}tion testing** to **Further remote exe{+cu+}tion testing**

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 13:22

mentioned in commit 85664fbead31ae60d95f2b448f5272bbdbda0407

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 14:59

mentioned in commit f354d73dab5f5ec5f61d2f884ba5c3b3d695d51e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 14:59

mentioned in commit 56a2ad807f74d0ca474bdad0844ee26ced4aba62

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 15:10

assigned to [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 16:10

mentioned in commit 2bc0472ec8e3c40911b67befe45fdf59282c261a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 16:10

mentioned in commit 887e08d56e490873aaee78ddb698aa7118e91d06

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 1, 2019, 16:10

mentioned in commit 86995ed9d0f6b42012a8a535209087b337fcf32f

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 4, 2019, 09:27

marked the task **Build *something* via a junction.** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 4, 2019, 09:27

marked the task **Build autotools with `bst --cache-buildtrees always build autotools/amhello.bst`** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 4, 2019, 09:27

marked the task **Write an element that **will fail when built** and verify that this artifact contains a buildtree.** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 4, 2019, 09:27

marked the task **Build autotools with `bst --cache-buildtrees always build autotools/amhello.bst`** as incomplete

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 4, 2019, 09:27

marked the task **Build autotools with `bst --cache-buildtrees always build autotools/amhello.bst`** as completed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 4, 2019, 13:49

mentioned in merge request !1452

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 4, 2019, 14:03

mentioned in commit 0b62d429dc2345265de898c9fe4f862536b31a12

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 4, 2019, 14:03

mentioned in commit f0a6ad7006b493dfb564ee5e4fd6e2aaa74e4586

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 4, 2019, 14:03

mentioned in commit 69e77ee7482d1a2cc978a2110954b23382187248

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 5, 2019, 13:40

mentioned in commit 76b5876f25655bcd1498aac472017f163e1f622c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 5, 2019, 13:40

mentioned in commit 21e8c2b37972e621412d001dccd67a9f605e4f05

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 5, 2019, 13:40

mentioned in commit be4c37ab4eeb3e7b1db4e710d9c5eece48978a92

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 10, 2019, 09:56

mentioned in commit 2a4b61d2f3c13f267e7d6745c445c6da4b4c6b18

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 10, 2019, 09:56

mentioned in commit 9f61f4f67e0b60129a28cd26ca502b949ffab670

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 10, 2019, 09:56

mentioned in commit ad18cd16bee475911d561fd82df9250765f3626a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 11, 2019, 12:06

mentioned in commit c0cb7bd5524ecef3978f8672be6e64f82dd91379

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 11, 2019, 12:06

mentioned in commit 81f13fa40fbf8517d8a69cdddca22447e2ba2c59

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 11, 2019, 12:06

mentioned in commit 0c805cac8416b8eb08ff18bd25830a1c55883425

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 11, 2019, 12:22

mentioned in commit 95bbb580d333635ffbcc822bb24e6b0e95077a0e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 11, 2019, 12:22

mentioned in commit b34c56c8e3b283a16e6f7b11af5363d1ae6ab6a8

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 11, 2019, 12:22

mentioned in commit ab8d096bc37cfb410423f48f95c310e39b1f78ae

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 11, 2019, 15:29

mentioned in commit e884af125fe547c0388f430f5036300613e1af8b

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 11, 2019, 15:29

mentioned in commit a81e468cf05f27d5009938eed8b10a78d450b3a4

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 11, 2019, 15:29

mentioned in commit 67d5a76093ab0198970fdc6b25815e4ec4697f58

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 11, 2019, 15:41

mentioned in commit 40ab4dc30cb7dcfdbf802b3a6ca0a2521b1a6299

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 11, 2019, 15:41

mentioned in commit ddd70be1b05f8fde1ff0c39a909687400bcc6878

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 11, 2019, 15:41

mentioned in commit ea527cd12cb89f901ddd8d26794af56b0e903e77

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 11, 2019, 15:43

mentioned in commit 6fc11d2d486c0ae2ccc5527b946a90d87b1a9a8c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 11, 2019, 15:43

mentioned in commit 54be79a2a7abe683cfbc58b5427a7c0a765777e6

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 11, 2019, 15:43

mentioned in commit 6fb7ca9ccd11ef80c58b3d7c4a969c4a796693ec

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 12, 2019, 09:36

mentioned in commit e562a88bfea1397cae22aae702c8be7067055c01

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 12, 2019, 09:36

mentioned in commit d43ee99356cc8a3569d0dddd61ca00ab484c3ca8

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 12, 2019, 09:36

mentioned in commit e10e67b87c766c0a5ee8ca1eb0e39b30735aa878

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 12, 2019, 18:39

mentioned in commit 817e553b69fe4ed33dd6260a2809ca94e1edc843

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 12, 2019, 18:39

mentioned in commit 4dbf8810fbc71f2b9803d994d9db847ab4104dd8

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 12, 2019, 18:39

mentioned in commit ecfdfd419323fa1be080459ff81e613b9da82978

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Jul 12, 2019, 19:06

closed via merge request !1452

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Jul 12, 2019, 19:06

mentioned in commit c6886c251fa3f65aa1cddb533c6121c2eb7c4ed6

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jul 24, 2019, 12:57

This should not be closed, there is still a check-box that's not been addressed: re-opening.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jul 24, 2019, 12:57

reopened
